USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ACCOUNTS_LEVELS]') AND type in (N'U'))
BEGIN
CREATE TABLE [ACCOUNTS_LEVELS](
	[ACCOUNT_LEVEL_ID] [int] NOT NULL,
	[NAME] [varchar](max) NULL,
 CONSTRAINT [PK_ACCOUNTS_LEVELS] PRIMARY KEY CLUSTERED 
(
	[ACCOUNT_LEVEL_ID] ASC
)
)
END
GO
