
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[AGENTS_MOLS]') AND type in (N'U'))
BEGIN
CREATE TABLE [AGENTS_MOLS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SUBJECT_ID] [int] NOT NULL DEFAULT ((-2)),
	[AGENT_ID] [int] NOT NULL,
	[MOL_ID] [int] NULL,
	[POST_NAME] [varchar](75) NULL,
	[RESPONSE] [varchar](max) NULL,
	[ACCOUNT_LEVEL_ID] [int] NULL,
	[NODE] [hierarchyid] NULL,
	[NAME] [varchar](50) NULL,
	[PARENT_ID] [int] NULL,
	[HAS_CHILDS] [bit] NOT NULL DEFAULT ((0)),
	[LEVEL_ID] [int] NULL,
	[SORT_ID] [float] NULL,
	[IS_DELETED] [bit] NOT NULL DEFAULT ((0)),
	[ADD_DATE] [datetime] DEFAULT getdate(),
	[ADD_MOL_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO


IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[AGENTS_MOLS]') AND name = N'IX_AGENTS_MOLS')
CREATE NONCLUSTERED INDEX [IX_AGENTS_MOLS] ON [AGENTS_MOLS]
(
	[AGENT_ID] ASC,
	[NODE] ASC
)
GO
