IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'AGENTS_GROUPS_NAMES') AND type in (N'U'))
BEGIN
CREATE TABLE AGENTS_GROUPS_NAMES(
	GROUP_ID int IDENTITY PRIMARY KEY,
	NAME varchar(50) NULL,
	IS_DELETED bit NULL DEFAULT (0),
	ADD_DATE datetime DEFAULT getdate()
)
END
GO

