USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[AGENTS_CATEGORIES]') AND type in (N'U'))
BEGIN
CREATE TABLE [AGENTS_CATEGORIES](
	[CATEGORY_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](30) NULL,
	[IS_DELETED] [bit] NOT NULL,
 CONSTRAINT [PK_AGENTS_CATEGORIES] PRIMARY KEY CLUSTERED 
(
	[CATEGORY_ID] ASC
)
)
END
GO
