USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[BDR_ARTICLES_STATUSES]') AND type in (N'U'))
BEGIN
CREATE TABLE [BDR_ARTICLES_STATUSES](
	[STATUS_ID] [int] NOT NULL,
	[NAME] [varchar](32) NULL,
 CONSTRAINT [PK_BDR_ARTICLES_STATUSES] PRIMARY KEY CLUSTERED 
(
	[STATUS_ID] ASC
)
)
END
GO
