USE CISP_SHARED
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[BDR_PERIODS]') AND type in (N'U'))
BEGIN
CREATE TABLE [BDR_PERIODS](
	[BDR_PERIOD_ID] [int] IDENTITY(1,1) NOT NULL,
	[TYPE_ID] [int] NULL,
	[NAME] [varchar](100) NULL,
	[DATE_START] [datetime] NULL,
	[DATE_END] [datetime] NULL,
    PRIMARY KEY CLUSTERED 
    (
        [BDR_PERIOD_ID] ASC
    )
)
END
GO

