
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[BUDGETS_SUBJECTS]') AND type in (N'U'))
BEGIN
CREATE TABLE [BUDGETS_SUBJECTS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[BUDGET_ID] [int] NULL,
	[SUBJECT_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO
