
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[BUDGETS_SHARES]') AND type in (N'U'))
BEGIN
CREATE TABLE [BUDGETS_SHARES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[BUDGET_ID] [int] NULL,
	[MOL_ID] [int] NULL,
	[A_READ] [tinyint] NOT NULL DEFAULT ((1)),
	[A_UPDATE] [tinyint] NOT NULL DEFAULT ((0)),
	[A_ACCESS] [tinyint] NOT NULL DEFAULT ((0)),
 CONSTRAINT [PK_BUDGETS_SHARES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[BUDGETS_SHARES]') AND name = N'IX_BUDGETS_SHARES')
CREATE UNIQUE NONCLUSTERED INDEX [IX_BUDGETS_SHARES] ON [BUDGETS_SHARES]
(
	[MOL_ID] ASC,
	[BUDGET_ID] ASC
)
GO
