
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[BUDGETS_TOTALS_SUBJECTS]') AND type in (N'U'))
BEGIN
CREATE TABLE [BUDGETS_TOTALS_SUBJECTS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[BUDGET_ID] [int] NOT NULL,
	[SUBJECT_ID] [int] NULL,
	[VALUE_LEFT] [decimal](18, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[BUDGETS_TOTALS_SUBJECTS]') AND name = N'IX_BUDGETS_TOTALS_SUBJECTS')
CREATE UNIQUE NONCLUSTERED INDEX [IX_BUDGETS_TOTALS_SUBJECTS] ON [BUDGETS_TOTALS_SUBJECTS]
(
	[BUDGET_ID] ASC,
	[SUBJECT_ID] ASC
)
GO
