USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[BUDGETS_TYPES]') AND type in (N'U'))
BEGIN
CREATE TABLE [BUDGETS_TYPES](
	[TYPE_ID] [int] NOT NULL,
	[NAME] [varchar](30) NULL,
 CONSTRAINT [PK_BUDGETS_TYPES] PRIMARY KEY CLUSTERED 
(
	[TYPE_ID] ASC
)
)
END
GO
