
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[BUDGETS_BY_VENDORS]') AND type in (N'U'))
BEGIN
CREATE TABLE [BUDGETS_BY_VENDORS](
	[BUDGET_ID] [int] NOT NULL,
	[SUBJECT_ID] [int] NULL,
	[PROJECT_ID] [int] NULL,
	[NAME] [varchar](255) NULL,
	[NODE] [hierarchyid] NULL,
	[PARENT_ID] [int] NULL,
	[HAS_CHILDS] [bit] NOT NULL DEFAULT ((0)),
	[LEVEL_ID] [int] NULL,
	[SORT_ID] [float] NULL,
	[IS_DELETED] [bit] NOT NULL DEFAULT ((0)),
 CONSTRAINT [PK_BUDGETS_BY_VENDORS] PRIMARY KEY CLUSTERED 
(
	[BUDGET_ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[BUDGETS_BY_VENDORS]') AND name = N'IX_BUDGETS_BY_VENDORS')
CREATE NONCLUSTERED INDEX [IX_BUDGETS_BY_VENDORS] ON [BUDGETS_BY_VENDORS]
(
	[PARENT_ID] ASC,
	[HAS_CHILDS] ASC,
	[NAME] ASC
)
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[BUDGETS_BY_VENDORS]') AND name = N'IX_BUDGETS_BY_VENDORS_1')
CREATE NONCLUSTERED INDEX [IX_BUDGETS_BY_VENDORS_1] ON [BUDGETS_BY_VENDORS]
(
	[NODE] ASC
)
GO
