
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[BUDGETS_ARTICLES]') AND type in (N'U'))
BEGIN
CREATE TABLE [BUDGETS_ARTICLES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[BUDGET_ID] [int] NOT NULL,
	[PARENT_ID] [int] NULL,
	[ARTICLE_ID] [int] NOT NULL,
	[PAYDELAY] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO
