
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[BUDGETS_PLANS]') AND type in (N'U'))
BEGIN
CREATE TABLE [BUDGETS_PLANS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[BUDGET_ID] [int] NOT NULL,
	[GOAL_ACCOUNT_ID] [int] NOT NULL CONSTRAINT [DF_BUDGETS_PLANS_GOAL_ACCOUNT_ID]  DEFAULT ((0)),
	[ARTICLE_ID] [int] NOT NULL,
	[BUDGET_PERIOD_ID] [int] NOT NULL,
	[PLAN_RUR] [decimal](18, 2) NULL,
	[NODE] [hierarchyid] NULL,
	[HAS_CHILDS] [bit] NOT NULL CONSTRAINT [DF__BUDGETS_P__HAS_C__3628A90C]  DEFAULT ((0)),
	[FACT_RUR_GOAL] [decimal](18, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[BUDGETS_PLANS]') AND name = N'IX_BUDGETS_PLANS')
CREATE NONCLUSTERED INDEX [IX_BUDGETS_PLANS] ON [BUDGETS_PLANS]
(
	[BUDGET_ID] ASC,
	[BUDGET_PERIOD_ID] ASC,
	[NODE] ASC
)
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[BUDGETS_PLANS]') AND name = N'IX_PROJECTS_BDR')
CREATE UNIQUE NONCLUSTERED INDEX [IX_PROJECTS_BDR] ON [BUDGETS_PLANS]
(
	[BUDGET_ID] ASC,
	[GOAL_ACCOUNT_ID] ASC,
	[ARTICLE_ID] ASC,
	[BUDGET_PERIOD_ID] ASC
)
GO
