USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[BUDGETS_STATUSES]') AND type in (N'U'))
BEGIN
CREATE TABLE [BUDGETS_STATUSES](
	[STATUS_ID] [int] NOT NULL,
	[NAME] [varchar](50) NOT NULL,
 CONSTRAINT [PK_BUDGETS_STATUSES] PRIMARY KEY CLUSTERED 
(
	[STATUS_ID] ASC
)
)
END
GO
