
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[BUDGETS_GOALS]') AND type in (N'U'))
BEGIN
CREATE TABLE [BUDGETS_GOALS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[BUDGET_ID] [int] NULL,
	[GOAL_ACCOUNT_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[BUDGETS_GOALS]') AND name = N'IX_BUDGETS')
CREATE UNIQUE NONCLUSTERED INDEX [IX_BUDGETS] ON [BUDGETS_GOALS]
(
	[BUDGET_ID] ASC,
	[GOAL_ACCOUNT_ID] ASC
)
GO
