
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[BUDGETS_PLANFACT]') AND type in (N'U'))
BEGIN
CREATE TABLE [BUDGETS_PLANFACT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[BUDGET_ID] [int] NULL,
	[GOAL_ACCOUNT_ID] [int] NULL,
	[ARTICLE_ID] [int] NULL,
	[PERIOD_ID] [varchar](16) NULL,
	[WEEK_ID] [varchar](20) NULL,
	[VALUE_PLAN] [decimal](18, 2) NULL,
	[VALUE_FACT] [decimal](18, 2) NULL,
	[D_CALC] [datetime] NULL DEFAULT (getdate()),
	[ACCOUNT_ID] [int] NULL,
	[D_DOC] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO


IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[BUDGETS_PLANFACT]') AND name = N'IX_BUDGETS_PLANFACT')
CREATE NONCLUSTERED INDEX [IX_BUDGETS_PLANFACT] ON [BUDGETS_PLANFACT]
(
	[BUDGET_ID] ASC,
	[GOAL_ACCOUNT_ID] ASC,
	[ARTICLE_ID] ASC
)
GO
