USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CALENDAR]') AND type in (N'U'))
BEGIN
CREATE TABLE [CALENDAR](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[WORKDAY_ID] [int] NULL,
	[DAY_DATE] [datetime] NULL,
	[TYPE] [int] NULL,
 CONSTRAINT [PK_CALENDAR] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[CALENDAR]') AND name = N'IX_DAY_DATE')
CREATE UNIQUE NONCLUSTERED INDEX [IX_DAY_DATE] ON [CALENDAR]
(
	[DAY_DATE] ASC
)
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[CALENDAR]') AND name = N'IX_WORKDAY')
CREATE NONCLUSTERED INDEX [IX_WORKDAY] ON [CALENDAR]
(
	[WORKDAY_ID] ASC
)
GO
