USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CCY_RATES_CROSS]') AND type in (N'U'))
BEGIN
CREATE TABLE [CCY_RATES_CROSS](
	[D_DOC] [date] NOT NULL,
	[FROM_CCY_ID] [char](3) NOT NULL,
	[TO_CCY_ID] [char](3) NOT NULL,
	[RATE] [float] NOT NULL,
 CONSTRAINT [PK_CCY_RATES_CROSS] PRIMARY KEY CLUSTERED 
(
	[D_DOC] ASC,
	[FROM_CCY_ID] ASC,
	[TO_CCY_ID] ASC
)
)
END
GO
