USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CITIES]') AND type in (N'U'))
BEGIN
CREATE TABLE [CITIES](
	[CITY_ID] [int] NOT NULL,
	[NAME] [varchar](50) NULL,
	[D_TIMESTAMP] [datetime] NULL,
 CONSTRAINT [PK_CITIES] PRIMARY KEY CLUSTERED 
(
	[CITY_ID] ASC
)
)
END
GO
