
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[DEALS_MAP_INSTANTS]') AND type in (N'U'))
BEGIN
CREATE TABLE [DEALS_MAP_INSTANTS](
	[INSTANT_ID] [int] NOT NULL,
	[INSTANT_NAME] [varchar](50) NULL,
	[TASK_NAME] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[INSTANT_ID] ASC
)
)
END
GO

