USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[DEALS_DOCS_TYPES]') AND type in (N'U'))
BEGIN
CREATE TABLE [DEALS_DOCS_TYPES](
	[TYPE_ID] [int] NOT NULL,
	[NAME] [varchar](50) NULL,
 CONSTRAINT [PK_DEALS_DOCS_TYPES] PRIMARY KEY CLUSTERED 
(
	[TYPE_ID] ASC
)
)
END
GO
