
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[DEALS_CREDITS_LEFTS]') AND type in (N'U'))
BEGIN
CREATE TABLE [DEALS_CREDITS_LEFTS](
	[SUBJECT_ID] [int] NULL,
	[D_DOC] [datetime] NULL,
	[BUDGET_ID] [int] NULL,
	[ARTICLE_ID] [int] NULL,
	[VALUE] [decimal](18, 2) NULL
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[DEALS_CREDITS_LEFTS]') AND name = N'IX_DEALS_CREDITS_LEFTS')
CREATE UNIQUE CLUSTERED INDEX [IX_DEALS_CREDITS_LEFTS] ON [DEALS_CREDITS_LEFTS]
(
	[SUBJECT_ID] ASC,
	[D_DOC] ASC,
	[BUDGET_ID] ASC,
	[ARTICLE_ID] ASC
)
GO
