
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[DEALS_COSTS_DETAILS]') AND type in (N'U'))
BEGIN
CREATE TABLE [DEALS_COSTS_DETAILS](
	[DEAL_ID] [int] NULL,
	[DEAL_NUMBER] [varchar](50) NULL,
	[COST_INFO] [xml] NULL,
	[COUNT_PRODUCTS] [int] NULL,
	[VALUE_BDR] [decimal](18, 2) NULL,
	[VALUE_BDS] [decimal](18, 2) NULL,
	[VALUE_TRANSFER_BDR] [decimal](18, 2) NULL,
	[VALUE_TRANSFER_BDS] [decimal](18, 2) NULL,
	[UPDATE_DATE] [datetime] NULL
)
END
GO


IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[DEALS_COSTS_DETAILS]') AND name = N'IX_DEAL')
CREATE NONCLUSTERED INDEX [IX_DEAL] ON [DEALS_COSTS_DETAILS]
(
	[DEAL_ID] ASC
)
GO
SET ANSI_PADDING ON

GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[DEALS_COSTS_DETAILS]') AND name = N'IX_DEAL_NUMBER')
CREATE NONCLUSTERED INDEX [IX_DEAL_NUMBER] ON [DEALS_COSTS_DETAILS]
(
	[DEAL_NUMBER] ASC
)
GO
