
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[DEALS_COSTS_KOEFS]') AND type in (N'U'))
BEGIN
CREATE TABLE [DEALS_COSTS_KOEFS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SLICE] [varchar](50) NOT NULL,
	[SUBJECT_ID] [int] NOT NULL,
	[SHORT_NAME] [varchar](50) NOT NULL,
	[ARTICLE_RATIO] [float] NULL,
PRIMARY KEY NONCLUSTERED 
(
	[SLICE] ASC,
	[SUBJECT_ID] ASC,
	[SHORT_NAME] ASC
)
)
END
GO


IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[DEALS_COSTS_KOEFS]') AND name = N'IX_DEALS_COSTS_KOEFS')
CREATE CLUSTERED INDEX [IX_DEALS_COSTS_KOEFS] ON [DEALS_COSTS_KOEFS]
(
	[ID] ASC
)
GO
