
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[DEALS_MOLS]') AND type in (N'U'))
BEGIN
CREATE TABLE [DEALS_MOLS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DEAL_ID] [int] NULL,
	[MOL_ID] [int] NULL,
	[KV] [decimal](5, 2) NULL,
	[KC] [decimal](5, 2) NULL,
	[NOTE] [varchar](250) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_DEALS_MOLS]') AND parent_object_id = OBJECT_ID(N'[DEALS_MOLS]'))
ALTER TABLE [DEALS_MOLS]  WITH CHECK ADD  CONSTRAINT [FK_DEALS_MOLS] FOREIGN KEY([DEAL_ID])
REFERENCES [DEALS] ([DEAL_ID])
ON DELETE CASCADE
GO

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_DEALS_MOLS]') AND parent_object_id = OBJECT_ID(N'[DEALS_MOLS]'))
ALTER TABLE [DEALS_MOLS] CHECK CONSTRAINT [FK_DEALS_MOLS]
GO
