
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[DEALS_DOCS]') AND type in (N'U'))
BEGIN
CREATE TABLE [DEALS_DOCS](
	[DOC_ID] [int] IDENTITY(1,1) NOT NULL,
	[TYPE_ID] [int] NULL,
	[NUMBER] [varchar](50) NULL,
	[D_DOC] [datetime] NULL,
	[EXTERNAL_ID] [int] NULL,
 CONSTRAINT [PK_DEALS_DOCS] PRIMARY KEY CLUSTERED 
(
	[DOC_ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[DEALS_DOCS]') AND name = N'IX_DEALS_DOCS')
CREATE UNIQUE NONCLUSTERED INDEX [IX_DEALS_DOCS] ON [DEALS_DOCS]
(
	[TYPE_ID] ASC,
	[D_DOC] ASC,
	[NUMBER] ASC
)
GO
