
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[DEALS_ARTICLES_PRIORITY]') AND type in (N'U'))
BEGIN
CREATE TABLE [DEALS_ARTICLES_PRIORITY](
	[ARTICLE_SHORT_NAME] [varchar](100) NOT NULL,
	[SORT_STD] [float] NULL,
	[SORT_NDS0] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[ARTICLE_SHORT_NAME] ASC
)
)
END
GO

