
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[DEALS_MAP_BUDGETS_BACK]') AND type in (N'U'))
BEGIN
CREATE TABLE [DEALS_MAP_BUDGETS_BACK](
	[ARTICLE_ID] [int] NOT NULL,
	[BudgetId] [int] NULL,
	[BudgetName] [varchar](250) NULL,
PRIMARY KEY CLUSTERED 
(
	[ARTICLE_ID] ASC
)
)
END
GO

