
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[DEALS_MAP_ALIASES]') AND type in (N'U'))
BEGIN
CREATE TABLE [DEALS_MAP_ALIASES](
	[ALIAS_ID] [int] NOT NULL,
	[ALIAS_NAME] [varchar](50) NULL,
	[TASK_NAME] [varchar](50) NULL,
	[ARTICLE_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ALIAS_ID] ASC
)
)
END
GO

