IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[DEALS_FUNDING]') AND type in (N'U'))
BEGIN
CREATE TABLE [DEALS_FUNDING](
	ROW_ID INT IDENTITY PRIMARY KEY,
    [DEAL_ID] [int] NULL,
	[BUDGET_ID] [int] NULL,
	[LAYER] [varchar](20) NULL,
	[D_CALC] [date] NOT NULL DEFAULT (getdate()),
	[VALUE_BDS] [float] NULL,
	[VALUE_PAID] [float] NULL,
	[VALUE_TRANZIT] [float] NULL,
	[VALUE_TRANSFER] [float] NULL,
	[VALUE_EXP1] [float] NULL,
	[VALUE_EXP2] [float] NULL,
	[VALUE_EXP3] [float] NULL,
	[VALUE_EXP4] [float] NULL,
	[VALUE_EXP5] [float] NULL,
	[VALUE_EXP6] [float] NULL,
	[VALUE_EXP_NOINC_1] [float] NULL,
	[VALUE_EXP_NOINC_2] [float] NULL,
	[VALUE_EXP_NOINC_3] [float] NULL,
	[VALUE_EXP_NOINC_31] [float] NULL,
	[VALUE_EXP_NOINC_32] [float] NULL,
	[CALC_MOL_ID] [int] NULL
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[DEALS_FUNDING]') AND name = N'IX_DEAL_FUNDING')
CREATE INDEX [IX_DEAL_FUNDING] ON [DEALS_FUNDING]
(
	[DEAL_ID] ASC,
	[LAYER] ASC
)
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[DEALS_FUNDING]') AND name = N'IX_BUDGET')
CREATE INDEX [IX_BUDGET] ON [DEALS_FUNDING]
(
	[BUDGET_ID] ASC
)
GO
