
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[DEALS_MAP_SUBJECTS]') AND type in (N'U'))
BEGIN
CREATE TABLE [DEALS_MAP_SUBJECTS](
	[PLACE_NAME] [varchar](50) NOT NULL,
	[SUBJECT_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[PLACE_NAME] ASC
)
)
END
GO

