
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[DEALS_META_TASKS]') AND type in (N'U'))
BEGIN
CREATE TABLE [DEALS_META_TASKS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DEAL_TYPE_ID] [int] NULL,
	[TASK_NAME] [varchar](64) NULL,
	[OPTION_KEY] [varchar](64) NULL,
	[BIND_TYPE] [varchar](16) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO

