
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[DEALS_MAP_STAGES]') AND type in (N'U'))
BEGIN
CREATE TABLE [DEALS_MAP_STAGES](
	[STAGE_ID] [int] NULL,
	[STAGE_NAME] [varchar](50) NULL,
	[TASK_NAME] [varchar](50) NULL
)
END
GO

