
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[DOCUMENTS_DICT_ROUTES]') AND type in (N'U'))
BEGIN
CREATE TABLE [DOCUMENTS_DICT_ROUTES](
	[TENANT_ID] [int] NOT NULL DEFAULT ((1)),
	[DICT_ROUTE_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](50) NULL,
	[NOTE] [nvarchar](max) NULL,
	[ADD_DATE] [datetime] DEFAULT getdate(),
	[IS_DELETED] [bit] NOT NULL DEFAULT ((0)),
PRIMARY KEY CLUSTERED 
(
	[DICT_ROUTE_ID] ASC
)
)
END
GO
