USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[DOCUMENTS_STATUSES]') AND type in (N'U'))
BEGIN
CREATE TABLE [DOCUMENTS_STATUSES](
	[STATUS_ID] [int] NOT NULL,
	[NAME] [nvarchar](30) NULL,
 CONSTRAINT [PK_DOCUMENTS_STATUSES] PRIMARY KEY CLUSTERED 
(
	[STATUS_ID] ASC
)
)
END
GO
