USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[DOCUMENTS_DICT_RESPONSIBLES]') AND type in (N'U'))
BEGIN
CREATE TABLE [DOCUMENTS_DICT_RESPONSIBLES](
	[TENANT_ID] [int] NOT NULL,
	[RESPONSIBLE_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](50) NULL,
	[SHORT_NAME] [nvarchar](20) NULL,
	[NOTE] [nvarchar](max) NULL,
	[ADD_DATE] [datetime] NULL,
 CONSTRAINT [PK_DOCUMENTS_DICT_RESPONSIBLES] PRIMARY KEY CLUSTERED 
(
	[RESPONSIBLE_ID] ASC
)
)
END
GO
