
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[DOCUMENTS_MOLS]') AND type in (N'U'))
BEGIN
CREATE TABLE [DOCUMENTS_MOLS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DOCUMENT_ID] [int] NOT NULL,
	[MOL_ID] [int] NOT NULL,
	[A_READ] [tinyint] NOT NULL DEFAULT ((1)),
	[A_UPDATE] [tinyint] NOT NULL DEFAULT ((0)),
	[A_ACCESS] [tinyint] NOT NULL DEFAULT ((0)),
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[DOCUMENTS_MOLS]') AND name = N'IX_DOCUMENTS_MOLS')
CREATE UNIQUE NONCLUSTERED INDEX [IX_DOCUMENTS_MOLS] ON [DOCUMENTS_MOLS]
(
	[DOCUMENT_ID] ASC,
	[MOL_ID] ASC
)
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_DOCUMENTS_MOLS_DOCUMENT_ID]') AND parent_object_id = OBJECT_ID(N'[DOCUMENTS_MOLS]'))
ALTER TABLE [DOCUMENTS_MOLS]  WITH CHECK ADD  CONSTRAINT [FK_DOCUMENTS_MOLS_DOCUMENT_ID] FOREIGN KEY([DOCUMENT_ID])
REFERENCES [DOCUMENTS] ([DOCUMENT_ID])
ON DELETE CASCADE
GO

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_DOCUMENTS_MOLS_DOCUMENT_ID]') AND parent_object_id = OBJECT_ID(N'[DOCUMENTS_MOLS]'))
ALTER TABLE [DOCUMENTS_MOLS] CHECK CONSTRAINT [FK_DOCUMENTS_MOLS_DOCUMENT_ID]
GO
