USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[EVENTS_STATUSES]') AND type in (N'U'))
BEGIN
CREATE TABLE [EVENTS_STATUSES](
	[STATUS_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](30) NULL,
	[IS_DELETED] [bit] NOT NULL,
 CONSTRAINT [PK_EVENTS_STATUSES] PRIMARY KEY CLUSTERED 
(
	[STATUS_ID] ASC
)
)
END
GO
