USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[EVENTS_FEEDS_TYPES]') AND type in (N'U'))
BEGIN
CREATE TABLE [EVENTS_FEEDS_TYPES](
	[FEED_ID] [int] NOT NULL,
	[FEED_TYPE_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[SHORT_NAME] [varchar](30) NOT NULL,
	[DESCRIPTION] [nvarchar](512) NULL,
	[IS_ALERT] [bit] NULL,
 CONSTRAINT [PK_EVENTS_FEEDS_TYPES] PRIMARY KEY CLUSTERED 
(
	[FEED_TYPE_ID] ASC
)
)
END
GO
