
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[EVENTS_OBJS_REFS]') AND type in (N'U'))
BEGIN
CREATE TABLE [EVENTS_OBJS_REFS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[EVENT_ID] [int] NULL,
	[OBJ_TYPE] [varchar](8) NULL,
	[OBJ_ID] [int] NULL,
 CONSTRAINT [PK__EVENTS_O__3214EC278D5ADDE9] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[EVENTS_OBJS_REFS]') AND name = N'IX_EVENTS_OBJS_REFS')
CREATE UNIQUE NONCLUSTERED INDEX [IX_EVENTS_OBJS_REFS] ON [EVENTS_OBJS_REFS]
(
	[EVENT_ID] ASC,
	[OBJ_TYPE] ASC,
	[OBJ_ID] ASC
)
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_EVENTS_OBJS_REFS_EVENTS_EVENT_ID]') AND parent_object_id = OBJECT_ID(N'[EVENTS_OBJS_REFS]'))
ALTER TABLE [EVENTS_OBJS_REFS]  WITH CHECK ADD  CONSTRAINT [FK_EVENTS_OBJS_REFS_EVENTS_EVENT_ID] FOREIGN KEY([EVENT_ID])
REFERENCES [EVENTS] ([EVENT_ID])
ON DELETE CASCADE
GO

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_EVENTS_OBJS_REFS_EVENTS_EVENT_ID]') AND parent_object_id = OBJECT_ID(N'[EVENTS_OBJS_REFS]'))
ALTER TABLE [EVENTS_OBJS_REFS] CHECK CONSTRAINT [FK_EVENTS_OBJS_REFS_EVENTS_EVENT_ID]
GO
