USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[EVENTS_FEEDS]') AND type in (N'U'))
BEGIN
CREATE TABLE [EVENTS_FEEDS](
	[FEED_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](30) NULL,
	[DESCRIPTION] [nvarchar](512) NULL,
	[IS_DELETED] [bit] NOT NULL,
 CONSTRAINT [PK_EVENTS_FEEDS] PRIMARY KEY CLUSTERED 
(
	[FEED_ID] ASC
)
)
END
GO
