
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[EVENTS_CACHE]') AND type in (N'U'))
BEGIN
CREATE TABLE [EVENTS_CACHE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [int] NULL,
	[FEED_ID] [int] NULL,
	[TASK_ID] [int] NULL,
	[TALK_ID] [int] NULL,
	[OWNER_NAME] [varchar](80) NULL,
	[OWNER_MOL_ID] [int] NULL,
	[OWNER_MOL_NAME] [varchar](50) NULL,
	[HREF] [varchar](250) NULL,
	[LAST_MESSAGE] [varchar](150) NULL,
	[LAST_DATE] [datetime] NULL,
	[COUNT_UNREADS] [int] NULL,
	[ADD_DATE] [datetime] DEFAULT getdate(),
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO


IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[EVENTS_CACHE]') AND name = N'IX_USER')
CREATE NONCLUSTERED INDEX [IX_USER] ON [EVENTS_CACHE]
(
	[USER_ID] ASC
)
GO
