
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[EVENTS_MOLS]') AND type in (N'U'))
BEGIN
CREATE TABLE [EVENTS_MOLS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[EVENT_ID] [int] NULL,
	[MOL_ID] [int] NULL,
	[READ_DATE] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[EVENTS_MOLS]') AND name = N'IX_EVENTS_MOLS')
CREATE UNIQUE NONCLUSTERED INDEX [IX_EVENTS_MOLS] ON [EVENTS_MOLS]
(
	[EVENT_ID] ASC,
	[MOL_ID] ASC
)
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_EVENTS_MOLS_EVENTS_EVENT_ID]') AND parent_object_id = OBJECT_ID(N'[EVENTS_MOLS]'))
ALTER TABLE [EVENTS_MOLS]  WITH CHECK ADD  CONSTRAINT [FK_EVENTS_MOLS_EVENTS_EVENT_ID] FOREIGN KEY([EVENT_ID])
REFERENCES [EVENTS] ([EVENT_ID])
ON DELETE CASCADE
GO

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_EVENTS_MOLS_EVENTS_EVENT_ID]') AND parent_object_id = OBJECT_ID(N'[EVENTS_MOLS]'))
ALTER TABLE [EVENTS_MOLS] CHECK CONSTRAINT [FK_EVENTS_MOLS_EVENTS_EVENT_ID]
GO
