USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[FILE_TYPES_ICONS]') AND type in (N'U'))
BEGIN
CREATE TABLE [FILE_TYPES_ICONS](
	[EXTENSION] [varchar](16) NOT NULL,
	[NAME] [varchar](128) NOT NULL,
	[IMG_URL] [varchar](256) NULL,
 CONSTRAINT [PK_FILE_TYPES_ICONS] PRIMARY KEY CLUSTERED 
(
	[EXTENSION] ASC
)
)
END
GO
