USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[FIN_GOALS_STATUSES]') AND type in (N'U'))
BEGIN
CREATE TABLE [FIN_GOALS_STATUSES](
	[STATUS_ID] [int] NOT NULL,
	[NAME] [nvarchar](30) NULL,
 CONSTRAINT [PK_FIN_GOALS_STATUSES] PRIMARY KEY CLUSTERED 
(
	[STATUS_ID] ASC
)
)
END
GO
