
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[FIN_GOALS_SUMS_DETAILS]') AND type in (N'U'))
BEGIN
CREATE TABLE [FIN_GOALS_SUMS_DETAILS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FIN_GOAL_ID] [int] NULL,
	[MOL_ID] [int] NULL,
	[FIN_GOAL_SUM_ID] [int] NULL,
	[BUDGET_ID] [int] NULL,
	[ARTICLE_ID] [int] NULL,
	[PARENT_ID] [int] NULL,
	[NODE_ID] [int] NULL,
	[NAME] [nvarchar](250) NULL,
	[HAS_CHILDS] [bit] NULL DEFAULT ((0)),
	[NODE] [hierarchyid] NULL,
	[LEVEL_ID] [int] NULL,
	[VALUE_START] [decimal](18, 2) NULL,
	[VALUE_IN] [decimal](18, 2) NULL,
	[VALUE_OUT] [decimal](18, 2) NULL,
	[VALUE_END] [decimal](18, 2) NULL,
	[VALUE_END_EDIT] [decimal](18, 2) NULL,
	[GOAL_ACCOUNT_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[FIN_GOALS_SUMS_DETAILS]') AND name = N'IX_FIN_GOALS_SUMS_DETAILS')
CREATE NONCLUSTERED INDEX [IX_FIN_GOALS_SUMS_DETAILS] ON [FIN_GOALS_SUMS_DETAILS]
(
	[MOL_ID] ASC,
	[ID] ASC
)
GO
