
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[FIN_GOALS_META_EXCLUDES]') AND type in (N'U'))
BEGIN
CREATE TABLE [FIN_GOALS_META_EXCLUDES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FOLDER_ID] [int] NULL,
	[BUDGET_ID] [int] NULL,
	[MOL_ID] [int] NULL,
	[ADD_DATE] [datetime] DEFAULT getdate(),
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[FIN_GOALS_META_EXCLUDES]') AND name = N'IX_FIN_GOALS_META_EXCLUDES')
CREATE UNIQUE NONCLUSTERED INDEX [IX_FIN_GOALS_META_EXCLUDES] ON [FIN_GOALS_META_EXCLUDES]
(
	[FOLDER_ID] ASC,
	[BUDGET_ID] ASC
)
GO
