
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[FIN_GOALS_DETAILS]') AND type in (N'U'))
BEGIN
CREATE TABLE [FIN_GOALS_DETAILS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FIN_GOAL_ID] [int] NULL,
	[MOL_ID] [int] NULL,
	[FOLDER_ID] [int] NULL,
	[ARTICLE_ID] [int] NULL,
	[BUDGET_ID] [int] NULL,
	[VALUE_START] [decimal](18, 2) NULL,
	[VALUE_IN] [decimal](18, 2) NULL,
	[VALUE_OUT] [decimal](18, 2) NULL,
	[VALUE_END] [decimal](18, 2) NULL,
	[VALUE_END_EDIT] [decimal](18, 2) NULL,
	[GOAL_ACCOUNT_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[FIN_GOALS_DETAILS]') AND name = N'IX_FIN_GOALS_DETAILS1')
CREATE NONCLUSTERED INDEX [IX_FIN_GOALS_DETAILS1] ON [FIN_GOALS_DETAILS]
(
	[FIN_GOAL_ID] ASC,
	[MOL_ID] ASC,
	[ARTICLE_ID] ASC
)
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[FIN_GOALS_DETAILS]') AND name = N'IX_FIN_GOALS_DETAILS2')
CREATE NONCLUSTERED INDEX [IX_FIN_GOALS_DETAILS2] ON [FIN_GOALS_DETAILS]
(
	[FIN_GOAL_ID] ASC,
	[MOL_ID] ASC,
	[BUDGET_ID] ASC
)
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[FIN_GOALS_DETAILS]') AND name = N'IX_FIN_GOALS_DETAILS3')
CREATE NONCLUSTERED INDEX [IX_FIN_GOALS_DETAILS3] ON [FIN_GOALS_DETAILS]
(
	[FIN_GOAL_ID] ASC,
	[MOL_ID] ASC,
	[GOAL_ACCOUNT_ID] ASC
)
GO
