
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[FINDOCS_AZ_BUDGETS]') AND type in (N'U'))
BEGIN
CREATE TABLE [FINDOCS_AZ_BUDGETS](
	[MOL_ID] [int] NULL,
	[BUDGET_ID] [int] NULL,
	[ADD_DATE] [datetime] DEFAULT getdate(),
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[FINDOCS_AZ_BUDGETS]') AND name = N'IX_FINDOCS_AZ_BUDGETS')
CREATE UNIQUE NONCLUSTERED INDEX [IX_FINDOCS_AZ_BUDGETS] ON [FINDOCS_AZ_BUDGETS]
(
	[MOL_ID] ASC,
	[BUDGET_ID] ASC
)
GO
