
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[FINDOCS_ACCOUNTS_AZ]') AND type in (N'U'))
BEGIN
CREATE TABLE [FINDOCS_ACCOUNTS_AZ](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MOL_ID] [int] NOT NULL,
	[ACCOUNT_ID] [int] NOT NULL,
	[D_FROM] [datetime] NULL,
	[D_TO] [datetime] NULL,
	[VALUE_START] [decimal](18, 2) NULL,
	[VALUE_IN] [decimal](18, 2) NULL,
	[VALUE_OUT] [decimal](18, 2) NULL,
	[VALUE_END] [decimal](18, 2) NULL,
	[ADD_DATE] [datetime] NOT NULL DEFAULT (getdate()),
 CONSTRAINT [PK_FINDOCS_ACCOUNTS_AZ] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO
