
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[FINDOCS_CACHE]') AND type in (N'U'))
BEGIN
CREATE TABLE [FINDOCS_CACHE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MOL_ID] [int] NULL,
	[FINDOC_ID] [int] NULL,
	[D_ADD] [datetime] default GETDATE()
 CONSTRAINT [PK_FINDOCS_CACHE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[FINDOCS_CACHE]') AND name = N'IX_FINDOCS_CACHE')
CREATE NONCLUSTERED INDEX [IX_FINDOCS_CACHE] ON [FINDOCS_CACHE]
(
	[MOL_ID] ASC,
	[FINDOC_ID] ASC
)
GO
