
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[FINDOCS_LOG]') AND type in (N'U'))
BEGIN
CREATE TABLE [FINDOCS_LOG](
	[TRAN_ID] [uniqueidentifier] NULL,
	[TRAN_CALLER] [varchar](max) NULL,
	[TRAN_ACTION] [char](1) NULL,
	[TRAN_USER_ID] [int] NULL,
	[ID] [int] NULL,
	[FINDOC_ID] [int] NULL,
	[GOAL_ACCOUNT_ID] [int] NULL,
	[BUDGET_ID] [int] NULL,
	[ARTICLE_ID] [int] NULL,
	[VALUE_CCY] [decimal](18, 2) NULL,
	[VALUE_RUR] [decimal](18, 2) NULL,
	[NOTE] [varchar](max) NULL,
	[ADD_DATE] [datetime] DEFAULT getdate(),
	[ADD_MOL_ID] [int] NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_MOL_ID] [int] NULL,
	[TRAN_DATE] [datetime] DEFAULT getdate()
)
END
GO


IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[FINDOCS_LOG]') AND name = N'IX_FINDOCS_LOG1')
CREATE NONCLUSTERED INDEX [IX_FINDOCS_LOG1] ON [FINDOCS_LOG]
(
	[FINDOC_ID] ASC
)
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[FINDOCS_LOG]') AND name = N'IX_FINDOCS_LOG2')
CREATE NONCLUSTERED INDEX [IX_FINDOCS_LOG2] ON [FINDOCS_LOG]
(
	[FINDOC_ID] ASC,
	[ID] ASC
)
GO
