
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[FINDOCS_WBS]') AND type in (N'U'))
BEGIN
CREATE TABLE [FINDOCS_WBS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FINDOC_ID] [int] NULL,
	[BUDGET_ID] [int] NULL,
	[ARTICLE_ID] [int] NULL,
	[TASK_ID] [int] NULL,
	[VALUE_BIND] [decimal](18, 2) NULL,
	[ADD_DATE] [datetime] DEFAULT getdate(),
	[MOL_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[FINDOCS_WBS]') AND name = N'IX_FINDOCS_WBS')
CREATE UNIQUE NONCLUSTERED INDEX [IX_FINDOCS_WBS] ON [FINDOCS_WBS]
(
	[FINDOC_ID] ASC,
	[BUDGET_ID] ASC,
	[ARTICLE_ID] ASC,
	[TASK_ID] ASC
)
GO
