
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[FINDOCS_UPLOAD_DETAILS_MAP]') AND type in (N'U'))
BEGIN
CREATE TABLE [FINDOCS_UPLOAD_DETAILS_MAP](
	[FROM_ARTICLE_NAME] [varchar](250) NULL,
	[TO_ARTICLE_NAME] [varchar](250) NULL
)
END
GO

