
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[FINDOCS#]') AND type in (N'U'))
BEGIN
CREATE TABLE [FINDOCS#](
	[FINDOC_ID] [int] NOT NULL,
	[DETAIL_ID] [int] NOT NULL DEFAULT ((0)),
	[SUBJECT_ID] [int] NULL,
	[ACCOUNT_ID] [int] NULL,
	[D_DOC] [datetime] NULL,
	[AGENT_ID] [int] NULL,
	[GOAL_ACCOUNT_ID] [int] NULL,
	[BUDGET_ID] [int] NULL,
	[ARTICLE_ID] [int] NULL,
	[VALUE_CCY] [decimal](18, 2) NULL,
	[VALUE_RUR] [decimal](18, 2) NULL,
	[FIXED_DETAILS] [bit] NULL,
	[D_REPLICATED] [datetime] NULL,
 CONSTRAINT [PK_FINDOCS#] PRIMARY KEY CLUSTERED 
(
	[FINDOC_ID] ASC,
	[DETAIL_ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[FINDOCS#]') AND name = N'IX_FINDOCS#1')
CREATE NONCLUSTERED INDEX [IX_FINDOCS#1] ON [FINDOCS#]
(
	[BUDGET_ID] ASC
)
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[FINDOCS#]') AND name = N'IX_FINDOCS#2')
CREATE NONCLUSTERED INDEX [IX_FINDOCS#2] ON [FINDOCS#]
(
	[ARTICLE_ID] ASC
)
GO
