
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[FINDOCS#TODO]') AND type in (N'U'))
BEGIN
CREATE TABLE [FINDOCS#TODO](
	[ROW_ID] [int] IDENTITY(1,1) NOT NULL,
	[FINDOC_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ROW_ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[FINDOCS#TODO]') AND name = N'IX_FINDOC_ID')
CREATE NONCLUSTERED INDEX [IX_FINDOC_ID] ON [FINDOCS#TODO]
(
	[FINDOC_ID] ASC
)
GO
