
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[FINDOCS_UPLOAD_DETAILS1]') AND type in (N'U'))
BEGIN
CREATE TABLE [FINDOCS_UPLOAD_DETAILS1](
	[PayId] [int] IDENTITY(1,1) NOT NULL,
	[findoc_id] [int] NULL,
	[DocDate] [datetime] NULL,
	[Number] [varchar](100) NULL,
	[ValueCcy] [decimal](18, 2) NULL,
	[Duplicated] [bit] NULL DEFAULT ((0)),
	[CreatedUserId] [int] NULL,
	[CreatedDate] [datetime] NULL DEFAULT (getdate()),
	[ProcessedUserId] [int] NULL,
	[ProcessedDate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[PayId] ASC
)
)
END
GO


IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[FINDOCS_UPLOAD_DETAILS1]') AND name = N'IX_FINDOCS_UPLOAD_DETAILS1')
CREATE NONCLUSTERED INDEX [IX_FINDOCS_UPLOAD_DETAILS1] ON [FINDOCS_UPLOAD_DETAILS1]
(
	[ValueCcy] ASC,
	[DocDate] ASC
)
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[FINDOCS_UPLOAD_DETAILS1]') AND name = N'IX_FINDOCS_UPLOAD_DETAILS1_FINDOC')
CREATE NONCLUSTERED INDEX [IX_FINDOCS_UPLOAD_DETAILS1_FINDOC] ON [FINDOCS_UPLOAD_DETAILS1]
(
	[findoc_id] ASC
)
GO
