USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[MFR_ITEMS_TYPES]') AND type in (N'U'))
BEGIN
CREATE TABLE [MFR_ITEMS_TYPES](
	[GROUP_ID] [int] NULL,
	[TYPE_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](150) NULL,
	[NOTE] [varchar](max) NULL,
	[IS_DELETED] [bit] NOT NULL,
	[ADD_DATE] [datetime] NULL,
	[ADD_MOL_ID] [int] NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_MOL_ID] [int] NULL,
	[SORT_ID] [int] NULL,
 CONSTRAINT [PK_MFR_ITEMS_TYPES] PRIMARY KEY CLUSTERED 
(
	[TYPE_ID] ASC
)
)
END
GO
