USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[MFR_EQUIPMENTS_STATUSES]') AND type in (N'U'))
BEGIN
CREATE TABLE [MFR_EQUIPMENTS_STATUSES](
	[STATUS_ID] [int] NOT NULL,
	[NAME] [varchar](50) NULL,
 CONSTRAINT [PK_MFR_EQUIPMENTS_STATUSES] PRIMARY KEY CLUSTERED 
(
	[STATUS_ID] ASC
)
)
END
GO
