USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[MFR_EXT_PROBABILITIES]') AND type in (N'U'))
BEGIN
CREATE TABLE [MFR_EXT_PROBABILITIES](
	[PROBABILITY_ID] [int] NOT NULL,
	[NAME] [varchar](50) NULL,
	[STYLE] [varchar](max) NULL,
 CONSTRAINT [PK_MFR_EXT_PROBABILITIES] PRIMARY KEY CLUSTERED 
(
	[PROBABILITY_ID] ASC
)
)
END
GO
