USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[MFR_R_PROVIDES_XSLICES]') AND type in (N'U'))
BEGIN
CREATE TABLE [MFR_R_PROVIDES_XSLICES](
	[XSLICE] [varchar](8) NOT NULL,
	[NAME] [varchar](30) NULL,
	[NOTE] [varchar](max) NULL,
 CONSTRAINT [PK_MFR_R_PROVIDES_XSLICES] PRIMARY KEY CLUSTERED 
(
	[XSLICE] ASC
)
)
END
GO
