USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[MFR_ITEMS_STATUSES]') AND type in (N'U'))
BEGIN
CREATE TABLE [MFR_ITEMS_STATUSES](
	[STATUS_ID] [int] NOT NULL,
	[NAME] [varchar](50) NULL,
	[NAME_QUEUE] [varchar](50) NULL,
	[SHORT_NAME] [varchar](10) NULL,
	[CSS] [varchar](50) NULL,
	[STYLE] [varchar](50) NULL,
	[GROUP_NAME] [varchar](50) NULL,
	[SORT_ID] [int] NULL,
 CONSTRAINT [PK_MFR_ITEMS_STATUSES] PRIMARY KEY CLUSTERED 
(
	[STATUS_ID] ASC
)
)
END
GO
