USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[MFR_SDOCS_PRIORITIES]') AND type in (N'U'))
BEGIN
CREATE TABLE [MFR_SDOCS_PRIORITIES](
	[PRIORITY_ID] [int] NOT NULL,
	[PRIORITY_MAX] [int] NULL,
	[NAME] [varchar](50) NULL,
	[CSS] [varchar](250) NULL,
 CONSTRAINT [PK_MFR_SDOCS_PRIORITIES] PRIMARY KEY CLUSTERED 
(
	[PRIORITY_ID] ASC
)
)
END
GO
