USE CISP_SHARED
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[MOLS_FRIENDS]') AND type in (N'U'))
BEGIN
CREATE TABLE [MOLS_FRIENDS](
	[MOL_ID] [int] NOT NULL,
	[FRIEND_ID] [int] NOT NULL,
	[D_ADD] [datetime] NOT NULL CONSTRAINT [DF_MOLS_FRIENDS_D_ADD]  DEFAULT (getdate()),
	[IS_ALERT_BIRTHDAY] [bit] NOT NULL CONSTRAINT [DF_MOLS_FRIENDS_IS_MAIL_BIRTHDAY]  DEFAULT ((0)),
    CONSTRAINT [PK_MOLS_FRIENDS] PRIMARY KEY CLUSTERED 
    (
        [MOL_ID] ASC,
        [FRIEND_ID] ASC
    )
)
END
GO
