USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[OBJS_FOLDERS_STATUSES]') AND type in (N'U'))
BEGIN
CREATE TABLE [OBJS_FOLDERS_STATUSES](
	[STATUS_ID] [int] NOT NULL,
	[NAME] [varchar](32) NULL,
 CONSTRAINT [PK_OBJS_FOLDERS_STATUSES] PRIMARY KEY CLUSTERED 
(
	[STATUS_ID] ASC
)
)
END
GO
