USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[OBJS_META_REFS]') AND type in (N'U'))
BEGIN
CREATE TABLE [OBJS_META_REFS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FROM_OBJ_TYPE] [varchar](8) NULL,
	[TO_OBJ_TYPE] [varchar](30) NULL,
	[TO_OBJ_NAME] [varchar](100) NULL,
	[URL] [varchar](max) NULL,
 CONSTRAINT [PK_OBJS_META_REFS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO
