USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[OPTIONS_LISTS]') AND type in (N'U'))
BEGIN
CREATE TABLE [OPTIONS_LISTS](
	[L_GROUP] [varchar](32) NOT NULL,
	[ID] [varchar](32) NOT NULL,
	[NAME] [varchar](100) NOT NULL,
	[NOTE] [varchar](max) NULL,
	[ROW_ID] [int] IDENTITY(1,1) NOT NULL,
	[SHORT_NAME] [varchar](16) NULL,
 CONSTRAINT [PK_OPTIONS_LISTS] PRIMARY KEY CLUSTERED 
(
	[ROW_ID] ASC
)
)
END
GO
