
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PAYORDERS_PARTIALS_DETAILS]') AND type in (N'U'))
BEGIN
CREATE TABLE [PAYORDERS_PARTIALS_DETAILS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PAYORDER_ID] [int] NULL,
	[FOLDER_ID] [int] NULL,
	[BUDGET_ID] [int] NULL,
	[ARTICLE_ID] [int] NULL,
	[VALUE_CCY] [decimal](18, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[PAYORDERS_PARTIALS_DETAILS]') AND name = N'IX_PAYORDERS_PARTIALS_DETAILS')
CREATE NONCLUSTERED INDEX [IX_PAYORDERS_PARTIALS_DETAILS] ON [PAYORDERS_PARTIALS_DETAILS]
(
	[PAYORDER_ID] ASC,
	[FOLDER_ID] ASC,
	[BUDGET_ID] ASC,
	[ARTICLE_ID] ASC
)
GO
