
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PAYORDERS_PARTIALS]') AND type in (N'U'))
BEGIN
CREATE TABLE [PAYORDERS_PARTIALS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PAYORDER_ID] [int] NULL,
	[D_DOC] [datetime] NULL,
	[VALUE_CCY] [decimal](18, 2) NULL,
	[NOTE] [varchar](250) NULL,
	[FOLDER_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO


IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[PAYORDERS_PARTIALS]') AND name = N'IX_PAYORDERS_PARTIALS')
CREATE UNIQUE NONCLUSTERED INDEX [IX_PAYORDERS_PARTIALS] ON [PAYORDERS_PARTIALS]
(
	[PAYORDER_ID] ASC,
	[D_DOC] ASC
)
GO
