USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PERIODICITY]') AND type in (N'U'))
BEGIN
CREATE TABLE [PERIODICITY](
	[PERIODICITY_ID] [int] NOT NULL,
	[NAME] [varchar](50) NULL,
 CONSTRAINT [PK_PERIODICITY] PRIMARY KEY CLUSTERED 
(
	[PERIODICITY_ID] ASC
)
)
END
GO
