USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PLAN_PAYS_STATUSES]') AND type in (N'U'))
BEGIN
CREATE TABLE [PLAN_PAYS_STATUSES](
	[STATUS_ID] [int] NOT NULL,
	[NAME] [varchar](20) NULL,
 CONSTRAINT [PK_PLAN_PAYS_STATUSES] PRIMARY KEY CLUSTERED 
(
	[STATUS_ID] ASC
)
)
END
GO
