USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PLISTS_STATUSES]') AND type in (N'U'))
BEGIN
CREATE TABLE [PLISTS_STATUSES](
	[STATUS_ID] [int] NOT NULL,
	[NAME] [nvarchar](30) NULL,
	[IS_DELETED] [bit] NOT NULL,
 CONSTRAINT [PK_PLISTS_STATUSES] PRIMARY KEY CLUSTERED 
(
	[STATUS_ID] ASC
)
)
END
GO
