
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRODMETA_TEMPLATES]') AND type in (N'U'))
BEGIN
CREATE TABLE [PRODMETA_TEMPLATES](
	[CLASS_ID] [int] NULL,
	[TEMPLATE_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](250) NULL,
	[CONTENT] [nvarchar](max) NULL,
	[IS_DELETED] [bit] NOT NULL DEFAULT ((0)),
PRIMARY KEY CLUSTERED 
(
	[TEMPLATE_ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[PRODMETA_TEMPLATES]') AND name = N'IX_PRODMETA_TEMPLATES')
CREATE UNIQUE NONCLUSTERED INDEX [IX_PRODMETA_TEMPLATES] ON [PRODMETA_TEMPLATES]
(
	[CLASS_ID] ASC,
	[NAME] ASC
)
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_PRODMETA_TEMPLATES_CLASS_ID]') AND parent_object_id = OBJECT_ID(N'[PRODMETA_TEMPLATES]'))
ALTER TABLE [PRODMETA_TEMPLATES]  WITH CHECK ADD  CONSTRAINT [FK_PRODMETA_TEMPLATES_CLASS_ID] FOREIGN KEY([CLASS_ID])
REFERENCES [PRODMETA_CLASSES] ([CLASS_ID])
ON DELETE CASCADE
GO

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_PRODMETA_TEMPLATES_CLASS_ID]') AND parent_object_id = OBJECT_ID(N'[PRODMETA_TEMPLATES]'))
ALTER TABLE [PRODMETA_TEMPLATES] CHECK CONSTRAINT [FK_PRODMETA_TEMPLATES_CLASS_ID]
GO
