
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRODMETA_CLASSES_ATTRS]') AND type in (N'U'))
BEGIN
CREATE TABLE [PRODMETA_CLASSES_ATTRS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CLASS_ID] [int] NULL,
	[ATTR_ID] [int] NULL,
	[IS_COLUMN] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO


IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[PRODMETA_CLASSES_ATTRS]') AND name = N'IX_PRODMETA_CLASSES_ATTRS')
CREATE UNIQUE NONCLUSTERED INDEX [IX_PRODMETA_CLASSES_ATTRS] ON [PRODMETA_CLASSES_ATTRS]
(
	[CLASS_ID] ASC,
	[ATTR_ID] ASC
)
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_PRODMETA_CLASSES_ATTRS_CLASS_ID]') AND parent_object_id = OBJECT_ID(N'[PRODMETA_CLASSES_ATTRS]'))
ALTER TABLE [PRODMETA_CLASSES_ATTRS]  WITH CHECK ADD  CONSTRAINT [FK_PRODMETA_CLASSES_ATTRS_CLASS_ID] FOREIGN KEY([CLASS_ID])
REFERENCES [PRODMETA_CLASSES] ([CLASS_ID])
ON DELETE CASCADE
GO

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_PRODMETA_CLASSES_ATTRS_CLASS_ID]') AND parent_object_id = OBJECT_ID(N'[PRODMETA_CLASSES_ATTRS]'))
ALTER TABLE [PRODMETA_CLASSES_ATTRS] CHECK CONSTRAINT [FK_PRODMETA_CLASSES_ATTRS_CLASS_ID]
GO
