
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRODUCTS_GROUPS]') AND type in (N'U'))
BEGIN
CREATE TABLE [PRODUCTS_GROUPS](
	[GROUP_ID] [int] IDENTITY(1,1) NOT NULL,
	[LEVEL_ID] [int] NULL,
	[NAME] [varchar](255) NOT NULL,
	[SORT_ID] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[GROUP_ID] ASC
)
)
END
GO

