
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_TIMESHEETS_MOLS]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_TIMESHEETS_MOLS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PROJECT_ID] [int] NOT NULL,
	[MOL_ID] [int] NOT NULL,
	[SUM_PLAN_H] [decimal](18, 2) NULL,
	[SUM_FACT_H] [decimal](18, 2) NULL,
	[SUM_ALLEXCEPT_PLAN_H] [decimal](18, 2) NULL,
	[SUM_ALLEXCEPT_FACT_H] [decimal](18, 2) NULL,
	[IS_DELETED] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO
