
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_CONTRACTS]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_CONTRACTS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PROJECT_ID] [int] NULL,
	[SUBJECT_ID] [int] NULL,
	[DOGOVOR_NUMBER] [varchar](50) NULL,
	[DOGOVOR_DATE] [datetime] NULL,
	[SPEC_NUMBER] [varchar](50) NULL,
	[SPEC_DATE] [datetime] NULL,
	[CCY_ID] [char](3) NULL,
	[VALUE_CCY] [decimal](18, 2) NULL,
	[CUSTOMER_ID] [int] NULL,
	[VENDOR_ID] [int] NULL,
	[PRINCIPAL_ID] [int] NULL,
	[PRINCIPAL_COMMISSION_ID] [int] NULL,
	[PRINCIPAL_SPEC_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO

