
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_REPS_BUDGETS]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_REPS_BUDGETS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[REP_ID] [int] NULL,
	[PROJECT_ID] [int] NULL,
	[BUDGET_ID] [int] NULL,
	[TASK_ID] [int] NULL,
	[ARTICLE_ID] [int] NULL,
	[D_DOC] [datetime] NULL,
	[INOUT] [int] NULL,
	[PLAN_BDS] [decimal](18, 2) NULL,
	[NOTE] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO


IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[PROJECTS_REPS_BUDGETS]') AND name = N'IX_PROJECTS_REPS_BUDGETS')
CREATE NONCLUSTERED INDEX [IX_PROJECTS_REPS_BUDGETS] ON [PROJECTS_REPS_BUDGETS]
(
	[PROJECT_ID] ASC,
	[BUDGET_ID] ASC,
	[TASK_ID] ASC,
	[ARTICLE_ID] ASC
)
GO
