
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_RISKS_RACI]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_RISKS_RACI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[RISK_ID] [int] NULL,
	[MOL_ID] [int] NULL,
	[RACI] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO

