
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_TASKS_RESOURCES]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_TASKS_RESOURCES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TASK_ID] [int] NOT NULL,
	[RESOURCE_ID] [int] NOT NULL,
	[QUANTITY] [decimal](18, 3) NOT NULL DEFAULT ((0)),
	[NOTE] [varchar](max) NULL,
	[MOL_ID] [int] NOT NULL,
	[ADD_DATE] [datetime] NOT NULL DEFAULT (getdate()),
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO


IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[PROJECTS_TASKS_RESOURCES]') AND name = N'IX_PROJECTS_TASKS_RESOURCES')
CREATE UNIQUE NONCLUSTERED INDEX [IX_PROJECTS_TASKS_RESOURCES] ON [PROJECTS_TASKS_RESOURCES]
(
	[TASK_ID] ASC,
	[RESOURCE_ID] ASC
)
GO
