
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_RESOURCES_AZ_TASKS_DAYS]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_RESOURCES_AZ_TASKS_DAYS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TREE_ID] [int] NOT NULL,
	[ROW_ID] [int] NOT NULL,
	[RESOURCE_ID] [int] NOT NULL,
	[D_DOC] [datetime] NOT NULL,
	[OUTPUT_Q] [decimal](18, 3) NULL,
	[OVERLIMIT_Q] [decimal](18, 3) NULL,
	[HAS_CHILDS] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[PROJECTS_RESOURCES_AZ_TASKS_DAYS]') AND name = N'IX_PROJECTS_RESOURCES_AZ_TASKS_DAYS')
CREATE NONCLUSTERED INDEX [IX_PROJECTS_RESOURCES_AZ_TASKS_DAYS] ON [PROJECTS_RESOURCES_AZ_TASKS_DAYS]
(
	[TREE_ID] ASC,
	[RESOURCE_ID] ASC,
	[D_DOC] ASC
)
GO
