
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_REPS_RESOURCES]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_REPS_RESOURCES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[REP_ID] [int] NOT NULL,
	[TASK_ID] [int] NOT NULL,
	[RESOURCE_ID] [int] NOT NULL,
	[Q_INPUT] [decimal](18, 3) NULL,
	[Q_CURRENT] [decimal](18, 3) NULL,
	[Q_OUTPUT] [decimal](18, 3) NULL,
	[Q_END] [decimal](18, 3) NULL,
	[NOTE] [varchar](max) NULL,
 CONSTRAINT [PK_PROJECTS_REPS_RESOURCES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO


IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[PROJECTS_REPS_RESOURCES]') AND name = N'IX_PROJECTS_REPS')
CREATE UNIQUE NONCLUSTERED INDEX [IX_PROJECTS_REPS] ON [PROJECTS_REPS_RESOURCES]
(
	[REP_ID] ASC,
	[TASK_ID] ASC,
	[RESOURCE_ID] ASC
)
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_PROJECTS_REPS_RESOURCES_REPS_REP_ID]') AND parent_object_id = OBJECT_ID(N'[PROJECTS_REPS_RESOURCES]'))
ALTER TABLE [PROJECTS_REPS_RESOURCES]  WITH CHECK ADD  CONSTRAINT [FK_PROJECTS_REPS_RESOURCES_REPS_REP_ID] FOREIGN KEY([REP_ID])
REFERENCES [PROJECTS_REPS] ([REP_ID])
ON DELETE CASCADE
GO

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_PROJECTS_REPS_RESOURCES_REPS_REP_ID]') AND parent_object_id = OBJECT_ID(N'[PROJECTS_REPS_RESOURCES]'))
ALTER TABLE [PROJECTS_REPS_RESOURCES] CHECK CONSTRAINT [FK_PROJECTS_REPS_RESOURCES_REPS_REP_ID]
GO
