USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_RISKS_ACTIONS]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_RISKS_ACTIONS](
	[RISK_ID] [int] NOT NULL,
	[ACTION_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](max) NULL,
	[ACTIONS] [varchar](max) NULL,
	[D_RESPONSE] [varchar](max) NULL,
	[IS_DELETED] [bit] NOT NULL,
	[ADD_DATE] [datetime] NULL,
 CONSTRAINT [PK_PROJECTS_RISKS_ACTIONS] PRIMARY KEY CLUSTERED 
(
	[ACTION_ID] ASC
)
)
END
GO
