USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_RISKS_CATEGORIES]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_RISKS_CATEGORIES](
	[CATEGORY_ID] [int] NOT NULL,
	[NAME] [varchar](20) NULL,
 CONSTRAINT [PK_PROJECTS_RISKS_CATEGORIES] PRIMARY KEY CLUSTERED 
(
	[CATEGORY_ID] ASC
)
)
END
GO
