
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_FAVORITES]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_FAVORITES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MOL_ID] [int] NOT NULL,
	[PROJECT_ID] [int] NOT NULL,
	[ADD_DATE] [datetime] DEFAULT getdate(),
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[PROJECTS_FAVORITES]') AND name = N'IX_PROJECTS_FAVORITES')
CREATE UNIQUE NONCLUSTERED INDEX [IX_PROJECTS_FAVORITES] ON [PROJECTS_FAVORITES]
(
	[MOL_ID] ASC,
	[PROJECT_ID] ASC
)
GO
