
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_BUYS_SHEETS_DETAILS]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_BUYS_SHEETS_DETAILS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PROJECT_ID] [int] NULL,
	[PRODUCT_ID] [int] NULL,
	[IN_DOC_ID] [int] NULL,
	[IN_D_DOC] [datetime] NULL,
	[OUT_DOC_ID] [int] NULL,
	[OUT_D_DOC] [datetime] NULL,
	[QUANTITY] [float] NULL,
	[Q_BUY] [float] NULL,
	[Q_STOCK] [float] NULL,
	[Q_MFS] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[PROJECTS_BUYS_SHEETS_DETAILS]') AND name = N'IX_PROJECTS_BUYS_SHEETS_DETAILS')
CREATE NONCLUSTERED INDEX [IX_PROJECTS_BUYS_SHEETS_DETAILS] ON [PROJECTS_BUYS_SHEETS_DETAILS]
(
	[PROJECT_ID] ASC,
	[PRODUCT_ID] ASC
)
GO
