USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_PRIORITIES]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_PRIORITIES](
	[PRIORITY_ID] [int] NOT NULL,
	[NAME] [varchar](32) NULL,
	[CSS_CLASS] [varchar](32) NULL,
 CONSTRAINT [PK_PROJECTS_PRIORITIES] PRIMARY KEY CLUSTERED 
(
	[PRIORITY_ID] ASC
)
)
END
GO
