
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_REPS_BUDGETS_PAYS]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_REPS_BUDGETS_PAYS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[REP_ID] [int] NULL,
	[ARTICLE_ID] [int] NULL,
	[FINDOC_ID] [int] NULL,
	[PLAN_INOUT] [int] NULL,
	[FACT_INOUT] [int] NULL,
	[FACT_BDS] [decimal](18, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO
