USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_STATUSES]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_STATUSES](
	[STATUS_ID] [int] NOT NULL,
	[NAME] [varchar](50) NOT NULL,
	[IMG_URL] [varchar](50) NULL,
	[NOTE] [varchar](max) NULL,
	[IS_DEAL] [bit] NULL,
 CONSTRAINT [PK_PROJECTS_STATUSES] PRIMARY KEY CLUSTERED 
(
	[STATUS_ID] ASC
)
)
END
GO
