
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_RESOURCES_AZ_TRACKING]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_RESOURCES_AZ_TRACKING](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MOL_ID] [int] NOT NULL,
	[TREE_ID] [int] NULL,
	[TASK_ID] [int] NULL,
	[D_FROM] [datetime] NULL,
	[D_AFTER] [datetime] NULL,
	[REBATE_SHIFT] [int] NULL,
	[IS_MANUAL] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[PROJECTS_RESOURCES_AZ_TRACKING]') AND name = N'IX_PROJECTS_RESOURCES_AZ_TRACKING')
CREATE UNIQUE NONCLUSTERED INDEX [IX_PROJECTS_RESOURCES_AZ_TRACKING] ON [PROJECTS_RESOURCES_AZ_TRACKING]
(
	[TREE_ID] ASC,
	[TASK_ID] ASC
)
GO
