
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_TIMESHEETS_EVENTS]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_TIMESHEETS_EVENTS](
	[EVENT_ID] [int] NULL,
	[NAME] [varchar](50) NULL
)
END
GO

