
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_PORTFOLIOS]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_PORTFOLIOS](
	[PORTFOLIO_ID] [int] IDENTITY(1,1) NOT NULL,
	[STATUS_ID] [int] NULL DEFAULT ((1)),
	[NAME] [varchar](50) NULL,
	[NOTE] [varchar](max) NULL,
	[MOL_ID] [int] NULL,
	[D_ADD] [datetime] NULL DEFAULT (getdate()),
	[IS_DELETED] [bit] NOT NULL DEFAULT ((0)),
PRIMARY KEY CLUSTERED 
(
	[PORTFOLIO_ID] ASC
)
)
END
GO

