
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_RESOURCES_LIMITS]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_RESOURCES_LIMITS](
	[LIMIT_ID] [int] IDENTITY(1,1) NOT NULL,
	[TREE_ID] [int] NOT NULL,
	[RESOURCE_ID] [int] NOT NULL,
	[LIMIT_Q] [decimal](18, 3) NULL,
	[ADD_DATE] [datetime] DEFAULT getdate(),
	[MOL_ID] [int] NULL,
	[PRICE] [decimal](18, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[LIMIT_ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[PROJECTS_RESOURCES_LIMITS]') AND name = N'IX_PROJECTS_RESOURCES_LIMITS')
CREATE UNIQUE NONCLUSTERED INDEX [IX_PROJECTS_RESOURCES_LIMITS] ON [PROJECTS_RESOURCES_LIMITS]
(
	[TREE_ID] ASC,
	[RESOURCE_ID] ASC
)
GO
