USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_GROUPS]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_GROUPS](
	[GROUP_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](64) NULL,
	[DESCRIPTION] [varchar](max) NULL,
	[ADD_DATE] [datetime] NULL,
	[IS_SYSTEM] [bit] NOT NULL,
 CONSTRAINT [PK_PROJECTS_GROUPS] PRIMARY KEY CLUSTERED 
(
	[GROUP_ID] ASC
)
)
END
GO
