
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_TIMESHEETS]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_TIMESHEETS](
	[TIMESHEET_ID] [int] IDENTITY(1,1) NOT NULL,
	[MOL_ID] [int] NOT NULL,
	[PROJECT_ID] [int] NOT NULL,
	[TASK_ID] [int] NOT NULL,
	[TALK_ID] [int] NULL,
	[NAME] [varchar](250) NULL,
	[SUM_PLAN_H] [decimal](18, 2) NULL,
	[SUM_FACT_H] [decimal](18, 2) NULL,
	[IS_DELETED] [bit] NULL,
	[ADD_DATE] [datetime] DEFAULT getdate(),
	[CALC_DATE] [datetime] NULL,
	[IS_CLOSED] [bit] NULL,
	[D_DEADLINE] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[TIMESHEET_ID] ASC
)
)
END
GO

