
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_DEALS_COSTS]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_DEALS_COSTS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DEAL_ID] [int] NOT NULL,
	[TASK_ID] [int] NOT NULL,
	[DATE_LAG] [int] NOT NULL DEFAULT ((0)),
	[ARTICLE_ID] [int] NOT NULL,
	[NDS_RATIO] [decimal](18, 2) NOT NULL DEFAULT ((0.18)),
	[VALUE_BDR] [decimal](18, 2) NULL,
	[VALUE_BDS] [decimal](18, 2) NULL,
	[VALUE_NDS] [decimal](18, 2) NULL,
	[NOTE] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO

