
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_RESOURCES_AZ_TASKS]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_RESOURCES_AZ_TASKS](
	[ROW_ID] [int] IDENTITY(1,1) NOT NULL,
	[TREE_ID] [int] NOT NULL,
	[TASK_ID] [int] NOT NULL,
	[RESOURCE_ID] [int] NOT NULL,
	[OUTPUT_Q] [decimal](18, 3) NULL,
	[REBATE_SHIFT] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ROW_ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[PROJECTS_RESOURCES_AZ_TASKS]') AND name = N'IX_PROJECTS_RESOURCES_AZ_TASKS')
CREATE NONCLUSTERED INDEX [IX_PROJECTS_RESOURCES_AZ_TASKS] ON [PROJECTS_RESOURCES_AZ_TASKS]
(
	[TREE_ID] ASC,
	[TASK_ID] ASC,
	[RESOURCE_ID] ASC
)
GO
