
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_PORTFOLIOS_DETAILS]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_PORTFOLIOS_DETAILS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PORTFOLIO_ID] [int] NULL,
	[PROJECT_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO
