USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_DURATIONS]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_DURATIONS](
	[DURATION_ID] [int] NOT NULL,
	[NAME] [varchar](12) NULL,
	[FACTOR] [float] NULL,
	[FACTOR24] [float] NULL,
 CONSTRAINT [PK_PROJECTS_DURATIONS] PRIMARY KEY CLUSTERED 
(
	[DURATION_ID] ASC
)
)
END
GO
