USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_RESOURCES_TYPES]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_RESOURCES_TYPES](
	[TYPE_ID] [int] NOT NULL,
	[NAME] [varchar](30) NULL,
	[NOTE] [varchar](max) NULL,
 CONSTRAINT [PK_PROJECTS_RESOURCES_TYPES] PRIMARY KEY CLUSTERED 
(
	[TYPE_ID] ASC
)
)
END
GO
