
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_REPS_RISKS]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_REPS_RISKS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[REP_ID] [int] NULL,
	[NAME] [varchar](max) NULL,
	[REASON] [varchar](max) NULL,
	[INFLUENCE] [varchar](max) NULL,
	[RESOLVE] [varchar](max) NULL,
	[ADD_DATE] [datetime] DEFAULT getdate(),
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_PROJECTS_REPS_RISKS_PROJECTS_REPS]') AND parent_object_id = OBJECT_ID(N'[PROJECTS_REPS_RISKS]'))
ALTER TABLE [PROJECTS_REPS_RISKS]  WITH CHECK ADD  CONSTRAINT [FK_PROJECTS_REPS_RISKS_PROJECTS_REPS] FOREIGN KEY([REP_ID])
REFERENCES [PROJECTS_REPS] ([REP_ID])
ON DELETE CASCADE
GO

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_PROJECTS_REPS_RISKS_PROJECTS_REPS]') AND parent_object_id = OBJECT_ID(N'[PROJECTS_REPS_RISKS]'))
ALTER TABLE [PROJECTS_REPS_RISKS] CHECK CONSTRAINT [FK_PROJECTS_REPS_RISKS_PROJECTS_REPS]
GO
