
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_MOLS_SECTIONS_META]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_MOLS_SECTIONS_META](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PROJECT_ID] [int] NULL,
	[TREE_ID] [int] NULL,
	[SECTION_ID] [int] NULL,
	[A_READ] [tinyint] NOT NULL DEFAULT ((1)),
	[A_UPDATE] [tinyint] NOT NULL DEFAULT ((0)),
	[ADD_DATE] [datetime] NOT NULL DEFAULT (getdate()),
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[PROJECTS_MOLS_SECTIONS_META]') AND name = N'IX_PROJECTS_MOLS_SECTIONS')
CREATE UNIQUE NONCLUSTERED INDEX [IX_PROJECTS_MOLS_SECTIONS] ON [PROJECTS_MOLS_SECTIONS_META]
(
	[PROJECT_ID] ASC,
	[TREE_ID] ASC,
	[SECTION_ID] ASC
)
GO
