
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_RESOURCES_AZ_LIMITS]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_RESOURCES_AZ_LIMITS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TREE_ID] [int] NOT NULL,
	[RESOURCE_ID] [int] NOT NULL,
	[D_DOC] [datetime] NOT NULL,
	[QUANTITY] [decimal](18, 3) NULL DEFAULT ((0)),
	[LIMIT_Q] [decimal](18, 3) NULL DEFAULT ((0)),
	[OVERLIMIT_Q]  AS (case when [QUANTITY]>[LIMIT_Q] then [QUANTITY]-[LIMIT_Q]  end),
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[PROJECTS_RESOURCES_AZ_LIMITS]') AND name = N'IX_PROJECTS_RESOURCES_AZ_LIMITS')
CREATE UNIQUE NONCLUSTERED INDEX [IX_PROJECTS_RESOURCES_AZ_LIMITS] ON [PROJECTS_RESOURCES_AZ_LIMITS]
(
	[TREE_ID] ASC,
	[RESOURCE_ID] ASC,
	[D_DOC] ASC
)
GO
