
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_EXTERNALS]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_EXTERNALS](
	[EXP_PROJECT_ID] [int] NOT NULL,
	[NAME] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[EXP_PROJECT_ID] ASC
)
)
END
GO

