USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_RESOURCES_AGGREGATIONS]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_RESOURCES_AGGREGATIONS](
	[AGGREGATION_ID] [int] NOT NULL,
	[NAME] [varchar](100) NOT NULL,
	[DESCRIPTION] [varchar](max) NULL,
 CONSTRAINT [PK_PROJECTS_RESOURCES_AGGREGATIONS] PRIMARY KEY CLUSTERED 
(
	[AGGREGATION_ID] ASC
)
)
END
GO
