
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_RESOURCES_CHARTS]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_RESOURCES_CHARTS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[RESOURCE_ID] [int] NOT NULL,
	[PROJECT_ID] [int] NOT NULL,
	[TASK_ID] [int] NOT NULL,
	[TASK_RESOURCE_ID] [int] NOT NULL,
	[QUANTITY] [decimal](18, 3) NOT NULL DEFAULT ((0)),
	[D_DOC] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[PROJECTS_RESOURCES_CHARTS]') AND name = N'IX_PROJECTS_RESOURCES_CHARTS')
CREATE UNIQUE NONCLUSTERED INDEX [IX_PROJECTS_RESOURCES_CHARTS] ON [PROJECTS_RESOURCES_CHARTS]
(
	[RESOURCE_ID] ASC,
	[TASK_ID] ASC,
	[D_DOC] ASC
)
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[PROJECTS_RESOURCES_CHARTS]') AND name = N'IX_PROJECTS_RESOURCES_CHARTS2')
CREATE NONCLUSTERED INDEX [IX_PROJECTS_RESOURCES_CHARTS2] ON [PROJECTS_RESOURCES_CHARTS]
(
	[PROJECT_ID] ASC,
	[RESOURCE_ID] ASC,
	[TASK_ID] ASC
)
GO
