
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PROJECTS_TASKS_LINKS]') AND type in (N'U'))
BEGIN
CREATE TABLE [PROJECTS_TASKS_LINKS](
	[PROJECT_ID] [int] NOT NULL,
	[LINK_ID] [int] IDENTITY(1,1) NOT NULL,
	[SOURCE_ID] [int] NULL,
	[TARGET_ID] [int] NULL,
	[TYPE_ID] [int] NULL DEFAULT ((0)),
PRIMARY KEY CLUSTERED 
(
	[LINK_ID] ASC
)
)
END
GO
