USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SDOCS_PROVIDES_GROUPS]') AND type in (N'U'))
BEGIN
CREATE TABLE [SDOCS_PROVIDES_GROUPS](
	[GROUP_ID] [int] NOT NULL,
	[NAME] [varchar](50) NULL,
 CONSTRAINT [PK_SDOCS_PROVIDES_GROUPS] PRIMARY KEY CLUSTERED 
(
	[GROUP_ID] ASC
)
)
END
GO
