USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SDOCS_STATUSES]') AND type in (N'U'))
BEGIN
CREATE TABLE [SDOCS_STATUSES](
	[STATUS_ID] [int] NOT NULL,
	[NAME] [varchar](50) NULL,
 CONSTRAINT [PK_SDOCS_STATUSES] PRIMARY KEY CLUSTERED 
(
	[STATUS_ID] ASC
)
)
END
GO
