USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SDOCS_TYPES]') AND type in (N'U'))
BEGIN
CREATE TABLE [SDOCS_TYPES](
	[TYPE_ID] [int] NOT NULL,
	[DIRECTION] [int] NULL,
	[NAME] [varchar](50) NULL,
	[NOTE] [varchar](max) NULL,
 CONSTRAINT [PK_SDOCS_TYPES] PRIMARY KEY CLUSTERED 
(
	[TYPE_ID] ASC
)
)
END
GO
