USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SDOCS_MFR_CONTENTS_CANCELREASONS]') AND type in (N'U'))
BEGIN
CREATE TABLE [SDOCS_MFR_CONTENTS_CANCELREASONS](
	[CANCEL_REASON_ID] [int] NOT NULL,
	[NAME] [varchar](50) NULL,
 CONSTRAINT [PK_SDOCS_MFR_CONTENTS_CANCELREASONS] PRIMARY KEY CLUSTERED 
(
	[CANCEL_REASON_ID] ASC
)
)
END
GO
