USE CISP_SHARED
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SUBJECTS]') AND type in (N'U'))
BEGIN
CREATE TABLE [SUBJECTS](
	[SUBJECT_ID] [int] NOT NULL,
	[NAME] [varchar](255) NOT NULL,
	[IS_DELETED] [bit] NOT NULL DEFAULT ((0)),
	[PRED_ID] [int] NULL,
	[IS_VENDOR] [bit] NULL,
	[SHORT_NAME] [varchar](20) NULL,
	[DBNAME] [varchar](32) NULL,
    PRIMARY KEY CLUSTERED 
    (
        [SUBJECT_ID] ASC
    )
)
END
GO
