USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[TASKS_STATUSES]') AND type in (N'U'))
BEGIN
CREATE TABLE [TASKS_STATUSES](
	[STATUS_ID] [int] NOT NULL,
	[NAME] [varchar](32) NULL,
	[CSS_CLASS] [varchar](50) NULL,
	[IS_WORKING] [bit] NULL,
	[CSS_BADGE] [varchar](64) NULL,
 CONSTRAINT [PK_TASKS_STATUSES] PRIMARY KEY CLUSTERED 
(
	[STATUS_ID] ASC
)
)
END
GO
