USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[TASKS_PRIORITIES]') AND type in (N'U'))
BEGIN
CREATE TABLE [TASKS_PRIORITIES](
	[PRIORITY_ID] [int] NOT NULL,
	[NAME] [varchar](30) NULL,
	[CSS_CLASS] [varchar](50) NULL,
 CONSTRAINT [PK_TASKS_PRIORITIES] PRIMARY KEY CLUSTERED 
(
	[PRIORITY_ID] ASC
)
)
END
GO
