
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[TASKS_HREFS]') AND type in (N'U'))
BEGIN
CREATE TABLE [TASKS_HREFS](
	[REF_ID] [int] IDENTITY(1,1) NOT NULL,
	[TASK_ID] [int] NULL,
	[HIST_ID] [int] NULL,
	[NAME] [varchar](64) NULL,
	[HREF] [varchar](max) NULL,
	[ADD_DATE] [datetime] DEFAULT getdate(),
	[ADD_MOL_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[REF_ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[TASKS_HREFS]') AND name = N'IX_TASKS_HREFS')
CREATE UNIQUE NONCLUSTERED INDEX [IX_TASKS_HREFS] ON [TASKS_HREFS]
(
	[TASK_ID] ASC,
	[HIST_ID] ASC,
	[NAME] ASC
)
GO
