USE CISP_SHARED
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[TASKS_TYPES]') AND type in (N'U'))
BEGIN
CREATE TABLE [TASKS_TYPES](
	[TYPE_ID] [int] NOT NULL,
	[NAME] [varchar](32) NULL,
 CONSTRAINT [PK_TASKS_TYPES] PRIMARY KEY CLUSTERED 
(
	[TYPE_ID] ASC
)
)
END
GO
