
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[TASKS_HISTS_MOLS]') AND type in (N'U'))
BEGIN
CREATE TABLE [TASKS_HISTS_MOLS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[HIST_ID] [int] NOT NULL,
	[MOL_ID] [int] NOT NULL,
	[D_RESPOND] [datetime] NULL,
	[D_READ] [datetime] NULL,
	[IS_DELETED] [bit] NULL,
	[IS_FAVORITE] [bit] NOT NULL DEFAULT ((0)),
 CONSTRAINT [PK_TASKS_HISTS_MOLS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[TASKS_HISTS_MOLS]') AND name = N'IX_TASKS_HISTS_MOLS')
CREATE NONCLUSTERED INDEX [IX_TASKS_HISTS_MOLS] ON [TASKS_HISTS_MOLS]
(
	[HIST_ID] ASC,
	[MOL_ID] ASC
)
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_TASKS_HISTS_MOLS_HIST_ID]') AND parent_object_id = OBJECT_ID(N'[TASKS_HISTS_MOLS]'))
ALTER TABLE [TASKS_HISTS_MOLS]  WITH CHECK ADD  CONSTRAINT [FK_TASKS_HISTS_MOLS_HIST_ID] FOREIGN KEY([HIST_ID])
REFERENCES [TASKS_HISTS] ([HIST_ID])
ON DELETE CASCADE
GO

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_TASKS_HISTS_MOLS_HIST_ID]') AND parent_object_id = OBJECT_ID(N'[TASKS_HISTS_MOLS]'))
ALTER TABLE [TASKS_HISTS_MOLS] CHECK CONSTRAINT [FK_TASKS_HISTS_MOLS_HIST_ID]
GO
