
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[TASKS_TAGS]') AND type in (N'U'))
BEGIN
CREATE TABLE [TASKS_TAGS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TASK_ID] [int] NOT NULL,
	[MOL_ID] [int] NOT NULL,
	[TAGS] [varchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO

