
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[TASKS_THEMES_PRINTS]') AND type in (N'U'))
BEGIN
CREATE TABLE [TASKS_THEMES_PRINTS](
	[THEME_ID] [int] NULL,
	[PRINT_ID] [int] IDENTITY(1,1) NOT NULL,
	[TITLE] [nvarchar](255) NULL,
	[PROC_NAME] [varchar](64) NULL,
	[HTML] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[PRINT_ID] ASC
)
)
END
GO

