
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[TASKS_THEMES_MOLS]') AND type in (N'U'))
BEGIN
CREATE TABLE [TASKS_THEMES_MOLS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[THEME_ID] [int] NOT NULL,
	[MOL_ID] [int] NOT NULL,
	[ADD_DATE] [datetime] DEFAULT getdate(),
	[ROLE_ID] [int] NOT NULL DEFAULT ((20)),
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[TASKS_THEMES_MOLS]') AND name = N'IX_TASKS_THEMES_MOLS')
CREATE UNIQUE NONCLUSTERED INDEX [IX_TASKS_THEMES_MOLS] ON [TASKS_THEMES_MOLS]
(
	[THEME_ID] ASC,
	[ROLE_ID] ASC,
	[MOL_ID] ASC
)
GO
