
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[TASKS_COUNTERS]') AND type in (N'U'))
BEGIN
CREATE TABLE [TASKS_COUNTERS](
	[NODE_ID] [int] IDENTITY(1,1) NOT NULL,
	[PARENT_ID] [int] NULL,
	[NAME] [varchar](50) NULL,
	[HAS_CHILDS] [bit] NULL DEFAULT ((0)),
	[MOL_ID] [int] NULL,
	[COUNTS] [int] NULL,
	[COUNTS_OVER] [int] NULL,
	[COUNTS_RISKS] [int] NULL,
	[ADD_DATE] [datetime] DEFAULT getdate(),
PRIMARY KEY CLUSTERED 
(
	[NODE_ID] ASC
)
)
END
GO

