
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[TASKS_THEMES_ATTRS]') AND type in (N'U'))
BEGIN
CREATE TABLE [TASKS_THEMES_ATTRS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[THEME_ID] [int] NULL,
	[ATTR_NAME] [varchar](50) NULL,
	[ATTR_TYPE] [varchar](20) NULL,
	[NOTE] [varchar](max) NULL,
	[IS_REQUIRED] [bit] NULL,
	[IS_READONLY] [bit] NULL,
	[IS_HIDDEN] [bit] NULL,
	[ATTR_META] [varchar](max) NULL,
	[PARENT_ID] [int] NULL,
	[IS_REQUIRED_ONCREATE] [bit] NULL,
	[SORT_ID] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[TASKS_THEMES_ATTRS]') AND name = N'IX_TASKS_THEMES_ATTRS')
CREATE UNIQUE NONCLUSTERED INDEX [IX_TASKS_THEMES_ATTRS] ON [TASKS_THEMES_ATTRS]
(
	[THEME_ID] ASC,
	[ATTR_NAME] ASC
)
GO
