
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[TASKS_DOCS_REFS]') AND type in (N'U'))
BEGIN
CREATE TABLE [TASKS_DOCS_REFS](
	[REF_ID] [int] IDENTITY(1,1) NOT NULL,
	[TASK_ID] [int] NULL,
	[HIST_ID] [int] NULL,
	[DOCUMENT_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[REF_ID] ASC
)
)
END
GO
