
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[TASKS_THEMES_MOLS_NODES]') AND type in (N'U'))
BEGIN
CREATE TABLE [TASKS_THEMES_MOLS_NODES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[THEME_ID] [int] NOT NULL,
	[MOL_NODE_ID] [int] NOT NULL,
	[ADD_DATE] [datetime] DEFAULT getdate(),
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO
