
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[TASKS_COUNTERS_DETAILS]') AND type in (N'U'))
BEGIN
CREATE TABLE [TASKS_COUNTERS_DETAILS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[COUNTER_ID] [int] NULL,
	[MOL_ID] [int] NULL,
	[TASK_ID] [int] NULL,
	[IS_OVER] [int] NULL,
	[COUNTS_RISKS] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
END
GO
