services:

# Infrastructure
  cisp-proxy:
    image: ruselprom/cisp-proxy
    container_name: cisp-proxy
    volumes: 
      - /mnt/cispfiles:/cispfiles:rw
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports: 
      - 5672:5672
      - 15672:15672

# Web UI
  cisp-root-ui:
    image: ruselprom/cisp-root-ui
    container_name: cisp-root-ui
    restart: always

  cisp-finance-ui:
    image: ruselprom/cisp-finance-ui
    container_name: cisp-finance-ui
    restart: always

  cisp-mfrs-ui:
    image: ruselprom/cisp-mfrs-ui
    container_name: cisp-mfrs-ui
    restart: always

  cisp-products-ui:
    image: ruselprom/cisp-products-ui
    container_name: cisp-products-ui
    restart: always

# API
  cisp-root:
    image: ruselprom/cisp-root
    container_name: cisp-root
    volumes: 
      - ./appsettings.json:/app/appsettings.json
      - /mnt/cispfiles:/cispfiles:rw
    restart: always
      
  cisp-mfrs:
    image: ruselprom/cisp-mfrs
    container_name: cisp-mfrs
    volumes: 
      - ./appsettings.json:/app/appsettings.json
      - /mnt/cispfiles:/cispfiles:rw
    restart: always
      
  cisp-finance:
    image: ruselprom/cisp-finance
    container_name: cisp-finance
    volumes: 
      - ./appsettings.json:/app/appsettings.json
      - /mnt/cispfiles:/cispfiles:rw
    restart: always

  cisp-products:
    image: ruselprom/cisp-products
    container_name: cisp-products
    volumes: 
      - ./appsettings.json:/app/appsettings.json
      - /mnt/cispfiles:/cispfiles:rw
    restart: always

# Workers
  cisp-qbroker:
    image: ruselprom/cisp-qbroker
    container_name: cisp-qbroker
    volumes: 
      - ./appsettings.json:/app/appsettings.json
    depends_on:
      - rabbitmq
    restart: always

  cisp-mail:
    image: ruselprom/cisp-mail
    container_name: cisp-mail
    volumes: 
      - ./appsettings.json:/app/appsettings.json
    depends_on:
      - rabbitmq
    restart: always

  cisp-exchange:
    image: ruselprom/cisp-exchange
    container_name: cisp-exchange
    volumes: 
      - ./appsettings.json:/app/appsettings.json
      - /home/projects/Cisp/exchange.prod.json:/app/exchange.json
    depends_on:
      - rabbitmq
    restart: always