worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;
    gzip on;

    map $http_connection $connection_upgrade {
        "~*Upgrade" $http_connection;
        default keep-alive;
    }

    proxy_headers_hash_max_size 1024;
    proxy_headers_hash_bucket_size 128;

    proxy_set_header HOST $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_cache_bypass $http_upgrade;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    server {
        listen 80;
        server_name localhost;

        location /signalr {
            proxy_pass http://cisp-root;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $server_name;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_cache_bypass $http_upgrade;
        }

        location /css/ {
            root html;
        }

        location /api/ {
            proxy_pass http://cisp-root/api/;
            proxy_redirect off;
        }

        location /finance/api/ {
            proxy_pass http://cisp-finance/api/;
            proxy_redirect off;
        }

        location /finance/FinanceReports/ {
            proxy_pass http://cisp-finance/FinanceReports/;
            proxy_redirect off;
            break;
        }        

        location /finance/ {
            proxy_pass http://cisp-finance/;
            proxy_redirect off;
        }

        location /mfrs/api/ {
            proxy_pass http://cisp-mfrs/api/;
            proxy_redirect off;
        }

        location /mfrs/MfrsReports/ {
            proxy_pass http://cisp-mfrs/MfrsReports/;
            proxy_redirect off;
            break;
        }        

        location /mfrs/ {
            proxy_pass http://cisp-mfrs/;
            proxy_redirect off;
        }

        location /products/api/ {
            proxy_pass http://cisp-products/api/;
            proxy_redirect off;
        }

        location /products/ {
            proxy_pass http://cisp-products/;
            proxy_redirect off;
        }

        location /files/ {
            alias /cispfiles/;
        }

        location /Files/ {
            alias /cispfiles/;
        }

        location /docs/ {
            proxy_pass http://192.168.112.91:9101/;
            proxy_redirect off;
        }

        location / {
            proxy_pass http://cisp-root/;
            proxy_redirect off;
        }

        error_page 500 502 503 504 /50x.html;

        location = /50x.html {
            root html;
        }
    }
}
