IF EXISTS (SELECT * FROM SYS.SYNONYMS WHERE NAME = N'MOLS') DROP SYNONYM MOLS
GO
CREATE SYNONYM MOLS FOR CISP_SHARED..MOLS
GO

IF EXISTS (SELECT * FROM SYS.SYNONYMS WHERE NAME = N'MOLCARDS') DROP SYNONYM MOLCARDS
GO
CREATE SYNONYM MOLCARDS FOR CISP_SHARED..MOLS
GO

IF EXISTS (SELECT * FROM SYS.SYNONYMS WHERE NAME = N'MOLCARDS_SHORTS') DROP SYNONYM MOLCARDS_SHORTS
GO
CREATE SYNONYM MOLCARDS_SHORTS FOR CISP_SHARED..MOLS
GO
