IF OBJECT_ID('V_MFR_R_PROVIDES_DIFFS') IS NOT NULL DROP VIEW V_MFR_R_PROVIDES_DIFFS
IF OBJECT_ID('V_MFR_PRINT_MATERIALS_DIFFS') IS NOT NULL DROP VIEW V_MFR_PRINT_MATERIALS_DIFFS
GO

-- SELECT TOP 10 * FROM V_MFR_PRINT_MATERIALS_DIFFS
CREATE VIEW V_MFR_PRINT_MATERIALS_DIFFS
AS
SELECT 
    MFR_DOC_ID,
    
    ST.STATUS_ID,
    STATUS_NAME = ST.NAME,
    STATUS_CSS = ST.CSS,
    STATUS_STYLE = ST.STYLE,
    
    ITEM_NAME = PI.NAME,

    DIFF_TYPE = SIGN(D_DIFF),
    D_TO_PLAN,
    D_DIFF,

	X.UNIT_NAME,
    Q = ISNULL(Q_JOB, Q_MFR),
    V = ISNULL(V_JOB, V_MFR)
FROM (
	SELECT
        MFR_DOC_ID, STATUS_ID, ITEM_ID, UNIT_NAME,
        D_TO_PLAN = MIN(D_MFR_TO),
        D_DIFF = CASE WHEN MAX(D_DIFF) < 0 THEN MIN(D_DIFF) ELSE MAX(D_DIFF) END,
        Q_MFR = SUM(Q_MFR),
        V_MFR = SUM(V_MFR),
        Q_JOB = SUM(Q_JOB),
        V_JOB = SUM(V_JOB)
    FROM (
        SELECT
            MFR_DOC_ID, STATUS_ID, ITEM_ID, UNIT_NAME, D_MFR_TO,
            D_DIFF = DATEDIFF(D, D_MFR_TO, ISNULL(D_JOB, DBO.TODAY())),
            Q_MFR,
            V_MFR = Q_MFR * PRICE,
            Q_JOB = ISNULL(Q_LZK, Q_JOB),
            V_JOB = ISNULL(Q_LZK, Q_JOB) * PRICE
        FROM MFR_R_PROVIDES R
        WHERE D_MFR_TO != ISNULL(D_JOB, DBO.TODAY())
        ) X
    GROUP BY MFR_DOC_ID, STATUS_ID, ITEM_ID, UNIT_NAME
    ) X
    JOIN PRODUCTS PI ON PI.PRODUCT_ID = X.ITEM_ID
    JOIN MFR_ITEMS_STATUSES ST ON ST.STATUS_ID = X.STATUS_ID

GO
