IF DBO.COLUMN_ID('SDOCS_PRODUCTS.HAS_DETAILS') IS NULL
    ALTER TABLE SDOCS_PRODUCTS ADD HAS_DETAILS BIT
    
IF OBJECT_ID('SDOCS_PRODUCTS_DETAILS') IS NULL
BEGIN
	-- DROP TABLE SDOCS_PRODUCTS_DETAILS
	CREATE TABLE SDOCS_PRODUCTS_DETAILS(
		ID INT IDENTITY PRIMARY KEY NONCLUSTERED,
		DOC_ID INT,
        DETAIL_ID INT,
        QUANTITY FLOAT,
        MFR_NUMBER VARCHAR(100),
        NOTE VARCHAR(MAX),
		--	
		ADD_DATE DATETIME DEFAULT GETDATE(),
		ADD_MOL_ID INT,
		UPDATE_DATE DATETIME,
		UPDATE_MOL_ID INT
	)
	CREATE CLUSTERED INDEX IX_SDOCS_PRODUCTS_DETAILS ON SDOCS_PRODUCTS_DETAILS(DOC_ID, DETAIL_ID)
END
GO
