IF DB_NAME() = 'CISP'
BEGIN
    DELETE FROM OBJS_TYPES WHERE TYPE = 'BUYORDER'
    INSERT INTO OBJS_TYPES(TYPE, FOLDER_KEYWORD, NAME, URL, BASE_TABLE, BASE_TABLE_COLUMN)
    VALUES('BUYORDER', 'BUYORDER', 'Заявки на закупку', '/finance/lgs/buyorders', 'SUPPLY_BUYORDERS', 'DOC_ID')
END
GO
