IF DB_NAME() = 'CISP'
    IF DBO.COLUMN_ID('DOCUMENTS.FOLDER_ID') IS NULL
        ALTER TABLE DOCUMENTS ADD FOLDER_ID INT
GO

IF DB_NAME() = 'CISP'
    UPDATE OBJS_TYPES SET FOLDER_KEYWORD = 'SWAP' WHERE [TYPE] = 'SWP'
GO
