IF DB_NAME() = 'CISP'
    UPDATE TASKS_ATTRS SET ATTR_ID = JT.ID
    FROM (
        SELECT TTA.ID, TTA.ATTR_NAME, T.TASK_ID
        FROM TASKS_THEMES_ATTRS TTA
            JOIN TASKS T ON T.THEME_ID = TTA.THEME_ID
        ) JT
        WHERE TASKS_ATTRS.TASK_ID = JT.TASK_ID AND TASKS_ATTRS.ATTR_NAME = JT.ATTR_NAME 
GO

IF DB_NAME() = 'CISP'
BEGIN
    IF DBO.COLUMN_ID('TASKS_ATTRS.SORT_ID') IS NULL
        ALTER TABLE TASKS_ATTRS ADD SORT_ID FLOAT NULL

    IF DBO.COLUMN_ID('TASKS_THEMES_ATTRS.SORT_ID') IS NULL
        ALTER TABLE TASKS_THEMES_ATTRS ADD SORT_ID FLOAT NULL
END
GO

IF DB_NAME() = 'CISP'
    UPDATE TASKS_THEMES_ATTRS SET SORT_ID = ID
GO