-- dbcontext: CISP
IF CISP_SHARED.DBO.COLUMN_ID('PAYORDERS.PAYMENT_TYPE') IS NULL
    ALTER TABLE CISP_SHARED.DBO.PAYORDERS ADD PAYMENT_TYPE NVARCHAR(250)
GO

IF DB_NAME() = 'CISP'
    UPDATE P SET NUMBER = LEFT(NOTE, 100)
    FROM PAYORDERS P
    WHERE EXISTS(SELECT 1 FROM PAYORDERS_MATERIALS WHERE PAYORDER_ID = P.PAYORDER_ID)
        AND NUMBER IS NULL
GO
