IF OBJECT_ID('MFR_PRODUCTS_GRP2') IS NOT NULL DROP VIEW MFR_PRODUCTS_GRP2
GO
-- SELECT * FROM MFR_ATTRS WHERE GROUP_KEY = 'MFRGRP'
CREATE VIEW MFR_PRODUCTS_GRP2
AS

SELECT 
	PA.PRODUCT_ID,
	A.ATTR_ID,
	A.NAME
FROM PRODUCTS_ATTRS PA
	JOIN MFR_ATTRS A ON A.ATTR_ID = PA.ATTR_ID AND A.GROUP_KEY = 'MfrGrp'

GO