IF OBJECT_ID('MFR_PRODUCTS_GRP1') IS NOT NULL DROP VIEW MFR_PRODUCTS_GRP1
GO
-- SELECT * FROM MFR_ATTRS WHERE GROUP_KEY = 'MFRTOTALGRP'
CREATE VIEW MFR_PRODUCTS_GRP1
AS
SELECT 
	PA.PRODUCT_ID,
	A.ATTR_ID,
	A.NAME
FROM 
	-- avoid duplicates
	(
		SELECT PRODUCT_ID, ATTR_ID = MAX(PA.ATTR_ID)
		FROM PRODUCTS_ATTRS PA
			JOIN MFR_ATTRS A ON A.ATTR_ID = PA.ATTR_ID AND A.GROUP_KEY = 'MFRTOTALGRP'
		GROUP BY PRODUCT_ID
	) PA 
	JOIN MFR_ATTRS A ON A.ATTR_ID = PA.ATTR_ID
GO
