IF OBJECT_ID('V_MFR_WK_SHEETS_JOBS') IS NOT NULL DROP VIEW V_MFR_WK_SHEETS_JOBS
GO
-- SELECT TOP 100 * FROM V_MFR_WK_SHEETS_JOBS
CREATE VIEW V_MFR_WK_SHEETS_JOBS
AS
SELECT 
	*
FROM (	
	SELECT 
		W.WK_SHEET_ID,
		W.D_DOC,
		W.NUMBER,
		PLACE_NAME = CONCAT(PL.NAME, ' ', PL.NOTE),
		M.MOL_ID,
		MOL_SURNAME = M.SURNAME,
		MOL_NAME1 = M.NAME1,
		MOL_NAME2 = M.NAME2,
		MOL_TAB_NUMBER = M.TAB_NUMBER,
		X.OPER_DATE,
		X.PLAN_JOB_ID,
		JOB_STATUS_NAME = JS.NAME,
		JOB_LAGDAYS = DATEDIFF(D, X.D_DOC, X.OPER_DATE),
		X.MFR_NUMBER,
		PRODUCT_NAME = P1.NAME,
		ITEM_NAME = ISNULL(P2.NAME, '[деталь не указана]'),
		X.OPER_NUMBER,
		OPER_NAME = CONCAT('#', X.OPER_NUMBER, '-', X.OPER_NAME),
		RESOURCE_NAME = RS.NAME,
		X.OPER_NOTE,
		X.PLAN_Q,
		X.FACT_Q,
		X.PLAN_DAY_Q,
		X.FACT_DAY_Q,				
		NORM_HOURS = X.NORM_DURATION_WK,
		PLAN_HOURS = X.PLAN_DURATION_WK,
		FACT_HOURS = X.DURATION_WK,
		X.WK_SHIFT,
		X.PLAN_SALARY,
		X.FACT_SALARY
	FROM MFR_WK_SHEETS_JOBS X WITH(NOLOCK)
		JOIN MFR_WK_SHEETS W WITH(NOLOCK) ON W.WK_SHEET_ID = X.WK_SHEET_ID
			JOIN MFR_PLACES PL WITH(NOLOCK) ON PL.PLACE_ID = W.PLACE_ID
		JOIN MOLS M WITH(NOLOCK) ON M.MOL_ID = X.MOL_ID
		LEFT JOIN MFR_JOBS_STATUSES JS ON JS.STATUS_ID = X.SALARY_STATUS_ID
		LEFT JOIN PRODUCTS P1 WITH(NOLOCK) ON P1.PRODUCT_ID = X.PRODUCT_ID
		LEFT JOIN PRODUCTS P2 WITH(NOLOCK) ON P2.PRODUCT_ID = NULLIF(X.ITEM_ID,0)
		LEFT JOIN MFR_RESOURCES RS WITH(NOLOCK) ON RS.RESOURCE_ID = X.RESOURCE_ID	
	WHERE X.D_DOC = W.D_DOC
	) W
GO
