IF OBJECT_ID('V_SDOCS_R_STOCKS_TURNS_PRODUCTS') IS NOT NULL DROP VIEW V_SDOCS_R_STOCKS_TURNS_PRODUCTS
GO
-- SELECT * FROM V_SDOCS_R_STOCKS_TURNS_PRODUCTS
CREATE VIEW V_SDOCS_R_STOCKS_TURNS_PRODUCTS
AS

SELECT 
    X.MOL_ID,
    X.PRODUCT_ID, 
    PRODUCT_NAME = P.NAME, 
    UNIT_NAME = U.NAME, 
    Q_START, Q_INPUT, Q_OUTPUT, Q_END
FROM (
    SELECT 
        MOL_ID, PRODUCT_ID, UNIT_ID,
        Q_START = SUM(Q_START),
        Q_INPUT = SUM(Q_INPUT),
        Q_OUTPUT = SUM(Q_OUTPUT),
        Q_END = SUM(Q_END)
    FROM SDOCS_R_STOCKS_TURNS
    GROUP BY MOL_ID, PRODUCT_ID, UNIT_ID
    ) X
    JOIN PRODUCTS P ON P.PRODUCT_ID = X.PRODUCT_ID
    JOIN PRODUCTS_UNITS U ON U.UNIT_ID = X.UNIT_ID
WHERE 
    ABS(Q_END) > 1E-4 OR Q_INPUT > 1E-4 OR Q_OUTPUT > 1E-4

GO
