IF DBO.COLUMN_ID('SDOCS_PRODUCTS_DETAILS.STOCK_ADDR_ID') IS NULL
    ALTER TABLE SDOCS_PRODUCTS_DETAILS ADD STOCK_ADDR_ID INT
GO

IF OBJECT_ID('SDOCS_STOCKS') IS NULL
BEGIN
    CREATE TABLE SDOCS_STOCKS(
        STOCK_ID INT IDENTITY PRIMARY KEY,
        NAME VARCHAR(150),
        SUBJECT_ID INT,
        EXT_SUBJECT_ID INT,
		NOTE VARCHAR(MAX),
		IS_DELETED BIT NOT NULL DEFAULT(0),
		ADD_DATE DATETIME DEFAULT GETDATE(),
		ADD_MOL_ID INT,
		UPDATE_DATE DATETIME,
		UPDATE_MOL_ID INT
        )

    SET IDENTITY_INSERT SDOCS_STOCKS ON
        IF EXISTS(SELECT 1 FROM CISP.SYS.TABLES WHERE NAME = 'SDOCS_BUNKS')
            INSERT INTO SDOCS_STOCKS(STOCK_ID, NAME, SUBJECT_ID, EXT_SUBJECT_ID)
            SELECT BUNK_ID, NAME, SUBJECT_ID, EXT_SUBJECT_ID FROM CISP..SDOCS_BUNKS
        ELSE
            INSERT INTO SDOCS_STOCKS(STOCK_ID, NAME, SUBJECT_ID, EXT_SUBJECT_ID)
            SELECT STOCK_ID, NAME, SUBJECT_ID, EXT_SUBJECT_ID FROM CISP..SDOCS_STOCKS
    SET IDENTITY_INSERT SDOCS_STOCKS OFF
END
GO

IF OBJECT_ID('SDOCS_BUNKS') IS NOT NULL
    IF EXISTS(SELECT 1 FROM SYS.TABLES WHERE NAME = 'SDOCS_BUNKS') DROP TABLE SDOCS_BUNKS
    ELSE DROP SYNONYM SDOCS_BUNKS
GO

IF OBJECT_ID('SDOCS_STOCKS_ADDRS') IS NULL
    -- DROP TABLE SDOCS_STOCKS_ADDRS
    CREATE TABLE SDOCS_STOCKS_ADDRS(
        ADDR_ID INT IDENTITY PRIMARY KEY,
        STOCK_ID INT,
        NAME VARCHAR(150),
        IS_LOCKED BIT NOT NULL DEFAULT(0),
		IS_DELETED BIT NOT NULL DEFAULT(0),
		ADD_DATE DATETIME DEFAULT GETDATE(),
        ADD_MOL_ID INT,
		UPDATE_DATE DATETIME,
		UPDATE_MOL_ID INT,
    )
GO

IF OBJECT_ID('SDOCS_STOCKS_MOLS') IS NULL
BEGIN
    -- DROP TABLE SDOCS_STOCKS_MOLS
    CREATE TABLE SDOCS_STOCKS_MOLS(
        ID INT IDENTITY PRIMARY KEY,
        STOCK_ID INT,
        MOL_ID INT,
        IS_KEEPER BIT,
        IS_DISPATCH BIT,
        IS_MANAGER BIT,
		ADD_DATE DATETIME DEFAULT GETDATE(),
        ADD_MOL_ID INT,
		UPDATE_DATE DATETIME,
		UPDATE_MOL_ID INT,
    )
    CREATE UNIQUE INDEX IX_SDOCS_STOCKS_MOLS ON SDOCS_STOCKS_MOLS(STOCK_ID, MOL_ID)
END
GO

IF OBJECT_ID('SDOCS_STOCKS_PRODUCTS') IS NULL
BEGIN
    -- DROP TABLE SDOCS_STOCKS_PRODUCTS
    CREATE TABLE SDOCS_STOCKS_PRODUCTS(
        ID INT IDENTITY PRIMARY KEY,
        STOCK_ID INT,
        ADDR_ID INT,
        PRODUCT_ID INT,
		ADD_DATE DATETIME DEFAULT GETDATE(),
        ADD_MOL_ID INT,
    )
    CREATE UNIQUE INDEX IX_SDOCS_STOCKS_PRODUCTS ON SDOCS_STOCKS_PRODUCTS(ADDR_ID, PRODUCT_ID)
END
GO

IF OBJECT_ID('SDOCS_R_STOCKS_TURNS') IS NOT NULL DROP TABLE SDOCS_R_STOCKS_TURNS
GO
CREATE TABLE SDOCS_R_STOCKS_TURNS(
	MOL_ID INT,
	D_FROM DATE,
	D_TO DATE,
    ACC_REGISTER_ID INT,
    PRODUCT_ID INT,
	STOCK_ID INT,
    ADDR_ID INT,
	UNIT_ID INT,
	Q_START FLOAT,
	Q_INPUT FLOAT,
	Q_OUTPUT FLOAT,
	Q_END FLOAT,
	D_CALC DATETIME NOT NULL DEFAULT GETDATE(),
	INDEX IX_SDOCS_R_STOCKS_TURNS2(MOL_ID, ACC_REGISTER_ID, PRODUCT_ID, STOCK_ID, ADDR_ID)
)
GO

IF DBO.COLUMN_ID('SDOCS.STOCK_ID') IS NULL
    EXEC SP_RENAME 'SDOCS.BUNK_ID', 'STOCK_ID', 'COLUMN'
IF DBO.COLUMN_ID('SDOCS_GOALS.STOCK_ID') IS NULL
    EXEC SP_RENAME 'SDOCS_GOALS.BUNK_ID', 'STOCK_ID', 'COLUMN'
IF DBO.COLUMN_ID('SDOCS_GOALS_MOLS.STOCK_ID') IS NULL
    EXEC SP_RENAME 'SDOCS_GOALS_MOLS.BUNK_ID', 'STOCK_ID', 'COLUMN'
IF DBO.COLUMN_ID('SDOCS_GOALS_DETAILS.STOCK_ID') IS NULL
    EXEC SP_RENAME 'SDOCS_GOALS_DETAILS.BUNK_ID', 'STOCK_ID', 'COLUMN'
IF DBO.COLUMN_ID('SDOCS_PROVIDES.STOCK_ID') IS NULL
    EXEC SP_RENAME 'SDOCS_PROVIDES.BUNK_ID', 'STOCK_ID', 'COLUMN'
GO
