IF DBO.COLUMN_ID('MFR_WK_SHEETS_DETAILS.WK_EXEC_ROWS') IS NULL
BEGIN
    ALTER TABLE MFR_WK_SHEETS_DETAILS ADD 
        WK_EXEC_ROWS INT,
        WK_EXEC_ROWS_COMPLETED INT,
        BRIG_EXECUTORS INT,
        BRIG_WK_HOURS FLOAT
END
GO
