/****** Object:  Synonym [MFR_DRAFTS]    Script Date: 9/18/2024 3:28:00 PM ******/
IF NOT EXISTS (SELECT * FROM sys.synonyms WHERE name = N'MFR_DRAFTS' AND schema_id = SCHEMA_ID(N'dbo'))
CREATE SYNONYM [MFR_DRAFTS] FOR [SDOCS_MFR_DRAFTS]
GO

/****** Object:  Synonym [MFR_DRAFTS_ITEMS]    Script Date: 9/18/2024 3:28:00 PM ******/
IF NOT EXISTS (SELECT * FROM sys.synonyms WHERE name = N'MFR_DRAFTS_ITEMS' AND schema_id = SCHEMA_ID(N'dbo'))
CREATE SYNONYM [MFR_DRAFTS_ITEMS] FOR [SDOCS_MFR_DRAFTS_ITEMS]
GO

/****** Object:  Synonym [MFR_DRAFTS_OPERS]    Script Date: 9/18/2024 3:28:00 PM ******/
IF NOT EXISTS (SELECT * FROM sys.synonyms WHERE name = N'MFR_DRAFTS_OPERS' AND schema_id = SCHEMA_ID(N'dbo'))
CREATE SYNONYM [MFR_DRAFTS_OPERS] FOR [SDOCS_MFR_DRAFTS_OPERS]
GO

/****** Object:  Synonym [MFR_DRAFTS_OPERS_RESOURCES]    Script Date: 9/18/2024 3:28:00 PM ******/
IF NOT EXISTS (SELECT * FROM sys.synonyms WHERE name = N'MFR_DRAFTS_OPERS_RESOURCES' AND schema_id = SCHEMA_ID(N'dbo'))
CREATE SYNONYM [MFR_DRAFTS_OPERS_RESOURCES] FOR [SDOCS_MFR_DRAFTS_OPERS_RESOURCES]
GO

/****** Object:  Synonym [MFR_DRAFTS_OPERS_EXECUTORS]    Script Date: 9/18/2024 3:28:00 PM ******/
IF NOT EXISTS (SELECT * FROM sys.synonyms WHERE name = N'MFR_DRAFTS_OPERS_EXECUTORS' AND schema_id = SCHEMA_ID(N'dbo'))
CREATE SYNONYM [MFR_DRAFTS_OPERS_EXECUTORS] FOR [SDOCS_MFR_DRAFTS_OPERS_EXECUTORS]
GO

/****** Object:  Synonym [MFR_DRAFTS_OPERS_COOPS]    Script Date: 9/18/2024 3:28:00 PM ******/
IF NOT EXISTS (SELECT * FROM sys.synonyms WHERE name = N'MFR_DRAFTS_OPERS_COOPS' AND schema_id = SCHEMA_ID(N'dbo'))
CREATE SYNONYM [MFR_DRAFTS_OPERS_COOPS] FOR [SDOCS_MFR_DRAFTS_OPERS_COOPS]
GO
