IF OBJECT_ID('DEALS_DOCS_PRINCIPALS_SPECS') IS NOT NULL DROP VIEW DEALS_DOCS_PRINCIPALS_SPECS
GO

CREATE VIEW DEALS_DOCS_PRINCIPALS_SPECS
WITH SCHEMABINDING
AS 
SELECT DOCUMENT_ID, NAME = NUMBER, D_DOC, NUMBER, EXTERNAL_ID
FROM DBO.DOCUMENTS
WHERE CHARINDEX('СПЕЦИФИКАЦИЯ КОМИССИИ', TAGS, 1) > 0

GO

CREATE UNIQUE CLUSTERED INDEX IDX_DEALS_DOCS_PRINCIPALS_SPECS ON DEALS_DOCS_PRINCIPALS_SPECS(DOCUMENT_ID)
GO
