IF OBJECT_ID('DEALS_DOCS_SPECS') IS NOT NULL DROP VIEW DEALS_DOCS_SPECS
GO

CREATE VIEW DEALS_DOCS_SPECS
WITH SCHEMABINDING
AS 
SELECT DOC_ID, D_DOC, NUMBER, EXTERNAL_ID
FROM DBO.DEALS_DOCS
WHERE TYPE_ID = 2

GO

CREATE UNIQUE CLUSTERED INDEX IDX_DEALS_DOCS_SPECS ON DEALS_DOCS_SPECS(DOC_ID)
GO
