IF OBJECT_ID('DEALS_DOCS_PRINCIPALS_COMISSIONS') IS NOT NULL DROP VIEW DEALS_DOCS_PRINCIPALS_COMISSIONS
GO

IF OBJECT_ID('DEALS_DOCS_PRINCIPALS_COMMISSIONS') IS NOT NULL DROP VIEW DEALS_DOCS_PRINCIPALS_COMMISSIONS
GO

CREATE VIEW DEALS_DOCS_PRINCIPALS_COMMISSIONS
WITH SCHEMABINDING
AS 
SELECT DOCUMENT_ID, NAME = NUMBER, D_DOC, NUMBER, EXTERNAL_ID
FROM DBO.DOCUMENTS
WHERE CHARINDEX('ДОГОВОР КОМИССИИ', TAGS, 1) > 0

GO

CREATE UNIQUE CLUSTERED INDEX IDX_DEALS_DOCS_PRINCIPALS_COMMISSIONS ON DEALS_DOCS_PRINCIPALS_COMMISSIONS(DOCUMENT_ID)
GO
