IF OBJECT_ID('DEALS_NUMBERS') IS NOT NULL DROP VIEW DEALS_NUMBERS
GO
CREATE VIEW DEALS_NUMBERS 
AS 
SELECT
	DEAL_ID, NUMBER AS NAME
FROM DEALS
	JOIN DEALS_STATUSES S ON S.STATUS_ID = DEALS.STATUS_ID
WHERE S.IS_ERROR = 0
	AND LEN(NUMBER) >= 5 -- SOME FILTER

GO
