IF OBJECT_ID('DEALS_STATUSES') IS NOT NULL DROP VIEW DEALS_STATUSES
GO
CREATE VIEW DEALS_STATUSES 
AS 
SELECT
	STATUS_ID,
	NAME,
	IS_CURRENT = CAST(
		CASE
			WHEN STATUS_ID NOT IN (33,34,35,40,50) THEN 1
			ELSE 0
		END AS BIT),
	IS_CLOSED = CAST(
		CASE
			WHEN STATUS_ID IN (33, 34, 35, 40, 50) THEN 1
			ELSE 0
		END AS BIT),
	IS_ERROR = CAST(
		CASE
			WHEN STATUS_ID IN (33, 34, 40) THEN 1
			ELSE 0
		END AS BIT)
FROM PROJECTS_STATUSES
WHERE IS_DEAL = 1

GO
