IF DBO.COLUMN_ID('SDOCS_MFR_OPERS.PROJECT_TASK_NAME') IS NULL
BEGIN
    ALTER TABLE SDOCS_MFR_OPERS ADD PROJECT_TASK_NAME VARCHAR(50)

    EXEC SP_EXECUTESQL N'
    UPDATE X SET PROJECT_TASK_NAME = LEFT(P.NAME, 50)
    FROM SDOCS_MFR_OPERS X
        JOIN PROJECTS_TASKS T ON T.TASK_ID = X.PROJECT_TASK_ID
            JOIN PROJECTS P ON P.PROJECT_ID = T.PROJECT_ID
    '
END
GO
