IF OBJECT_ID('SUPPLY_INVOICES_DOGOVORS') IS NOT NULL DROP VIEW SUPPLY_INVOICES_DOGOVORS
GO

CREATE VIEW SUPPLY_INVOICES_DOGOVORS
AS 
SELECT 
    DOCUMENT_ID, 
    NAME = NUMBER,
    D_DOC, NUMBER, SUBJECT_ID, AGENT_ID
FROM DOCUMENTS
WHERE TYPE_ID = 2
    AND AGENT_ID IS NOT NULL
    AND STATUS_ID >= 0

GO

-- select * from SUPPLY_INVOICES_DOGOVORS where SUBJECT_ID = 15134
-- select * from agents where AGENT_ID = 16486
