IF OBJECT_ID('V_SUPPLY_R_INVPAYS_TOTALS') IS NOT NULL DROP VIEW V_SUPPLY_R_INVPAYS_TOTALS
GO
-- SELECT TOP 50 * FROM V_SUPPLY_R_INVPAYS_TOTALS
CREATE VIEW V_SUPPLY_R_INVPAYS_TOTALS
AS
SELECT *,
    CONTENT = CONCAT(INV_NUMBER, '#', MFR_NUMBER, '#', ITEM_NAME, '#', MANAGER_NAME, '#', VENDOR_NAME)
FROM (
    SELECT    
        X.ROW_ID,
        X.MFR_DOC_ID,
        MFR_NUMBER = ISNULL(MFR.NUMBER, '-'),
        X.ITEM_ID,
        ITEM_NAME = P.NAME,
        MANAGER_NAME = MOLS.NAME,
        X.INV_D_PLAN,
        X.INV_MS_D_PLAN,
        INV_NUMBER = I.NUMBER,
        INV_CONDITION,
        INV_CONDITION_PAY,
        INV_CONDITION_FUND,
        INV_ID,
        INV_DATE,
        X.INV_MILESTONE_ID,
        INV_MILESTONE = CONCAT(MS.MILESTONE_ID, '.', MS.NAME),
        VENDOR_NAME = A.NAME,
	    INV_D_PLAN_MONTH = LEFT(CONVERT(VARCHAR, X.INV_D_PLAN, 20), 7),
	    INV_D_PLAN_WEEK = DATEPART(ISO_WEEK, X.INV_D_PLAN),		
        INV_D_MFR,
        INV_D_MFR_TO,
        INV_Q,
        INV_Q_SHIP,
        INV_VALUE,
        SHIP_VALUE = INV_Q_SHIP / NULLIF(INV_Q, 0) * INV_VALUE,
        FINDOC_VALUE,
        INV_FUND_VALUE
    FROM SUPPLY_R_INVPAYS_TOTALS X
        JOIN SUPPLY_INVOICES I ON I.DOC_ID = X.INV_ID
            JOIN AGENTS A ON A.AGENT_ID = I.AGENT_ID
            LEFT JOIN MOLS ON MOLS.MOL_ID = I.MOL_ID
        LEFT JOIN SDOCS_MFR MFR ON MFR.DOC_ID = X.MFR_DOC_ID
        LEFT JOIN SDOCS_MILESTONES_NAMES MS ON MS.MILESTONE_ID = X.INV_MILESTONE_ID
        LEFT JOIN PRODUCTS P ON P.PRODUCT_ID = X.ITEM_ID
    WHERE I.STATUS_ID >= 0
    ) V
GO
