-- dbcontext: CISP
IF DB_NAME() IN ('CISP', 'CISP_TEST')
BEGIN
    DELETE FROM SDOCS_TYPES WHERE TYPE_ID = 100

    INSERT INTO SDOCS_TYPES(TYPE_ID, DIRECTION, NAME)
    VALUES (100, 1, 'Инвентаризация')
END
GO
