IF DBO.COLUMN_ID('SDOCS.CONSIGNEE_ID') IS NULL
BEGIN
    ALTER TABLE SDOCS ADD CONSIGNEE_ID INT
    
    EXEC SP_EXECUTESQL N'
    UPDATE X SET CONSIGNEE_ID = S.PRED_ID
    FROM SDOCS X
        JOIN SUBJECTS S ON S.SUBJECT_ID = X.SUBJECT_ID
    WHERE X.TYPE_ID = 18
    '
END
GO
