IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[MFR_PDM_ATTRS]') AND type in (N'U'))
BEGIN
CREATE TABLE [MFR_PDM_ATTRS]
(
    [ID] [bigint] IDENTITY(1,1) NOT NULL,
    [PDM_ID] [int] NULL,
    [ATTR_ID] [int] NULL,
    [NOTE] [varchar](max) NULL,
    [ADD_DATE] [datetime] DEFAULT getdate(),
    [ADD_MOL_ID] [int] NULL,
    [UPDATE_DATE] [datetime] NULL,
    [UPDATE_MOL_ID] [int] NULL,
    [IS_DELETED] [bit] NULL,
    CONSTRAINT [PK_MFR_PDM_ATTRS] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[MFR_PDM_ATTRS]') AND name = N'IX_MFR_PDM_ATTRS')
CREATE CLUSTERED INDEX [IX_MFR_PDM_ATTRS] ON [MFR_PDM_ATTRS]
(
	[PDM_ID] ASC,
	[ATTR_ID] ASC
)
GO
