IF OBJECT_ID('DEPTS_NODES') IS NOT NULL DROP VIEW DEPTS_NODES
GO
-- SELECT TOP 10 * FROM DEPTS_NODES
CREATE VIEW DEPTS_NODES
AS

SELECT 
	PARENT_ID, DEPT_ID, NAME, 
    SUBJECT_ID, NOTE, SHORT_NAME, CHIEF_ID, RESOURCE_ID,
    LEVEL_ID, SORT_ID, HAS_CHILDS,
    NODE, NODE_ID,
    IS_DELETED
FROM DEPTS

GO
