IF OBJECT_ID('FIN_GOALS_ACCOUNTS_NAMES') IS NOT NULL DROP VIEW FIN_GOALS_ACCOUNTS_NAMES
GO
CREATE VIEW FIN_GOALS_ACCOUNTS_NAMES AS
	SELECT GOAL_ACCOUNT_ID, NAME, SHORT_NAME
	FROM FIN_GOALS_ACCOUNTS
GO
