IF OBJECT_ID('MFR_PDM_VARIANTS') IS NOT NULL DROP VIEW MFR_PDM_VARIANTS
IF OBJECT_ID('MFR_PDM_VERSIONS') IS NOT NULL DROP VIEW MFR_PDM_VERSIONS
GO
-- SELECT TOP 100 * FROM MFR_PDM_VERSIONS
CREATE VIEW MFR_PDM_VERSIONS
AS
SELECT 
	X.PDM_ID,
	X.ITEM_ID,
	X.VERSION_NUMBER,
	X.NUMBER,
	X.IS_DEFAULT,	
	X.IS_DELETED
FROM MFR_PDMS X
GO
