IF OBJECT_ID('MFR_ATTRS') IS NOT NULL  DROP VIEW MFR_ATTRS
GO
CREATE VIEW MFR_ATTRS AS
    SELECT
        ATTR_ID,
        SLICE,
        GROUP_NAME,
        NAME,
        GROUP_KEY,
        ATTR_KEY,
        NOTE,
        ADD_DATE,
        ADD_MOL_ID,
        UPDATE_DATE,
        UPDATE_MOL_ID,
        VALUE_TYPE,
        IS_DELETED
    FROM PRODMETA_ATTRS X
    WHERE ATTR_KEY IS NOT NULL
GO

IF OBJECT_ID('MFR_ATTRS_REFS') IS NOT NULL  DROP VIEW MFR_ATTRS_REFS
GO
CREATE VIEW MFR_ATTRS_REFS AS
    SELECT ATTR_ID, NAME FROM PRODMETA_ATTRS X
GO
