IF OBJECT_ID('MFR_SDOCS_STATUSES') IS NOT NULL DROP VIEW MFR_SDOCS_STATUSES
GO
-- SELECT TOP 10 * FROM MFR_SDOCS_STATUSES
CREATE VIEW MFR_SDOCS_STATUSES
AS
    SELECT * FROM SDOCS_STATUSES
    WHERE STATUS_ID NOT IN (1,2,5,20)
GO
