IF OBJECT_ID('MFR_SWAPS_PRODUCTS') IS NOT NULL DROP VIEW MFR_SWAPS_PRODUCTS
GO
-- SELECT TOP 50 * FROM MFR_SWAPS_PRODUCTS
CREATE VIEW MFR_SWAPS_PRODUCTS
AS
SELECT    
    X.DETAIL_ID,
    X.NUMPOS,
    X.DOC_ID,
    X.MFR_NUMBER,
    X.DRAFT_ID,
    X.PRODUCT_ID,
    X.UNIT_ID,
    X.QUANTITY,
    X.DEST_PRODUCT_ID,
    X.DEST_UNIT_ID,
    X.DEST_QUANTITY,
    X.NOTE,
    X.ERRORS
FROM SDOCS_PRODUCTS X WITH(NOLOCK)

GO
