IF OBJECT_ID('MFR_SWAPS') IS NOT NULL DROP VIEW MFR_SWAPS
GO
-- SELECT TOP 50 * FROM MFR_SWAPS
CREATE VIEW MFR_SWAPS
AS
SELECT    
    X.DOC_ID,
    X.TYPE_ID,
    X.SUBJECT_ID,
    SUBJECT_NAME = SUBJ.SHORT_NAME,
    X.STATUS_ID,
    STATUS_NAME = S.NAME,
    X.SOURCE_ID,
    X.D_DOC,
    X.NUMBER, 
    X.MOL_ID,
    MOL_NAME = M.NAME,
    X.NOTE,
    X.CONTENT,        
    -- TIMESTAMP
    X.ADD_MOL_ID,
    X.ADD_DATE,
    X.UPDATE_DATE,
    X.UPDATE_MOL_ID,
    IS_DELETED = CASE WHEN X.STATUS_ID = -1 THEN 1 ELSE 0 END
FROM SDOCS X
    LEFT JOIN SUBJECTS SUBJ ON SUBJ.SUBJECT_ID = X.SUBJECT_ID
    LEFT JOIN SDOCS_STATUSES S ON S.STATUS_ID = X.STATUS_ID
    LEFT JOIN MOLS M ON M.MOL_ID = X.MOL_ID
WHERE X.TYPE_ID = 11
GO
