IF OBJECT_ID('OBJS_FOLDERS_SHARES_META') IS NOT NULL DROP VIEW OBJS_FOLDERS_SHARES_META
GO
CREATE VIEW OBJS_FOLDERS_SHARES_META AS
	SELECT
		FOLDER_ID = O.OWNER_ID,
		OS.MOL_ID,
		OS.MOL_NODE_ID,
		OS.A_READ,
		OS.A_UPDATE,
		OS.A_ACCESS
	FROM OBJS_SHARES OS
		JOIN OBJS O ON O.OBJ_UID = OS.OBJ_UID
	WHERE O.OWNER_TYPE = 'F'
GO
