IF OBJECT_ID('PAYORDERS_CHILDS') IS NOT NULL DROP VIEW PAYORDERS_CHILDS
GO
CREATE VIEW PAYORDERS_CHILDS AS
SELECT
    X.PARENT_ID,
	X.PAYORDER_ID,
	X.STATUS_ID,
    X.D_ADD,
	X.D_PAY_PLAN,
	X.NUMBER,
	X.CCY_ID,
	X.VALUE_CCY,
	X.NOTE
FROM PAYORDERS X
WHERE PARENT_ID IS NOT NULL
	AND IS_DELETED = 0
GO
