IF OBJECT_ID('PRODUCTS_PLANS_GROUPS') IS NOT NULL DROP VIEW PRODUCTS_PLANS_GROUPS
GO
-- SELECT * FROM PRODUCTS_PLANS_GROUPS
CREATE VIEW PRODUCTS_PLANS_GROUPS
AS
SELECT 
	PLAN_GROUP_ID = ATTR_ID,
	NAME
FROM PRODMETA_ATTRS
WHERE GROUP_KEY = 'MfrPlanProdGrp'
GO
