IF OBJECT_ID('PROJECTS_INFO') IS NOT NULL DROP VIEW PROJECTS_INFO
GO
CREATE VIEW PROJECTS_INFO
AS
SELECT 
    PROJECT_ID,
    NAME,
    CURATOR_ID,
    ADMIN_ID,
    CHIEF_ID,
    ADD_DATE,
    D_FROM,
    D_TO,
    D_TO_MIN,
    D_TO_FORECAST,
    STATUS_ID,
	TYPE_ID
FROM PROJECTS
WHERE TYPE_ID NOT IN (3)
    AND STATUS_ID NOT IN (-1)

GO
