IF OBJECT_ID('PROJECTS_MOLS_NODES') IS NOT NULL	DROP VIEW PROJECTS_MOLS_NODES
GO

CREATE VIEW PROJECTS_MOLS_NODES 
AS 
SELECT
	pm.PROJECT_ID,
	pm.ID AS MOL_NODE_ID,
	pm.NAME,
	NAME_PATH = pm.NAME 
		+ ' (' 
			+ case 
				when len(p.name) < 20 then p.name
				else substring(p.NAME, 1, 20) + '...'
			  end
		+ ')',
	pm.PARENT_ID,
	pm.NODE, pm.HAS_CHILDS, pm.LEVEL_ID, pm.SORT_ID
FROM PROJECTS_MOLS pm
	JOIN PROJECTS p ON p.PROJECT_ID = pm.PROJECT_ID
WHERE pm.HAS_CHILDS = 1

GO
