IF OBJECT_ID('PROJECTS_NAMES') IS NOT NULL DROP VIEW PROJECTS_NAMES
GO
CREATE VIEW PROJECTS_NAMES
AS
SELECT 
    PROJECT_ID,
    NAME
FROM PROJECTS
WHERE TYPE_ID NOT IN (3)
    AND STATUS_ID NOT IN (-1)
GO
