IF OBJECT_ID('SDOCS_SHARES') IS NOT NULL DROP VIEW SDOCS_SHARES
GO
CREATE VIEW SDOCS_SHARES
AS
	SELECT
		DOC_ID = O.OWNER_ID,
		OS.MOL_ID,
		OS.MOL_NODE_ID,
		OS.A_READ,
		OS.A_UPDATE,
		OS.A_ACCESS
	FROM OBJS_SHARES OS
		JOIN OBJS O ON O.OBJ_UID = OS.OBJ_UID
	WHERE O.OWNER_TYPE = 'SD'
GO
