IF OBJECT_ID('SDOCS_REFS') IS NOT NULL DROP VIEW SDOCS_REFS
GO
-- SELECT TOP 10 * FROM SDOCS_REFS
CREATE VIEW SDOCS_REFS
AS
	SELECT
		DOC_ID,
		TYPE_ID,
		NAME = CONCAT(CONVERT(VARCHAR(10), D_DOC, 121), ' №', NUMBER, ' #', DOC_ID),
		NUMBER,
		D_DOC,
		AGENT_ID,
		VALUE_CCY,
		CCY_ID
	FROM SDOCS
	WHERE STATUS_ID >= 0
GO
