IF OBJECT_ID('SUPPLY_INVOICES_PRODUCTS') IS NOT NULL DROP VIEW SUPPLY_INVOICES_PRODUCTS
GO
-- SELECT TOP 50 * FROM SUPPLY_INVOICES_PRODUCTS
CREATE VIEW SUPPLY_INVOICES_PRODUCTS
AS
SELECT    
    DETAIL_ID,
    DOC_ID,
    NUMPOS,
    MFR_NUMBER,
    PRODUCT_ID,
    UNIT_ID,
    QUANTITY,
    PLAN_Q,
    DUE_DATE,
    PRICE,
    PRICE_PURE,
    NDS_RATIO,
    VALUE_NDS,    
    VALUE_PURE,
    VALUE_RUR,
    VALUE_CCY,
    HAS_DETAILS,
    NOTE
FROM SDOCS_PRODUCTS
GO
