IF OBJECT_ID('SUPPLY_BUYORDERS') IS NOT NULL DROP VIEW SUPPLY_BUYORDERS
GO
-- SELECT TOP 50 * FROM SUPPLY_BUYORDERS
CREATE VIEW SUPPLY_BUYORDERS
AS
SELECT    
    X.TYPE_ID,
    X.DOC_ID,
    X.ACC_REGISTER_ID,
    X.SUBJECT_ID,
    SUBJECT_NAME = SUBJ.SHORT_NAME,
    X.STATUS_ID,
    STATUS_NAME = S.NAME,
    X.D_DOC,
    X.D_DELIVERY,
    D_READY = X.D_ISSUE,
    X.NUMBER, 
    X.DOGOVOR_NUMBER,
    X.DOGOVOR_DATE,
    X.SPEC_NUMBER,
    X.SPEC_DATE,
    X.AGENT_ID,
    AGENT_NAME = AG.NAME,
    X.CONSIGNEE_ID,
    X.MOL_ID,
    MOL_NAME = M.NAME,
    X.CCY_ID,
    X.VALUE_CCY,
    X.VALUE_RUR,
    X.NOTE,
    X.CONTENT,
    X.REFKEY,
    -- TIMESTAMP
    X.ADD_MOL_ID,
    X.ADD_DATE,
    X.UPDATE_DATE,
    X.UPDATE_MOL_ID,
    -- EXCHANGE
    X.EXTERN_ID,    
    X.SOURCE_ID,
    X.REPLICATE_DATE
FROM SDOCS X
    LEFT JOIN SUBJECTS SUBJ ON SUBJ.SUBJECT_ID = X.SUBJECT_ID
    LEFT JOIN SDOCS_STATUSES S ON S.STATUS_ID = X.STATUS_ID
    LEFT JOIN AGENTS AG ON AG.AGENT_ID = X.AGENT_ID
    LEFT JOIN MOLS M ON M.MOL_ID = X.MOL_ID
WHERE X.TYPE_ID = 18
GO
