IF OBJECT_ID('SUPPLY_INVOICES_MILESTONES_NAMES') IS NOT NULL DROP VIEW SUPPLY_INVOICES_MILESTONES_NAMES
GO
-- SELECT TOP 50 * FROM SUPPLY_INVOICES_MILESTONES_NAMES
CREATE VIEW SUPPLY_INVOICES_MILESTONES_NAMES
AS
    SELECT MILESTONE_ID = ID, NAME
    FROM OPTIONS_LISTS 
    WHERE L_GROUP = 'SupplyPaysMilestones'
GO
