IF OBJECT_ID('SUPPLY_INVOICES_REFS') IS NOT NULL DROP VIEW SUPPLY_INVOICES_REFS
GO
-- SELECT TOP 50 * FROM SUPPLY_INVOICES_REFS
CREATE VIEW SUPPLY_INVOICES_REFS
AS
SELECT 
    DOC_ID, 
    NAME = CONCAT(
            AGENT_NAME,
            ' от ', CONVERT(VARCHAR(10), D_DOC, 121),
            ' №', ISNULL(NULLIF(NUMBER,''), '(не указан)')
            )
FROM SUPPLY_INVOICES
WHERE STATUS_ID >= 0
GO
