IF OBJECT_ID('V_AGENTS') IS NOT NULL DROP VIEW V_AGENTS
GO
CREATE VIEW V_AGENTS
AS
SELECT 
	X.AGENT_ID,
	X.STATUS_ID,
	X.CATEGORY_ID,
	X.NAME,	
	X.NAME_PRINT,
	STATUS_NAME = S.NAME,
	X.INN,
	X.GROUP_NAME,
	COUNTRY_NAME = X.ADDR_COUNTRY,
	CITY_NAME = CONCAT(X.ADDR_CITY, CASE WHEN X.ADDR_CITY <> X.ADDR_REGION THEN ' ' + X.ADDR_REGION END),
	X.DADATA_HID
FROM AGENTS X
	JOIN AGENTS_STATUSES S ON S.STATUS_ID = X.STATUS_ID
GO
