IF OBJECT_ID('V_DEALS') IS NOT NULL DROP VIEW V_DEALS
GO
CREATE VIEW V_DEALS
AS 
SELECT
    D.DEAL_ID,
	D.BUDGET_ID,
    D.SUBJECT_ID,
    D.VENDOR_ID,
	D.CUSTOMER_ID,
    D.D_DOC,
    D.NUMBER,
	D.DOGOVOR_NUMBER,
	D.DOGOVOR_DATE,
	D.SPEC_NUMBER,
	D.SPEC_DATE,
	D.CRM_NUMBER,
	D.PAY_CONDITIONS,
	DEAL_NAME = CONCAT(D.NUMBER, ' ', AG.NAME),
	VENDOR_NAME = v.SHORT_NAME,
	BUDGET_NAME = B.NAME,
	AGENT_NAME = AG.NAME,
	DIRECTION_NAME = COALESCE(DIR.SHORT_NAME, DIR.NAME, '-'),
	MOL_NAME = MOLS.NAME,
	D.VALUE_CCY,
    DEAL_HID = CONCAT('#', D.DEAL_ID),
	BUDGET_HID = CONCAT('#', D.BUDGET_ID)
FROM DEALS D
	JOIN SUBJECTS AS V ON V.SUBJECT_ID = D.VENDOR_ID
	JOIN BUDGETS B ON B.BUDGET_ID = D.BUDGET_ID
	JOIN DEPTS DIR ON DIR.DEPT_ID = ISNULL(D.DIRECTION_ID,0)
	JOIN MOLS ON MOLS.MOL_ID = D.MANAGER_ID
	JOIN AGENTS AG ON AG.AGENT_ID = D.CUSTOMER_ID
	
GO
