IF OBJECT_ID('V_MFR_R_PROVIDES_STOCK_ITEMS') IS NOT NULL DROP VIEW V_MFR_R_PROVIDES_STOCK_ITEMS
GO
-- SELECT TOP 100 * FROM V_MFR_R_PROVIDES_STOCK_ITEMS
CREATE VIEW V_MFR_R_PROVIDES_STOCK_ITEMS
AS
SELECT 
	ACC_REGISTER_ID = ISNULL(X.ACC_REGISTER_ID, 0),
    X.ITEM_ID,
    ITEM_NAME = P.NAME,
    X.MFR_DOC_ID,
    MFR_NUMBER = ISNULL(MFR.NUMBER, '<документ не указан>'),
	X.UNIT_NAME,
	Q_SHIP, Q_LZK, Q_JOB, Q_RETURN,
    Q_LEFT = Q_SHIP - Q_JOB + Q_RETURN
FROM (
	SELECT 
        ACC_REGISTER_ID, ITEM_ID, UNIT_NAME, MFR_DOC_ID,
		Q_SHIP = ISNULL(SUM(Q_SHIP), 0),
		Q_LZK = ISNULL(SUM(Q_LZK), 0),
		Q_JOB = ISNULL(SUM(Q_JOB), 0),
		Q_RETURN = ISNULL(SUM(Q_RETURN), 0)
	FROM V_MFR_R_PROVIDES_ALL
    WHERE XSLICE != 'MANUAL'
	GROUP BY ACC_REGISTER_ID, ITEM_ID, UNIT_NAME, MFR_DOC_ID
	) X
	JOIN PRODUCTS P ON P.PRODUCT_ID = X.ITEM_ID
    LEFT JOIN MFR_SDOCS MFR ON MFR.DOC_ID = X.MFR_DOC_ID
GO
