IF OBJECT_ID('V_MFR_PLANS_PRODUCTS') IS NOT NULL DROP VIEW V_MFR_PLANS_PRODUCTS
GO
CREATE VIEW V_MFR_PLANS_PRODUCTS
AS
SELECT 
	X.PLAN_ID,
	X.PRODUCT_ID,
	P.NAME,
	X.QUANTITY,
	X.D_FROM,
	X.D_TO
FROM (
	SELECT 
		SD.PLAN_ID,
		X.PRODUCT_ID,
		QUANTITY = SUM(X.QUANTITY),
		D_FROM = MIN(SD.D_ISSUE_PLAN),
		D_TO = MAX(SD.D_ISSUE_PLAN)
	FROM SDOCS_PRODUCTS X
		JOIN SDOCS SD ON SD.DOC_ID = X.DOC_ID
	WHERE SD.PLAN_ID IS NOT NULL
	GROUP BY SD.PLAN_ID, PRODUCT_ID
	) X
	JOIN PRODUCTS P ON P.PRODUCT_ID = X.PRODUCT_ID
GO
