IF OBJECT_ID('V_MFR_PLANS_JOBS') IS NOT NULL DROP VIEW V_MFR_PLANS_JOBS
GO
-- SELECT TOP 100 * FROM V_MFR_PLANS_JOBS
CREATE VIEW V_MFR_PLANS_JOBS
AS
SELECT 
	JP.SUBJECT_ID,
	X.PLAN_ID,
	PLAN_NUMBER = JP.NUMBER,
	X.PLAN_JOB_ID,
	TYPE_SHORT_NAME = TP.SHORT_NAME,
	X.TYPE_ID,
	X.STATUS_ID,
	X.PLACE_ID,
	X.PLACE_TO_ID,
	STATUS_NAME = ST.NAME,
	PLACE_NAME = CONCAT(PL.NAME, '-', PL.NOTE),
	PLACE_TO_NAME = CONCAT(PL2.NAME, '-', PL2.NOTE),
	X.D_DOC,
	X.D_CLOSED,
	X.UPDATE_DATE,
	X.NUMBER,
	RESPONSIBLE_NAME = MOLS.NAME,
	X.NOTE,
	X.CONTENT
FROM MFR_PLANS_JOBS X WITH(NOLOCK)
	LEFT JOIN MFR_PLANS JP WITH(NOLOCK) ON JP.PLAN_ID = X.PLAN_ID
	JOIN MFR_PLANS_JOBS_TYPES TP WITH(NOLOCK) ON TP.TYPE_ID = X.TYPE_ID
	JOIN MFR_JOBS_STATUSES ST WITH(NOLOCK) ON ST.STATUS_ID = X.STATUS_ID	
	LEFT JOIN MFR_PLACES PL WITH(NOLOCK) ON PL.PLACE_ID = X.PLACE_ID
	LEFT JOIN MFR_PLACES PL2 WITH(NOLOCK) ON PL2.PLACE_ID = X.PLACE_TO_ID
	LEFT JOIN MOLS WITH(NOLOCK) ON MOLS.MOL_ID = X.EXECUTOR_ID
GO
