IF OBJECT_ID('V_MFR_PLANS_PRODUCTS_GROUPS') IS NOT NULL DROP VIEW V_MFR_PLANS_PRODUCTS_GROUPS
GO
-- SELECT * FROM V_MFR_PLANS_PRODUCTS_GROUPS ORDER BY NAME
-- SELECT * FROM PRODMETA_ATTRS WHERE GROUP_KEY = 'MFRPLANPRODGRP'
CREATE VIEW V_MFR_PLANS_PRODUCTS_GROUPS
AS
SELECT 
	GROUP_ID = A.ATTR_ID,
	A.NAME,
	PA.PRODUCT_ID	
FROM PRODUCTS_ATTRS PA
	JOIN PRODMETA_ATTRS A ON A.ATTR_ID = PA.ATTR_ID
WHERE A.GROUP_KEY = 'MfrPlanProdGrp'
	AND PA.IS_DELETED = 0
GO
