IF OBJECT_ID('V_MFR_PLANS_JOBS_TERMS_DETAILS') IS NOT NULL DROP VIEW V_MFR_PLANS_JOBS_TERMS_DETAILS
GO
-- SELECT TOP 10 * FROM V_MFR_PLANS_JOBS_TERMS_DETAILS
CREATE VIEW V_MFR_PLANS_JOBS_TERMS_DETAILS
AS
SELECT 
	X.ID,	
	X.TERM_ID,
	X.BARCODE,
	X.JOB_ID,
	X.JOB_DETAIL_ID,
	X.MFR_DOC_ID,
	MFR_NUMBER = SD.NUMBER,
	PARENT_ITEM_NAME = PI.NAME,
	X.ITEM_ID,
	ITEM_NAME = I.NAME,
	X.OPER_NUMBER,	
	X.OPER_NAME,
	X.PLAN_Q,
	X.FACT_Q,
	X.ADD_DATE
FROM MFR_PLANS_JOBS_TERMS_DETAILS X
	JOIN MFR_PLANS_JOBS_TERMS J WITH (NOLOCK) ON J.TERM_ID = X.TERM_ID
	LEFT JOIN SDOCS SD WITH (NOLOCK) ON SD.DOC_ID = X.MFR_DOC_ID
	JOIN MFR_PLANS_JOBS_DETAILS JD WITH (NOLOCK) ON JD.ID = X.JOB_DETAIL_ID
		LEFT JOIN PRODUCTS PI WITH (NOLOCK) ON PI.PRODUCT_ID = JD.PARENT_ITEM_ID
	JOIN PRODUCTS I WITH (NOLOCK) ON I.PRODUCT_ID = X.ITEM_ID
GO
