IF OBJECT_ID('V_MFR_R_PLANS_JOBS_ITEMS_ALL') IS NOT NULL DROP VIEW V_MFR_R_PLANS_JOBS_ITEMS_ALL
GO
-- SELECT TOP 100 * FROM V_MFR_R_PLANS_JOBS_ITEMS_ALL
CREATE VIEW V_MFR_R_PLANS_JOBS_ITEMS_ALL
AS
SELECT 
	MFR_DOC_ID,
	CONTENT_ID,
	ITEM_ID,
	OPER_ID,
	OPER_NUMBER,
	JOB_ID,
	JOB_DETAIL_ID,
    JOB_STATUS_ID,
	JOB_DATE,	
	PLAN_Q,
	FACT_Q
FROM MFR_R_PLANS_JOBS_ITEMS WITH(NOLOCK)

UNION ALL

SELECT 
	MFR_DOC_ID,
	CONTENT_ID,
	ITEM_ID,
	OPER_ID,
	OPER_NUMBER,
	JOB_ID,
	JOB_DETAIL_ID,
	JOB_STATUS_ID,
	JOB_DATE,	
	PLAN_Q,
	FACT_Q
FROM MFR_R_PLANS_JOBS_ITEMS_ARCHIVE WITH(NOLOCK)
WHERE ARCHIVE = 1

GO
