IF OBJECT_ID('V_MFR_PLANS_JOBS_TERMS') IS NOT NULL DROP VIEW V_MFR_PLANS_JOBS_TERMS
GO
-- SELECT TOP 100 * FROM V_MFR_PLANS_JOBS_TERMS
CREATE VIEW V_MFR_PLANS_JOBS_TERMS
AS
SELECT 
	X.TERM_ID,
	X.STATUS_ID,
	STATUS_NAME = ST.NAME,
	X.D_DOC,
	X.NUMBER,
	X.NOTE,
	ADD_MOL_NAME = MOLS.NAME
FROM MFR_PLANS_JOBS_TERMS X WITH(NOLOCK)
	LEFT JOIN MFR_JOBS_STATUSES ST WITH(NOLOCK) ON ST.STATUS_ID = X.STATUS_ID	
	LEFT JOIN MOLS WITH(NOLOCK) ON MOLS.MOL_ID = X.ADD_MOL_ID
GO
