IF OBJECT_ID('V_MFR_FIFO_JOBS') IS NOT NULL DROP VIEW V_MFR_FIFO_JOBS
GO
-- SELECT TOP 10 * FROM V_MFR_FIFO_JOBS
CREATE VIEW V_MFR_FIFO_JOBS
AS
SELECT
	J.PLAN_ID,
	JOB_ID = J.PLAN_JOB_ID,
	JOB_TYPE = TP.SLICE,
	JOB_DETAIL_ID = X.ID,
	JOB_STATUS_ID = J.STATUS_ID,
    X.ITEM_ID,
    X.CONTENT_ID,
	X.OPER_NUMBER,
	X.MFR_DOC_ID,
	J.D_DOC,
    J.D_CLOSED,
	SORT_NUMBER = CASE WHEN J.STATUS_ID = 100 THEN -1 ELSE 0 END,
	VALUE_Q = 
		CASE
			WHEN J.STATUS_ID = 100 THEN NULLIF(X.FACT_Q,0)
			ELSE ISNULL(NULLIF(X.FACT_Q,0), X.PLAN_Q)
		END,
	X.UNIT_NAME
FROM MFR_PLANS_JOBS_DETAILS X WITH (NOLOCK)
	JOIN MFR_PLANS_JOBS J WITH (NOLOCK) ON J.PLAN_JOB_ID = X.PLAN_JOB_ID
		JOIN MFR_PLANS_JOBS_TYPES TP WITH (NOLOCK) ON TP.TYPE_ID = J.TYPE_ID
	LEFT JOIN MFR_SDOCS MFR WITH(NOLOCK) ON MFR.DOC_ID = X.MFR_DOC_ID
WHERE J.STATUS_ID >= 0
	AND TP.SLICE = 'component'
	AND X.OPER_NUMBER IS NOT NULL
    
GO
