IF OBJECT_ID('V_MFR_SDOCS') IS NOT NULL DROP VIEW V_MFR_SDOCS
GO
-- SELECT TOP 10 * FROM V_MFR_SDOCS
CREATE VIEW V_MFR_SDOCS
AS
SELECT 
	X.DOC_ID,
	X.TYPE_ID,
    X.EXT_TYPE_ID,
    X.EXT_PROBABILITY_ID,
    X.EXT_STATUS_ID,
	X.ACC_REGISTER_ID,
	X.PLAN_ID,
	PLAN_NAME = PL.NUMBER,
	PLAN_STATUS_ID = PL.STATUS_ID,
	X.STATUS_ID,
	STATUS_NAME = ST.NAME,
	X.PRIORITY_ID,
	X.PRIORITY_FINAL,
	X.PRIORITY_SORT,
	PRIORITY_CSS = PRIO.CSS,
	X.D_DOC,
	X.NUMBER,
	X.SUBJECT_ID,
	SUBJECT_NAME = SUBJECTS.SHORT_NAME,
	X.AGENT_ID,
	AGENT_NAME = AGENTS.NAME,
	X.DEAL_ID,
	X.DEAL_NUMBER,
	X.D_DELIVERY,
	X.D_SHIP,
	X.D_ISSUE_PLAN,
	X.D_ISSUE_FORECAST,
	X.D_ISSUE,
	X.D_ISSUE_CALC,
	DELIVERY_BUFFER = DATEDIFF(D, X.D_ISSUE_PLAN, X.D_ISSUE_CALC),
	DELIVERY_BUFFER2 = DATEDIFF(D, ISNULL(X.D_ISSUE, X.D_ISSUE_FORECAST), X.D_ISSUE_PLAN),
	MS.D_TO_PLAN_HAND,
    X.TALK_ID,
	X.CCY_ID,
	X.VALUE_CCY,
	X.NOTE,
	X.PART_PARENT_ID,
	X.PART_HAS_CHILDS,
	X.TEMPLATE_NAME,
	X.SYNC_DIRTY,
	X.EXTERN_ID,
	X.ADD_DATE,
	X.CONTENT
FROM SDOCS X WITH(NOLOCK)
	LEFT JOIN SUBJECTS WITH(NOLOCK) ON SUBJECTS.SUBJECT_ID = X.SUBJECT_ID
	LEFT JOIN MFR_PLANS PL WITH(NOLOCK) ON PL.PLAN_ID = X.PLAN_ID		
	LEFT JOIN AGENTS WITH(NOLOCK) ON AGENTS.AGENT_ID = X.AGENT_ID
	LEFT JOIN SDOCS_STATUSES ST WITH(NOLOCK) ON ST.STATUS_ID = X.STATUS_ID
	LEFT JOIN MFR_SDOCS_PRIORITIES PRIO WITH(NOLOCK) ON X.PRIORITY_ID between PRIO.PRIORITY_ID and PRIO.PRIORITY_MAX
	LEFT JOIN (
		SELECT DOC_ID, D_TO_PLAN_HAND = MAX(MS.D_TO_PLAN_HAND)
		FROM MFR_SDOCS_MILESTONES MS WITH(NOLOCK)
			JOIN MFR_ATTRS A ON A.ATTR_ID = MS.ATTR_ID
		WHERE A.NAME LIKE '%Готовая продукция%'
		GROUP BY DOC_ID
	) MS ON MS.DOC_ID = X.DOC_ID
WHERE TYPE_ID = 5
GO


IF NOT EXISTS (SELECT * FROM sys.synonyms WHERE name = N'MFR_SDOCS' AND schema_id = SCHEMA_ID(N'dbo'))
CREATE SYNONYM [MFR_SDOCS] FOR [V_MFR_SDOCS]
GO
