IF OBJECT_ID('V_MFR_PLANS_QJOBS1') IS NOT NULL DROP VIEW V_MFR_PLANS_QJOBS1
GO
-- SELECT TOP 10 * FROM V_MFR_PLANS_QJOBS1
CREATE VIEW V_MFR_PLANS_QJOBS1
AS
SELECT *,
	QUEUE_HOURS = CASE WHEN PLAN_HOURS - FACT_HOURS > 0 THEN PLAN_HOURS - FACT_HOURS END
FROM (
	SELECT 		
		X.ID,	
		J.SUBJECT_ID,
		X.FLOW_ID,
		PLACE_ID = ISNULL(O.PLACE_ID, J.PLACE_ID),
		SD.PRIORITY_ID,
		PRIORITY_SORT = SD.PRIORITY_ID,
		PRIORITY_CSS = PRIO.CSS,
		X.PLAN_JOB_ID,
		X.MFR_DOC_ID,
		MFR_NUMBER = ISNULL(SD.NUMBER, 'б/н'),
		X.CONTENT_ID,
		X.ITEM_ID,
		C.DRAFT_ID,
		X.OPER_ID,
		OPER_STATUS_ID = O.STATUS_ID,
		X.OPER_NUMBER,
		X.OPER_NAME,
		O.WORK_TYPE_ID,
		OPER_D_FROM = O.D_FROM,
		OPER_D_TO = O.D_TO,
		X.PLAN_Q,
		X.FACT_Q,
		NORM_HOURS = X.NORM_DURATION_WK,
		PLAN_HOURS = ISNULL(X.PLAN_DURATION_WK * DUR1.FACTOR / DUR_H.FACTOR, 0),
		FACT_HOURS = ISNULL(X.DURATION_WK * DUR2.FACTOR / DUR_H.FACTOR, 0),
		COUNT_EXECUTORS = ISNULL(X.COUNT_EXECUTORS, 0),
		X.EXECUTORS_NAMES,
		RESOURCE_ID = ISNULL(X.RESOURCE_ID, O.RESOURCE_ID),
		X.OVERLOADS_DURATION_WK
	FROM MFR_PLANS_JOBS_DETAILS X WITH (NOLOCK)
		JOIN MFR_PLANS_JOBS J WITH (NOLOCK) ON J.PLAN_JOB_ID = X.PLAN_JOB_ID
		LEFT JOIN MFR_PLANS_JOBS_FLOWS F ON F.FLOW_ID = X.FLOW_ID
		LEFT JOIN SDOCS SD WITH (NOLOCK) ON SD.DOC_ID = X.MFR_DOC_ID
			LEFT JOIN MFR_SDOCS_PRIORITIES PRIO ON SD.PRIORITY_ID between PRIO.PRIORITY_ID and PRIO.PRIORITY_MAX
		LEFT JOIN SDOCS_MFR_CONTENTS C WITH (NOLOCK) ON C.CONTENT_ID = X.CONTENT_ID
		LEFT JOIN SDOCS_MFR_OPERS O WITH (NOLOCK) ON O.OPER_ID = X.OPER_ID
		LEFT JOIN PROJECTS_DURATIONS DUR1 ON DUR1.DURATION_ID = X.PLAN_DURATION_WK_ID
		LEFT JOIN PROJECTS_DURATIONS DUR2 ON DUR2.DURATION_ID = X.DURATION_WK_ID
		JOIN PROJECTS_DURATIONS DUR_H ON DUR_H.DURATION_ID = 2
	WHERE J.STATUS_ID BETWEEN 0 AND 99
		-- AND (
		-- 	X.OPER_ID IS NOT NULL -- ВСЕ ДЕТАЛЕ-ОПЕРАЦИИ СМЕННЫХ ЗАДАНИЙ
		-- 	OR X.OPER_NUMBER IS NULL -- ... + ДОПОЛНИТЕЛЬНЫЕ ОПЕРАЦИИ
		-- )
) V
GO
