IF OBJECT_ID('V_MFR_SDOCS_TRF') IS NOT NULL DROP VIEW V_MFR_SDOCS_TRF
GO
-- SELECT TOP 10 * FROM V_MFR_SDOCS_TRF
CREATE VIEW V_MFR_SDOCS_TRF
AS
SELECT 
	X.DOC_ID,
	X.EXTERN_ID,
	X.TYPE_ID,
	TYPE_NAME = TP.NAME,
	X.ACC_REGISTER_ID,
    ACC_REGISTER_NAME = acc.NAME,
    X.PRINCIPAL_DOGOVOR_ID,
	X.PLAN_ID,
	X.D_DOC,
	X.NUMBER,	
	X.STATUS_ID,
	STATUS_NAME = ST.NAME,
	X.SUBJECT_ID,
	SUBJECT_NAME = SUBJECTS.SHORT_NAME,
	SUBJECT_PRED_NAME = A.NAME,
	X.PLACE_ID,
	PLACE_NAME = PL.FULL_NAME,
	X.PLACE_TO_ID,
	PLACE_TO_NAME = PL2.FULL_NAME,
    X.VALUE_RUR,
	X.MOL_ID,
	X.MOL_TO_ID,
	X.EXECUTOR_ID,
	X.NOTE,
	X.CONTENT,
	X.ADD_DATE,
	X.ADD_MOL_ID,
	MOL_NAME = M1.NAME,
	MOL_TO_NAME = M2.NAME,
	ADD_MOL_NAME = M3.NAME,
	X.UPDATE_DATE,
	X.UPDATE_MOL_ID
FROM SDOCS X WITH(NOLOCK)
	LEFT JOIN ACCOUNTS_REGISTERS ACC ON ACC.ACC_REGISTER_ID = X.ACC_REGISTER_ID
    JOIN SDOCS_TYPES TP WITH(NOLOCK) ON TP.TYPE_ID = X.TYPE_ID
	LEFT JOIN SUBJECTS WITH(NOLOCK) ON SUBJECTS.SUBJECT_ID = X.SUBJECT_ID
		LEFT JOIN AGENTS A WITH(NOLOCK) ON A.AGENT_ID = SUBJECTS.PRED_ID
	LEFT JOIN MFR_PLACES PL WITH(NOLOCK) ON PL.PLACE_ID = X.PLACE_ID
	LEFT JOIN MFR_PLACES PL2 WITH(NOLOCK) ON PL2.PLACE_ID = X.PLACE_TO_ID
	LEFT JOIN SDOCS_STATUSES ST WITH(NOLOCK) ON ST.STATUS_ID = X.STATUS_ID
	LEFT JOIN MOLS AS M1 WITH(NOLOCK) ON M1.MOL_ID = X.MOL_ID
	LEFT JOIN MOLS AS M2 WITH(NOLOCK) ON M2.MOL_ID = X.MOL_TO_ID
	LEFT JOIN MOLS AS M3 WITH(NOLOCK) ON M3.MOL_ID = X.ADD_MOL_ID
WHERE CHARINDEX('TRF', TP.NOTE) > 0
GO

IF OBJECT_ID('MFR_SDOCS_TRF') IS NULL
	CREATE SYNONYM MFR_SDOCS_TRF FOR V_MFR_SDOCS_TRF
GO
