IF OBJECT_ID('V_MFR_R_PROVIDES') IS NOT NULL DROP VIEW V_MFR_R_PROVIDES
GO

-- SELECT TOP 10 * FROM V_MFR_R_PROVIDES
CREATE VIEW V_MFR_R_PROVIDES
AS
SELECT 
	CONTENT_ID = ID_MFR,
	INVOICE_ID = ID_INVOICE,
	INVOICE_D_DOC = X.D_INVOICE,
	INVOICE_D_DELIVERY = X.D_DELIVERY,
	INVOICE_D_DIFF = DATEDIFF(D, X.D_INVOICE, X.D_DELIVERY),
	INVOICE_NUMBER = D1.NUMBER,
	SHIP_ID = ID_SHIP,
	SHIP_D_DOC = X.D_SHIP,
	SHIP_NUMBER = D2.NUMBER,
	JOB_ID = ID_JOB,
	JOB_D_DOC = X.D_JOB,
	JOB_NUMBER = D3.NUMBER,
	Q_MFR = ISNULL(X.Q_MFR,0),
	Q_INVOICE = ISNULL(X.Q_INVOICE,0),
	Q_SHIP = ISNULL(X.Q_SHIP,0),
	Q_LZK = ISNULL(X.Q_LZK,0),
	Q_JOB = ISNULL(X.Q_JOB,0),
	X.UNIT_NAME
FROM (
	SELECT 
		ID_MFR, ID_ORDER, ID_INVOICE, ID_SHIP, ID_JOB,
		D_DELIVERY, D_MFR, D_ORDER, D_INVOICE, D_SHIP, D_JOB,
		UNIT_NAME,
		Q_MFR = SUM(Q_MFR),
		Q_SHIP = SUM(Q_SHIP),
		Q_INVOICE = SUM(Q_INVOICE),
		Q_LZK = SUM(Q_LZK),
		Q_JOB = SUM(Q_JOB)
	FROM MFR_R_PROVIDES
	GROUP BY 
		ID_MFR, ID_ORDER, ID_INVOICE, ID_SHIP, ID_JOB,
		D_DELIVERY, D_MFR, D_ORDER, D_INVOICE, D_SHIP, D_JOB,
		UNIT_NAME
	) X
	LEFT JOIN SDOCS D1 ON D1.DOC_ID = X.ID_INVOICE
	LEFT JOIN SDOCS D2 ON D2.DOC_ID = X.ID_SHIP
	LEFT JOIN SDOCS D3 ON D3.DOC_ID = X.ID_JOB
GO
