IF OBJECT_ID('V_MFR_WK_SHEETS') IS NOT NULL DROP VIEW V_MFR_WK_SHEETS
GO
CREATE VIEW V_MFR_WK_SHEETS
AS
SELECT 
	X.SUBJECT_ID,
	X.WK_SHEET_ID,
	X.STATUS_ID,
	X.PLACE_ID,
	SUBJECT_NAME = SUBJ.SHORT_NAME,
	STATUS_NAME = ST.NAME,
	PLACE_NAME = PL.NAME,
	X.D_DOC,
	X.WK_SHIFT,
	X.NUMBER,
	X.NOTE
FROM MFR_WK_SHEETS X
	LEFT JOIN SUBJECTS SUBJ ON SUBJ.SUBJECT_ID = X.SUBJECT_ID
	JOIN MFR_WK_SHEETS_STATUSES ST ON ST.STATUS_ID = X.STATUS_ID
	LEFT JOIN MFR_PLACES PL ON PL.PLACE_ID = X.PLACE_ID
GO
