IF OBJECT_ID('V_MFR_PLANS_QJOBS2') IS NOT NULL DROP VIEW V_MFR_PLANS_QJOBS2
GO
-- SELECT TOP 10 * FROM V_MFR_PLANS_QJOBS2 
CREATE VIEW V_MFR_PLANS_QJOBS2
AS
SELECT 
    ID = X.DETAIL_ID,
    X.*,
    NORM_COST = X.NORM_HOURS * X.RATE_PRICE,
    PLAN_COST = X.PLAN_HOURS * X.RATE_PRICE,
    FACT_COST = X.FACT_HOURS * X.RATE_PRICE,
    STATUS_NAME = ST.NAME,
    STATUS_CSS = ST.CSS,
    STATUS_STYLE = ST.STYLE
FROM MFR_PLANS_JOBS_QUEUES X WITH(NOLOCK)
    LEFT JOIN MFR_ITEMS_STATUSES ST ON ST.STATUS_ID = X.STATUS_ID
GO
