IF OBJECT_ID('V_MFR_OPERS_WORKS') IS NOT NULL DROP VIEW V_MFR_OPERS_WORKS
GO
-- SELECT TOP 10 * FROM V_MFR_OPERS_WORKS
CREATE VIEW V_MFR_OPERS_WORKS
AS
SELECT X.*,
	PLAN_HOURS = X.PLAN_DURATION_WK * DUR.FACTOR / DUR_H.FACTOR,
	FACT_HOURS =  X.DURATION_WK * DUR.FACTOR / DUR_H.FACTOR
FROM (
    SELECT 
        X.CONTENT_ID,
        X.OPER_ID,
        MFR_NUMBER = SD.NUMBER,
        PLACE_NAME = PL.NAME,
        JD.PLAN_JOB_ID,
        JOB_STATUS_ID = J.STATUS_ID,
        JOB_DATE = J.D_DOC,
        JOB_CLOSED = J.D_CLOSED,
        OPER_NUMBER = X.NUMBER,
        OPER_NAME = X.NAME,
        EXECUTOR_DATE = JE.D_DOC,
        EXECUTOR_NAME = MOLS.NAME,
        PLAN_Q = ISNULL(JE.PLAN_Q, JD.PLAN_Q),
        FACT_Q = ISNULL(JE.FACT_Q, JD.FACT_Q),
        PLAN_DURATION_WK = ISNULL(JE.PLAN_DURATION_WK, JD.PLAN_DURATION_WK),
        PLAN_DURATION_WK_ID = ISNULL(JE.PLAN_DURATION_WK_ID, JD.PLAN_DURATION_WK_ID),
        DURATION_WK = ISNULL(JE.DURATION_WK, JD.DURATION_WK)
    FROM SDOCS_MFR_OPERS X WITH (NOLOCK)
        JOIN MFR_PLACES PL ON PL.PLACE_ID = X.PLACE_ID
        JOIN SDOCS_MFR_CONTENTS C WITH (NOLOCK) ON C.CONTENT_ID = X.CONTENT_ID
        JOIN MFR_PLANS_JOBS_DETAILS JD WITH (NOLOCK) ON JD.OPER_ID = X.OPER_ID
            JOIN MFR_PLANS_JOBS J WITH (NOLOCK) ON J.PLAN_JOB_ID = JD.PLAN_JOB_ID
            LEFT JOIN MFR_PLANS_JOBS_EXECUTORS JE WITH(NOLOCK) ON JE.DETAIL_ID = JD.ID
                LEFT JOIN MOLS WITH(NOLOCK) ON MOLS.MOL_ID = JE.MOL_ID
            LEFT JOIN SDOCS SD WITH (NOLOCK) ON SD.DOC_ID = JD.MFR_DOC_ID
        JOIN PRODUCTS I WITH (NOLOCK) ON I.PRODUCT_ID = JD.ITEM_ID
    WHERE J.STATUS_ID >= 0
    ) X
    JOIN PROJECTS_DURATIONS DUR ON DUR.DURATION_ID = X.PLAN_DURATION_WK_ID
    JOIN PROJECTS_DURATIONS DUR_H ON DUR_H.DURATION_ID = 2

GO
