IF OBJECT_ID('V_MFR_PRINT_ITEMS_DIFFS') IS NOT NULL DROP VIEW V_MFR_PRINT_ITEMS_DIFFS
GO
-- SELECT TOP 10 * FROM V_MFR_PRINT_ITEMS_DIFFS
CREATE VIEW V_MFR_PRINT_ITEMS_DIFFS
AS
SELECT 
    MFR_DOC_ID,

    PLACE_NAME = PL.NAME,
    PLACE_NOTE = PL.NOTE,

    ST.STATUS_ID,
    STATUS_COMPLETED = CASE WHEN ST.STATUS_ID = 100 THEN 1 ELSE 0 END,
    STATUS_NAME = ST.NAME,
    STATUS_CSS = ST.CSS,
    STATUS_STYLE = ST.STYLE,

    ITEM_NAME = PI.NAME,
    X.OPER_NAME,

    DIFF_TYPE = SIGN(D_DIFF),
    X.D_TO_PLAN,
    X.D_DIFF,

    x.PLAN_Q,
    x.FACT_Q
FROM (
    SELECT 
        O.MFR_DOC_ID,
        O.OPER_ID,
        O.STATUS_ID,
        O.PLACE_ID,
        OPER_NAME = CONCAT('#', O.NUMBER, '-', O.NAME),
        C.ITEM_ID,
        O.D_TO_PLAN,
        D_DIFF = DATEDIFF(D, O.D_TO_PLAN, ISNULL(O.D_TO_FACT, CAST(GETDATE() AS DATE))),
        O.PLAN_Q, O.FACT_Q
    FROM SDOCS_MFR_OPERS O
        JOIN SDOCS_MFR_CONTENTS C ON C.CONTENT_ID = O.CONTENT_ID
    WHERE C.IS_BUY = 0
        and c.ITEM_TYPE_ID not in (select id from dbo.mfr_provides_excl_items(0))
    ) X
    JOIN MFR_PLACES PL ON PL.PLACE_ID = X.PLACE_ID
    JOIN PRODUCTS PI ON PI.PRODUCT_ID = X.ITEM_ID
    JOIN MFR_ITEMS_STATUSES ST ON ST.STATUS_ID = X.STATUS_ID
where X.D_DIFF != 0

GO
