IF OBJECT_ID('V_MFR_PLANS_RATES_GROUPS') IS NOT NULL DROP VIEW V_MFR_PLANS_RATES_GROUPS
GO
-- SELECT TOP 100 * FROM V_MFR_PLANS_RATES_GROUPS
CREATE VIEW V_MFR_PLANS_RATES_GROUPS
AS	

SELECT 
	PRODUCT_GROUP_ID = ATTR_ID,
	NAME 
FROM PRODMETA_ATTRS 
WHERE GROUP_KEY = 'MFRPLANPRODGRP'

GO
