IF OBJECT_ID('V_MFR_PLACES') IS NOT NULL DROP VIEW V_MFR_PLACES
GO
CREATE VIEW V_MFR_PLACES AS
	SELECT 
		X.SUBJECT_ID,
		SUBJECT_NAME = SUBJ.SHORT_NAME,
		X.PLACE_ID,
		X.NAME,
		X.WORK_TYPE_ID,
        X.WORK_HOURS,
		X.NOTE,
		X.ADD_DATE,
		X.ADD_MOL_ID,
		X.UPDATE_DATE,
		X.UPDATE_MOL_ID,
		X.IS_DELETED
	FROM MFR_PLACES X
		LEFT JOIN SUBJECTS SUBJ ON SUBJ.SUBJECT_ID = X.SUBJECT_ID
GO
