IF OBJECT_ID('V_MFR_R_PROVIDES_ALL') IS NOT NULL DROP VIEW V_MFR_R_PROVIDES_ALL
GO
-- SELECT TOP 10 * FROM V_MFR_R_PROVIDES_ALL
CREATE VIEW V_MFR_R_PROVIDES_ALL
AS
    SELECT 
        ACC_REGISTER_ID,
        MFR_DOC_ID,
        ITEM_ID,
        UNIT_NAME,
        ID_MFR,
        ID_ORDER,
        ID_INVOICE,
        ID_SHIP,
        ID_JOB,
        Q_MFR, Q_INVOICE, Q_SHIP, Q_LZK, Q_JOB, Q_RETURN,
        XSLICE
    FROM MFR_R_PROVIDES
    
    UNION ALL 

    SELECT 
        ACC_REGISTER_ID,
        MFR_DOC_ID,
        ITEM_ID,
        UNIT_NAME,
        ID_MFR,
        ID_ORDER,
        ID_INVOICE,
        ID_SHIP,
        ID_JOB,
        Q_MFR, Q_INVOICE, Q_SHIP, Q_LZK, Q_JOB, Q_RETURN,
        XSLICE
    FROM MFR_R_PROVIDES_ARCHIVE
    WHERE ARCHIVE = 1
GO