IF OBJECT_ID('V_MFR_PDM_REF') IS NOT NULL DROP VIEW V_MFR_PDM_REF
GO
-- SELECT TOP 100 * FROM V_MFR_PDM_REF
CREATE VIEW V_MFR_PDM_REF
AS
SELECT 
	X.PDM_ID,
	NAME = CONCAT(P.NAME, CASE WHEN X.VERSION_NUMBER IS NOT NULL THEN ' V.' END, X.VERSION_NUMBER),
	X.ITEM_ID
FROM MFR_PDMS X
	JOIN PRODUCTS P ON P.PRODUCT_ID = X.ITEM_ID
WHERE X.IS_DELETED = 0
GO
