IF OBJECT_ID('V_MFR_WK_SHEETS_DETAILS') IS NOT NULL DROP VIEW V_MFR_WK_SHEETS_DETAILS
GO
-- SELECT TOP 100 * FROM V_MFR_WK_SHEETS_DETAILS
CREATE VIEW V_MFR_WK_SHEETS_DETAILS
AS
	SELECT 
		X.ID,
        W.WK_SHEET_ID,
		WK_SHEET_NUMBER = W.NUMBER,
        W.STATUS_ID,
		W.PLACE_ID,
		PLACE_NAME = PL.NAME,
		PLACE_NOTE = PL.NOTE,
		W.D_DOC,
		WK_SHIFT = ISNULL(W.WK_SHIFT, '1'),
		X.MOL_ID,
		MOL_NAME = CONCAT(M.NAME, CASE WHEN X.HAS_CHILDS = 1 THEN ' бригадир' END),
        MOL_POST_NAME = PS.NAME,
		WK_HOURS = ISNULL(X.BRIG_WK_HOURS, X.WK_HOURS),
        X.WK_KTU,
        X.WK_K_INC,
		X.WK_KTD,
		X.PLAN_HOURS,
		X.FACT_HOURS,
        X.WK_COMPLETION,
        WK_COMPLETION_ROWS = CASE WHEN 1.00 * X.WK_EXEC_ROWS_COMPLETED / NULLIF(X.WK_EXEC_ROWS, 0) >= 1.00 THEN 1 ELSE 1.00 * X.WK_EXEC_ROWS_COMPLETED / NULLIF(X.WK_EXEC_ROWS, 0) END,
        X.WK_EXEC_ROWS,
        X.WK_EXEC_ROWS_COMPLETED,
        WK_EXECUTORS = ISNULL(X.BRIG_EXECUTORS, 1),
        X.NOTE
	FROM MFR_WK_SHEETS_DETAILS X WITH(NOLOCK)
		JOIN MFR_WK_SHEETS W WITH(NOLOCK) ON W.WK_SHEET_ID = X.WK_SHEET_ID
			JOIN MFR_PLACES PL WITH(NOLOCK) ON PL.PLACE_ID = W.PLACE_ID
		JOIN MOLS M WITH(NOLOCK) ON M.MOL_ID = X.MOL_ID
        LEFT JOIN MOLS_POSTS PS ON PS.POST_ID = X.WK_POST_ID
    WHERE X.WK_HOURS > 0
        AND X.PARENT_ID IS NULL
        -- AND X.WK_EXEC_ROWS > 0
GO
