IF OBJECT_ID('V_MFR_R_PLANS_JOBS_PRODUCTS') IS NOT NULL DROP VIEW V_MFR_R_PLANS_JOBS_PRODUCTS
GO
-- SELECT TOP 100 * FROM V_MFR_R_PLANS_JOBS_PRODUCTS
CREATE VIEW V_MFR_R_PLANS_JOBS_PRODUCTS
AS
SELECT 
	PLAN_ID,
	MFR_DOC_ID,
	CONTENT_ID,
	PRODUCT_ID,
	ITEM_ID,
	JOB_ID,
	JOB_DETAIL_ID,
	JOB_DATE,	
	CLOSED_DATE,
	PLAN_Q,
	FACT_Q,
	CLOSED_Q
FROM (
    SELECT 
        X.PLAN_ID,
        X.MFR_DOC_ID,
        X.CONTENT_ID,
        C.PRODUCT_ID,
        X.ITEM_ID,
        X.JOB_ID,
        X.JOB_DETAIL_ID,
        X.JOB_DATE,	
        CLOSED_DATE = CASE WHEN X.JOB_STATUS_ID = 100 THEN X.JOB_DATE END,
        X.PLAN_Q,
        X.FACT_Q,
        CLOSED_Q = CASE WHEN X.JOB_STATUS_ID = 100 THEN X.FACT_Q END,
        IS_FINAL = CASE WHEN D.IS_PRODUCT = 1 AND O.IS_LAST = 1 THEN 1 ELSE 0 END
    FROM MFR_R_PLANS_JOBS_ITEMS X WITH(NOLOCK)
        JOIN SDOCS_MFR_CONTENTS C WITH(NOLOCK) ON C.CONTENT_ID = X.CONTENT_ID
            JOIN MFR_DRAFTS D WITH(NOLOCK) ON D.DRAFT_ID = C.DRAFT_ID
        JOIN SDOCS_MFR_OPERS O WITH(NOLOCK) ON O.OPER_ID = X.OPER_ID
    ) X
WHERE IS_FINAL = 1

UNION ALL
SELECT 
	PLAN_ID,
	MFR_DOC_ID,
	CONTENT_ID,
	PRODUCT_ID,
	ITEM_ID,
	JOB_ID,
	JOB_DETAIL_ID,
	JOB_DATE,	
	CLOSED_DATE,
	PLAN_Q,
	FACT_Q,
	CLOSED_Q
FROM (
    SELECT 
        X.PLAN_ID,
        X.MFR_DOC_ID,
        X.CONTENT_ID,
        C.PRODUCT_ID,
        X.ITEM_ID,
        X.JOB_ID,
        X.JOB_DETAIL_ID,
        X.JOB_DATE,	
        CLOSED_DATE = CASE WHEN X.JOB_STATUS_ID = 100 THEN X.JOB_DATE END,
        X.PLAN_Q,
        X.FACT_Q,
        CLOSED_Q = CASE WHEN X.JOB_STATUS_ID = 100 THEN X.FACT_Q END,
        IS_FINAL = CASE WHEN D.IS_PRODUCT = 1 AND O.IS_LAST = 1 THEN 1 ELSE 0 END
    FROM MFR_R_PLANS_JOBS_ITEMS_ARCHIVE X WITH(NOLOCK)
        JOIN SDOCS_MFR_CONTENTS C WITH(NOLOCK) ON C.CONTENT_ID = X.CONTENT_ID
            JOIN MFR_DRAFTS D WITH(NOLOCK) ON D.DRAFT_ID = C.DRAFT_ID
        JOIN SDOCS_MFR_OPERS O WITH(NOLOCK) ON O.OPER_ID = X.OPER_ID
    WHERE X.ARCHIVE = 1
    ) X
WHERE IS_FINAL = 1

GO
