IF OBJECT_ID('V_MFR_FIFO_OPERS') IS NOT NULL DROP VIEW V_MFR_FIFO_OPERS
GO
-- SELECT TOP 10 * FROM V_MFR_FIFO_OPERS
CREATE VIEW V_MFR_FIFO_OPERS
AS
SELECT
	C.PLAN_ID,
    X.CONTENT_ID,
    X.OPER_ID,
	C.ITEM_ID,
	OPER_NUMBER = X.NUMBER,
	X.MFR_DOC_ID,
	SORT_NUMBER = MFR.PRIORITY_FINAL,
	D_FROM = ISNULL(X.D_FROM_PLAN, '2100-12-31'),
	X.WORK_TYPE_ID,
	X.PLAN_Q,
	C.UNIT_NAME,
	C.ITEM_PRICE0	
FROM SDOCS_MFR_OPERS X WITH (NOLOCK)
	JOIN SDOCS_MFR_CONTENTS C WITH (NOLOCK) ON C.CONTENT_ID = X.CONTENT_ID
    JOIN MFR_SDOCS MFR WITH (NOLOCK) ON MFR.DOC_ID = X.MFR_DOC_ID
WHERE MFR.STATUS_ID >= 0
    AND MFR.PLAN_ID IS NOT NULL
    AND C.IS_BUY = 0
    AND ISNULL(X.WORK_TYPE_ID,1) != 2
GO
