IF OBJECT_ID('V_MFR_R_MILESTONES') IS NOT NULL DROP VIEW V_MFR_R_MILESTONES
GO
-- SELECT TOP 100 * FROM V_MFR_R_MILESTONES
CREATE VIEW V_MFR_R_MILESTONES
AS

SELECT
	X.VERSION_ID,
	X.MFR_DOC_ID,
	MFR_NUMBER = MFR.NUMBER,
	MFR.SUBJECT_NAME,
	MFR.D_DOC,
	MFR.AGENT_NAME,
	MFR.D_DELIVERY,
	D_ISSUE_PLAN = X.MFR_D_PLAN,
	MFR.D_ISSUE_FORECAST,
	X.PRODUCT_ID,
	PRODUCT_NAME = P1.NAME,
	CONTENT_ID = 0, -- X.CONTENT_ID,
	ITEM_NAME = '-', -- ITEM_NAME = P2.NAME,
	UNIT_NAME = '-', -- UNIT_NAME = U.NAME,
	X.MILESTONE_ID,
	MILESTONE_NAME = MS.NAME,
	ISSUE_STATUS = '-', -- X.ISSUE_STATUS,
	D_PLAN,
	D_FACT = CASE WHEN PLAN_Q <= FACT_Q THEN D_LAST END,
	X.PLAN_Q,
	X.FACT_Q
FROM (
	SELECT 
		VERSION_ID,
		MFR_DOC_ID,
		PRODUCT_ID,
		MILESTONE_ID,
		MFR_D_PLAN,
		D_PLAN,
		D_LAST = MAX(D_FACT),
		PLAN_Q = SUM(PLAN_Q),
		FACT_Q = SUM(FACT_Q)
	FROM MFR_R_MILESTONES
	GROUP BY VERSION_ID, MFR_DOC_ID, PRODUCT_ID, MILESTONE_ID, MFR_D_PLAN, D_PLAN
	) X
	JOIN MFR_SDOCS MFR ON MFR.DOC_ID = X.MFR_DOC_ID
	JOIN PRODUCTS P1 ON P1.PRODUCT_ID = X.PRODUCT_ID
	JOIN MFR_MILESTONES MS ON MS.MILESTONE_ID = X.MILESTONE_ID

GO