IF OBJECT_ID('V_MFR_PLANS_JOBS_DETAILS') IS NOT NULL DROP VIEW V_MFR_PLANS_JOBS_DETAILS
GO
-- SELECT TOP 10 * FROM V_MFR_PLANS_JOBS_DETAILS
CREATE VIEW V_MFR_PLANS_JOBS_DETAILS
AS
SELECT 
	X.ID,	
	J.PLAN_ID,
	JOB_STATUS_ID = J.STATUS_ID,
	X.PLAN_JOB_ID,
    JOB_D_DOC = J.D_DOC,
    JOB_D_CLOSED = J.D_CLOSED,
	X.MFR_DOC_ID,
	MFR_NUMBER = SD.NUMBER,
	MFR_PRIORITY = SD.PRIORITY_FINAL,
	X.PRODUCT_ID,
	X.PARENT_ITEM_ID,
	X.CONTENT_ID,
	X.ITEM_ID,
	ITEM_NAME = I.NAME,
	X.OPER_ID,
	X.OPER_NUMBER,	
	X.OPER_NAME,
	OPER_KEY = ISNULL(X.OPER_KEY, CONCAT(x.OPER_NUMBER, x.OPER_NAME)),
	OPER_D_FROM = O.D_FROM_PLAN,
	OPER_D_TO = O.D_TO_PLAN,
	PRODUCT_NAME = P.NAME,
	PARENT_ITEM_NAME = IP.NAME,
	DR.DRAFT_ID,
	DRAFT_NUMBER = DR.NUMBER,
	DR.PROP_SIZE,
	O.PLACE_ID,
	PLACE_NAME = PL1.NAME,
	PREV_PLACE_NAME = PL2.NAME,
	NEXT_PLACE_NAME = PL3.NAME,
	X.PLAN_Q,
	X.FACT_Q,
	X.FACT_DEFECT_Q,
	X.NORM_DURATION,
	X.NORM_DURATION_WK,
	NORM_DURATION_WK_ID = ISNULL(X.PLAN_DURATION_WK_ID, 2),
	X.PLAN_DURATION_WK,
	PLAN_DURATION_WK_ID = ISNULL(X.PLAN_DURATION_WK_ID, 2),
	X.DURATION_WK,
	DURATION_WK_ID = ISNULL(X.DURATION_WK_ID, 2),
	X.RESOURCE_ID,
	RESOURCE_NAME = RS.NAME,
	X.VALUE_NDS,
	X.VALUE_PURE,
	X.VALUE_RUR,
	X.COUNT_EXECUTORS,
	X.COUNT_EQUIPMENTS,
	X.PROBLEM_ID,
	PROBLEM_NAME = PROBLEM.NAME,
	X.NOTE,
	X.ADD_MOL_ID, X.ADD_DATE, X.UPDATE_MOL_ID, X.UPDATE_DATE
FROM MFR_PLANS_JOBS_DETAILS X WITH (NOLOCK)
	JOIN MFR_PLANS_JOBS J WITH (NOLOCK) ON J.PLAN_JOB_ID = X.PLAN_JOB_ID
	LEFT JOIN SDOCS SD WITH (NOLOCK) ON SD.DOC_ID = X.MFR_DOC_ID
	LEFT JOIN PRODUCTS P WITH (NOLOCK) ON P.PRODUCT_ID = X.PRODUCT_ID
	LEFT JOIN PRODUCTS I WITH (NOLOCK) ON I.PRODUCT_ID = X.ITEM_ID
	LEFT JOIN SDOCS_MFR_CONTENTS C WITH (NOLOCK) ON C.CONTENT_ID = X.CONTENT_ID
		LEFT JOIN MFR_DRAFTS DR WITH (NOLOCK) ON DR.DRAFT_ID = C.DRAFT_ID
	LEFT JOIN SDOCS_MFR_OPERS O WITH (NOLOCK) ON O.OPER_ID = x.OPER_ID
		LEFT JOIN MFR_PLACES PL1 ON PL1.PLACE_ID = O.PLACE_ID
	LEFT JOIN MFR_PLACES PL2 ON PL2.PLACE_ID = X.PREV_PLACE_ID
	LEFT JOIN MFR_PLACES PL3 ON PL3.PLACE_ID = X.NEXT_PLACE_ID
	LEFT JOIN PRODUCTS IP WITH (NOLOCK) ON IP.PRODUCT_ID = X.PARENT_ITEM_ID
	LEFT JOIN MFR_PLANS_JOBS_PROBLEMS_TYPES PROBLEM WITH (NOLOCK) ON PROBLEM.PROBLEM_ID = X.PROBLEM_ID
	LEFT JOIN MFR_RESOURCES RS WITH (NOLOCK) ON RS.RESOURCE_ID = X.RESOURCE_ID
WHERE J.STATUS_ID >= 0
GO
