IF OBJECT_ID('V_MFR_EQUIPMENTS') IS NOT NULL DROP VIEW V_MFR_EQUIPMENTS
GO
CREATE VIEW V_MFR_EQUIPMENTS
AS
SELECT 
	X.EQUIPMENT_ID,	
	X.SUBJECT_ID,	
	SUBJECT_NAME = SUBJ.SHORT_NAME,
	X.STATUS_ID,
	STATUS_NAME = S.NAME,
	X.D_DOC,
	X.D_RELEASE,
	X.NUMBER,
	X.NAME,
	X.MODEL,
	X.SPECIFICATION,
	X.PROP_POWER,
	X.NOTE,
	x.CONTENT,
	X.ADD_MOL_ID,
	X.ADD_DATE,
	X.UPDATE_MOL_ID,
	X.UPDATE_DATE	
FROM MFR_EQUIPMENTS X
	JOIN MFR_EQUIPMENTS_STATUSES S ON S.STATUS_ID = X.STATUS_ID
	JOIN SUBJECTS SUBJ ON SUBJ.SUBJECT_ID = X.SUBJECT_ID
GO
