IF OBJECT_ID('V_MFR_PLANS_RATES') IS NOT NULL DROP VIEW V_MFR_PLANS_RATES
GO
-- SELECT TOP 100 * FROM V_MFR_PLANS_RATES
CREATE VIEW V_MFR_PLANS_RATES
AS	
SELECT 
	R.ID,
	R.D_DOC,
	R.PRODUCT_GROUP_ID,
	PRODUCT_GROUP_NAME = G.NAME,
	R.LIMIT_Q,
	R.NOTE,
	R.ADD_DATE,
	R.ADD_MOL_ID,
	R.UPDATE_DATE,
	R.UPDATE_MOL_ID,
	R.IS_DELETED
FROM MFR_PLANS_RATES R
	JOIN V_MFR_PLANS_RATES_GROUPS G ON G.PRODUCT_GROUP_ID = R.PRODUCT_GROUP_ID
WHERE R.IS_DELETED = 0

GO

