IF OBJECT_ID('V_MFR_DRAFTS') IS NOT NULL DROP VIEW V_MFR_DRAFTS
GO
-- SELECT TOP 100 * FROM V_MFR_DRAFTS
CREATE VIEW V_MFR_DRAFTS
AS
SELECT 
	X.DRAFT_ID,
	X.MFR_DOC_ID,
	MFR_NUMBER = MFR.NUMBER,
	P.NAME,
	X.ITEM_ID
FROM SDOCS_MFR_DRAFTS X
	JOIN MFR_SDOCS MFR ON MFR.DOC_ID = X.MFR_DOC_ID
	JOIN PRODUCTS P ON P.PRODUCT_ID = X.ITEM_ID
WHERE X.IS_DELETED = 0
	AND X.IS_BUY = 0
GO
