IF OBJECT_ID('V_MOLS_BIRTHDAYS') IS NOT NULL DROP VIEW V_MOLS_BIRTHDAYS
GO
CREATE VIEW V_MOLS_BIRTHDAYS
AS
SELECT
	M.MOL_ID,
	DAY = CONVERT(VARCHAR(5), DATEADD(YEAR, - DATEDIFF(YEAR, GETDATE(), M.BIRTHDAY), M.BIRTHDAY), 104),
	MOL_SHORT = M.NAME,
	MOL_NAME = ISNULL(M.SURNAME,'') + ' ' + ISNULL(M.NAME1,'') + ' '	 + ISNULL(M.NAME2,''),
	M.SURNAME,
	M.NAME1,
	BRANCH_NAME = BR.NAME,
	BIRTHDAY = DATEADD(YEAR, - DATEDIFF(YEAR, GETDATE(), M.BIRTHDAY), M.BIRTHDAY),
	DATE_START = DATEADD(DAY, -1, DATEADD(YEAR, - DATEDIFF(YEAR, GETDATE(), M.BIRTHDAY), M.BIRTHDAY)),
	DATE_END = DATEADD(DAY, 1, DATEADD(YEAR, - DATEDIFF(YEAR, GETDATE(), M.BIRTHDAY), M.BIRTHDAY)),
	M.EMAIL
FROM MOLS M
	LEFT JOIN BRANCHES BR ON BR.BRANCH_ID = M.BRANCH_ID	
WHERE BIRTHDAY IS NOT NULL AND IS_WORKING = 1 AND STATUS_ID NOT IN (-2,2)

GO
