IF OBJECT_ID('V_OBJS_SHARES') IS NOT NULL DROP VIEW V_OBJS_SHARES
GO
CREATE VIEW V_OBJS_SHARES
AS
SELECT 
  OBJS.OBJ_UID,
  OBJS.OWNER_TYPE,
  OBJS.OWNER_ID,
  SH.MOL_ID,
  SH.A_READ,
  SH.A_UPDATE,
  SH.A_ACCESS
FROM OBJS_SHARES SH
  JOIN OBJS ON OBJS.OBJ_UID = SH.OBJ_UID
GO
