IF OBJECT_ID('V_PAYORDERS') IS NOT NULL DROP VIEW V_PAYORDERS
GO
-- SELECT TOP 100 * FROM V_PAYORDERS
CREATE VIEW V_PAYORDERS AS
	SELECT
		X.PAYORDER_ID
		, X.PARENT_ID
		, X.SUBJECT_ID
		, SUBJECT_NAME = SUBJ.NAME
		, SUBJECT_SHORT_NAME = SUBJ.SHORT_NAME
		, X.BRANCH_ID
		, BRANCH_NAME = BR.NAME
		, TP.TYPE_ID
		, TYPE_NAME = TP.NAME
		, S.STATUS_ID
		, STATUS_NAME = S.NAME
		, D_DOC = ISNULL(X.D_PAY_PLAN, X.D_ADD)
		, X.NUMBER
		, X.PROJECTS_NAME
		, X.RECIPIENT_ID
		, RECIPIENT_NAME = ISNULL(A.NAME, A2.NAME)
		, X.VALUE_CCY
		, X.PAID_CCY
		, X.REMAIN_CCY
		, X.MOL_ID
		, CHIEF_ID = M.CHIEF_ID
		, NOTE = CONCAT(X.NUMBER, ' ', X.NOTE)
		, X.CONTENT
		, X.HAS_FILES
		, X.HAS_CHILDS
		, X.IS_DELETED
	FROM PAYORDERS X
		JOIN PAYORDERS_TYPES TP ON TP.TYPE_ID = X.TYPE_ID
		JOIN MOLS M ON M.MOL_ID = X.MOL_ID
		LEFT JOIN SUBJECTS SUBJ ON SUBJ.SUBJECT_ID = X.SUBJECT_ID
		LEFT JOIN BRANCHES BR ON BR.BRANCH_ID = X.BRANCH_ID
		LEFT JOIN AGENTS A ON A.AGENT_ID = X.RECIPIENT_ID
		LEFT JOIN AGENTS A2 ON A2.AGENT_ID = X.AGENT_ID
		LEFT JOIN PAYORDERS_STATUSES S ON S.STATUS_ID = X.STATUS_ID			
GO