IF OBJECT_ID('V_PRODUCTS_GROUPS') IS NOT NULL DROP VIEW V_PRODUCTS_GROUPS
GO
-- SELECT * FROM V_PRODUCTS_GROUPS
CREATE VIEW V_PRODUCTS_GROUPS
AS
SELECT PRODUCT_ID, NAME = ISNULL(PA.ATTR_VALUE, '-')
FROM PRODUCTS_ATTRS PA
	JOIN (
		SELECT TOP 1 ATTR_ID FROM PRODMETA_ATTRS
		WHERE CODE = 'материал.ГруппаНаименование'
	) A ON A.ATTR_ID = PA.ATTR_ID
GO
