IF OBJECT_ID('V_PRODUCTS_MANAGERS') IS NOT NULL DROP VIEW V_PRODUCTS_MANAGERS
GO
-- SELECT TOP 10 * FROM V_PRODUCTS_MANAGERS
CREATE VIEW V_PRODUCTS_MANAGERS
AS
SELECT PRODUCT_ID, MOLS.MOL_ID, NAME = MOLS.NAME
FROM PRODUCTS_ATTRS PA
	JOIN MOLS ON MOLS.MOL_ID = PA.ATTR_VALUE_ID
	JOIN (
		SELECT TOP 1 ATTR_ID FROM PRODMETA_ATTRS
		WHERE CODE = 'ЗАКУПКА.КОДМЕНЕДЖЕРА'
	) A ON A.ATTR_ID = PA.ATTR_ID
GO
