IF OBJECT_ID('V_PRODUCTS_SUBGROUPS') IS NOT NULL DROP VIEW V_PRODUCTS_SUBGROUPS
GO
-- SELECT * FROM V_PRODUCTS_SUBGROUPS
CREATE VIEW V_PRODUCTS_SUBGROUPS
AS
SELECT PRODUCT_ID, NAME = ISNULL(PA.ATTR_VALUE, '-')
FROM PRODUCTS_ATTRS PA
	JOIN (
		SELECT TOP 1 ATTR_ID FROM PRODMETA_ATTRS
		WHERE CODE = 'материал.ПодгруппаНаименование'
	) A ON A.ATTR_ID = PA.ATTR_ID
GO
