IF OBJECT_ID('V_SDOCS_STOCKS') IS NOT NULL DROP VIEW V_SDOCS_STOCKS
GO
CREATE VIEW V_SDOCS_STOCKS AS
	SELECT 
		X.SUBJECT_ID,
		SUBJECT_NAME = SUBJ.SHORT_NAME,
		X.STOCK_ID,
		X.NAME,
		X.NOTE,
		X.ADD_DATE,
		X.ADD_MOL_ID,
		X.UPDATE_DATE,
		X.UPDATE_MOL_ID,
		X.IS_DELETED
	FROM SDOCS_STOCKS X
		LEFT JOIN SUBJECTS SUBJ ON SUBJ.SUBJECT_ID = X.SUBJECT_ID
GO
-- SELECT * FROM V_SDOCS_STOCKS

IF OBJECT_ID('SDOCS_STOCKS_REFS') IS NOT NULL DROP VIEW SDOCS_STOCKS_REFS
GO
CREATE VIEW SDOCS_STOCKS_REFS AS
    SELECT STOCK_ID, NAME FROM SDOCS_STOCKS
GO
