IF OBJECT_ID('V_SDOCS') IS NOT NULL DROP VIEW V_SDOCS
GO
-- SELECT TOP 10 * FROM V_SDOCS
CREATE VIEW V_SDOCS
AS
SELECT
    X.DOC_ID,
    X.ACC_REGISTER_ID,
    X.D_DOC,
    X.NUMBER,
    X.SUBJECT_ID,
    SUBJECT_NAME = SUBJECTS.SHORT_NAME,
    X.TYPE_ID,
    TYPE_NAME = TYPES.NAME,
    X.STATUS_ID,
    STATUS_NAME = STATUSES.NAME,
    STOCK_NAME = STOCKS.NAME,
    AGENT_NAME = AGENTS.NAME,
    MOL_NAME = MOLS.NAME,
    X.ADD_MOL_ID,
    ADD_MOL_NAME = M2.NAME,
    X.VALUE_CCY,
    X.CCY_ID,
    X.NOTE,
    X.CONTENT
FROM SDOCS X
    JOIN SDOCS_TYPES TYPES ON TYPES.TYPE_ID = X.TYPE_ID
    JOIN SDOCS_STATUSES STATUSES ON STATUSES.STATUS_ID = X.STATUS_ID
    LEFT JOIN SUBJECTS ON SUBJECTS.SUBJECT_ID = X.SUBJECT_ID
    LEFT JOIN SDOCS_STOCKS STOCKS ON STOCKS.STOCK_ID = X.STOCK_ID
    LEFT JOIN AGENTS ON AGENTS.AGENT_ID = X.AGENT_ID
    LEFT JOIN MOLS ON MOLS.MOL_ID = X.MOL_ID 
    LEFT JOIN MOLS M2 ON M2.MOL_ID = X.ADD_MOL_ID 
WHERE X.TYPE_ID NOT IN (5,10,11)
GO
