IF OBJECT_ID('V_SDOCS_MFR_CONTENTS') IS NOT NULL DROP VIEW V_SDOCS_MFR_CONTENTS
GO
-- SELECT TOP 10 * FROM V_SDOCS_MFR_CONTENTS
CREATE VIEW V_SDOCS_MFR_CONTENTS
AS
SELECT 
	X.CONTENT_ID,
	CONTENT_HID = concat('#', X.CONTENT_ID), -- при выгрузке в Excel
	X.CHILD_ID,
	X.PLAN_ID,
	PLAN_NUMBER = PL.NUMBER,
	PLAN_STATUS_ID = PL.STATUS_ID,
	X.MFR_DOC_ID,
	MFR_NUMBER = D.NUMBER,
	MFR_PRIORITY = D.PRIORITY_FINAL,
    MFR_PRIORITY_CSS = PRIO.CSS,
	MFR_STATUS_ID = D.STATUS_ID,
    MFR_EXT_TYPE_ID = D.EXT_TYPE_ID,
	X.PLACE_ID,
	PLACE_NAME = PLC.NAME,
	X.NAME,
	X.PRODUCT_ID,
	PRODUCT_NAME = P.NAME,
	X.ITEM_ID,
	X.ITEM_TYPE_ID,
	ITEM_TYPE_NAME = IT.NAME,
	ITEM_GROUP_NAME = PG.NAME,
	ITEM_SUBGROUP_NAME = PG2.NAME,
	ITEM_NAME = X.NAME,
	D_DOC = X.D_DOC,
	DR.PDM_ID,
	X.DRAFT_ID,
	DR.PROP_WEIGHT,
	DR.PROP_SIZE,
	X.Q_BRUTTO_PRODUCT,	
	x.Q_PROVIDED,
	x.Q_PROVIDED_MAX,
	K_PROVIDED = ROUND(X.Q_PROVIDED / NULLIF(X.Q_BRUTTO_PRODUCT,0), 3),
	X.UNIT_NAME,
	X.ITEM_VALUE0,
	X.STATUS_ID,
	STATUS_NAME = S.NAME,
	STATUS_CSS = S.CSS,
	STATUS_STYLE = S.STYLE,
	X.IS_BUY,
	X.WORK_TYPE_1,
	X.WORK_TYPE_2,
	X.WORK_TYPE_3,
	X.IS_MANUAL_PROGRESS,
	X.IS_MILESTONE,
	X.IS_SWAP,
	X.OPERS_WK_HOURS,
	X.OPERS_COUNT,
	X.OPERS_DAYS,
	X.OPERS_FROM,
	X.OPERS_FROM_PLAN,
	X.OPERS_FROM_PREDICT,
	X.OPERS_TO,
	X.OPERS_TO_PLAN,
	X.OPERS_TO_PREDICT,
	X.OPERS_FACT_Q,	
	X.D_AFTER,
	X.D_BEFORE,
	X.DURATION_BUFFER,
	X.DURATION_BUFFER_PREDICT,
	SUPPLIER_NAME = AG.NAME,
	MANAGER_NAME = M.NAME,
	X.CANCEL_REASON_ID,
	CANCEL_REASON = CNC.NAME,
	CANCEL_NOTE = X.CANCEL_NOTE,
	X.TALK_ID,
	X.LAST_TASK_ID,
	X.HAS_CHILDS
FROM SDOCS_MFR_CONTENTS X WITH(NOLOCK)
	JOIN MFR_ITEMS_STATUSES S ON S.STATUS_ID = X.STATUS_ID	
	JOIN SDOCS D WITH(NOLOCK) ON D.DOC_ID = X.MFR_DOC_ID
        LEFT JOIN MFR_SDOCS_PRIORITIES PRIO WITH(NOLOCK) ON D.PRIORITY_ID BETWEEN PRIO.PRIORITY_ID AND PRIO.PRIORITY_MAX
	JOIN PRODUCTS P WITH(NOLOCK) ON P.PRODUCT_ID = X.PRODUCT_ID
	LEFT JOIN MFR_PLANS PL WITH(NOLOCK) ON PL.PLAN_ID = X.PLAN_ID
	JOIN MFR_DRAFTS DR WITH(NOLOCK) ON DR.DRAFT_ID = X.DRAFT_ID
	LEFT JOIN V_PRODUCTS_GROUPS PG WITH(NOLOCK) ON PG.PRODUCT_ID = X.ITEM_ID
	LEFT JOIN V_PRODUCTS_SUBGROUPS PG2 WITH(NOLOCK) ON PG2.PRODUCT_ID = X.ITEM_ID
	LEFT JOIN MFR_PLACES PLC WITH(NOLOCK) ON PLC.PLACE_ID = X.PLACE_ID
	LEFT JOIN MFR_ITEMS_TYPES IT WITH(NOLOCK) ON IT.TYPE_ID = X.ITEM_TYPE_ID		
	LEFT JOIN AGENTS AG WITH(NOLOCK) ON AG.AGENT_ID = X.SUPPLIER_ID
	LEFT JOIN MOLS M WITH(NOLOCK) ON M.MOL_ID = X.MANAGER_ID
	LEFT JOIN SDOCS_MFR_CONTENTS_CANCELREASONS CNC ON CNC.CANCEL_REASON_ID = X.CANCEL_REASON_ID
GO
