IF OBJECT_ID('V_SDOCS_R_STOCKS_TURNS_ADDRS') IS NOT NULL DROP VIEW V_SDOCS_R_STOCKS_TURNS_ADDRS
GO
-- SELECT * FROM V_SDOCS_R_STOCKS_TURNS_ADDRS
CREATE VIEW V_SDOCS_R_STOCKS_TURNS_ADDRS
AS

SELECT 
    X.MOL_ID,
    X.PRODUCT_ID, 
    ACC_REGISTER_ID = ISNULL(X.ACC_REGISTER_ID, 0),
    PRINCIPAL_DOGOVOR_ID = ISNULL(X.PRINCIPAL_DOGOVOR_ID, 0),
    STOCK_ID = ISNULL(X.STOCK_ID, 0),
    ADDR_ID = ISNULL(X.ADDR_ID, 0),
    ADDR_NAME = ISNULL(ADR.NAME, '#адрес'), 
    UNIT_NAME = U.NAME, 
    Q_START, Q_INPUT, Q_OUTPUT, Q_END
FROM (
    SELECT 
        MOL_ID, ACC_REGISTER_ID, PRINCIPAL_DOGOVOR_ID, PRODUCT_ID, STOCK_ID, ADDR_ID, UNIT_ID,
        Q_START = SUM(Q_START),
        Q_INPUT = SUM(Q_INPUT),
        Q_OUTPUT = SUM(Q_OUTPUT),
        Q_END = SUM(Q_END)
    FROM SDOCS_R_STOCKS_TURNS
    GROUP BY MOL_ID, ACC_REGISTER_ID, PRINCIPAL_DOGOVOR_ID, PRODUCT_ID, STOCK_ID, ADDR_ID, UNIT_ID
    ) X
    LEFT JOIN SDOCS_STOCKS_ADDRS ADR ON ADR.ADDR_ID = X.ADDR_ID
    JOIN PRODUCTS_UNITS U ON U.UNIT_ID = X.UNIT_ID
WHERE 
    ABS(Q_END) > 1E-4 OR Q_INPUT > 1E-4 OR Q_OUTPUT > 1E-4

GO
