IF OBJECT_ID('V_SDOCS_MFR_MATERIALS') IS NOT NULL DROP VIEW V_SDOCS_MFR_MATERIALS
GO
CREATE VIEW V_SDOCS_MFR_MATERIALS
AS
SELECT
	X.PLAN_ID,
	X.MFR_DOC_ID,	
	IT.GROUP_ID,
	ITEM_CONTENT_ID = XX.CONTENT_ID,
	ITEM_ID = XX.ITEM_ID,
	ITEM_NAME = P2.NAME,
	MATERIAL_TYPE_NAME = IT.NAME,
	MATERIAL_CONTENT_ID = X.CONTENT_ID,
	MATERIAL_ITEM_ID = X.ITEM_ID,
	MATERIAL_NAME = P.NAME,
	X.STATUS_ID,
	X.Q_BRUTTO_PRODUCT,
	X.Q_NETTO_PRODUCT,
	X.W_BRUTTO,
	X.W_NETTO,
	X.UNIT_NAME,
	X.CANCEL_REASON_ID,
	X.CANCEL_NOTE
FROM SDOCS_MFR_CONTENTS X
	JOIN SDOCS_MFR_CONTENTS XX ON XX.MFR_DOC_ID = X.MFR_DOC_ID AND XX.PRODUCT_ID = X.PRODUCT_ID AND XX.CHILD_ID = X.PARENT_ID
		JOIN PRODUCTS P2 ON P2.PRODUCT_ID = XX.ITEM_ID
	JOIN PRODUCTS P ON P.PRODUCT_ID = X.ITEM_ID
	LEFT JOIN MFR_ITEMS_TYPES IT ON IT.TYPE_ID = X.ITEM_TYPE_ID
WHERE X.IS_BUY = 1
GO
