IF OBJECT_ID('V_SDOCS_MFR_DRAFTS_ITEMS') IS NOT NULL DROP VIEW V_SDOCS_MFR_DRAFTS_ITEMS
GO
-- SELECT TOP 100 * FROM V_SDOCS_MFR_DRAFTS_ITEMS
CREATE VIEW V_SDOCS_MFR_DRAFTS_ITEMS
AS
SELECT 
	X.ID,
	D.MFR_DOC_ID,
	MFR_NUMBER = MFR.NUMBER,
	X.DRAFT_ID,
	X.PLACE_ID,
	ITEM_DRAFT_ID = REF.DRAFT_ID,
	X.ITEM_ID,
	X.IS_BUY,
	X.IS_SWAP,
	X.ITEM_TYPE_ID,
	ITEM_TYPE_NAME = IT.NAME,
	ITEM_NAME = P.NAME,
	P.NAME, -- alias for picker
	U.UNIT_ID,
	X.UNIT_NAME,
	X.Q_NETTO,
	X.Q_BRUTTO,
	X.NUMBERS,
	X.ADD_DATE,
	X.ADD_MOL_ID,
	X.UPDATE_DATE,
	X.UPDATE_MOL_ID,
	X.IS_DELETED
FROM SDOCS_MFR_DRAFTS_ITEMS X WITH(NOLOCK)
	JOIN SDOCS_MFR_DRAFTS D WITH(NOLOCK) ON D.DRAFT_ID = X.DRAFT_ID AND D.IS_DELETED = 0
		JOIN MFR_SDOCS MFR WITH(NOLOCK) ON MFR.DOC_ID = D.MFR_DOC_ID
		LEFT JOIN (
			SELECT MFR_DOC_ID, PRODUCT_ID, ITEM_ID,
				DRAFT_ID = MIN(DRAFT_ID)
			FROM SDOCS_MFR_DRAFTS WITH(NOLOCK)
			WHERE IS_DELETED = 0
			GROUP BY MFR_DOC_ID, PRODUCT_ID, ITEM_ID
		) REF ON REF.MFR_DOC_ID = D.MFR_DOC_ID 
			AND REF.PRODUCT_ID = D.PRODUCT_ID
			AND REF.ITEM_ID = X.ITEM_ID
	JOIN PRODUCTS P WITH(NOLOCK) ON P.PRODUCT_ID = X.ITEM_ID
	LEFT JOIN PRODUCTS_UNITS U WITH(NOLOCK) ON U.NAME = X.UNIT_NAME
	LEFT JOIN MFR_ITEMS_TYPES IT WITH(NOLOCK) ON IT.TYPE_ID = X.ITEM_TYPE_ID		
WHERE X.IS_DELETED = 0
GO
