IF OBJECT_ID('V_SDOCS_R_STOCKS_TURNS_DOCS') IS NOT NULL DROP VIEW V_SDOCS_R_STOCKS_TURNS_DOCS
GO
-- SELECT top 10 * FROM V_SDOCS_R_STOCKS_TURNS_DOCS
CREATE VIEW V_SDOCS_R_STOCKS_TURNS_DOCS
AS
    SELECT
        X.MOL_ID,
        X.PRODUCT_ID,
        X.TURN_TYPE_ID,
        ISNULL(X.ACC_REGISTER_ID, 0) as ACC_REGISTER_ID,
        ISNULL(X.PRINCIPAL_DOGOVOR_ID, 0) as PRINCIPAL_DOGOVOR_ID,
        ISNULL(X.STOCK_ID, 0) as STOCK_ID,
        S.NAME as STOCK_NAME,
        CONCAT(
            CASE WHEN ACC.NAME IS NOT NULL THEN 'КРУ=' + ACC.NAME + ' ' END,
            CASE WHEN DG.NAME IS NOT NULL THEN 'Принципал=' + DG.NAME END
        ) AS NOTE,
        X.DOC_ID,
        X.D_DOC,
        X.NUMBER,
        U.NAME as UNIT_NAME,
        Q_START,
        Q_INPUT,
        Q_OUTPUT,
        Q_END
    FROM SDOCS_R_STOCKS_TURNS X
        LEFT JOIN SDOCS_STOCKS S ON S.STOCK_ID = X.STOCK_ID
        LEFT JOIN ACCOUNTS_REGISTERS ACC ON ACC.ACC_REGISTER_ID = X.ACC_REGISTER_ID
        LEFT JOIN DOCS_PRINCIPALS_DOGOVORS DG ON DG.DOCUMENT_ID = X.PRINCIPAL_DOGOVOR_ID
        JOIN PRODUCTS_UNITS U ON U.UNIT_ID = X.UNIT_ID
GO
