IF OBJECT_ID('V_SDOCS_R_STOCKS_TURNS_PRODUCTS') IS NOT NULL DROP VIEW V_SDOCS_R_STOCKS_TURNS_PRODUCTS
GO
-- SELECT * FROM V_SDOCS_R_STOCKS_TURNS_PRODUCTS
CREATE VIEW V_SDOCS_R_STOCKS_TURNS_PRODUCTS
AS

SELECT 
    X.MOL_ID,
    X.PRODUCT_ID, 
    PRODUCT_NAME = P.NAME, 
    UNIT_NAME = U.NAME, 
    Q_START, 
    Q_INPUT, 
    Q_OUTPUT, 
    Q_END
FROM SDOCS_R_STOCKS_TURNS_RESULTS X
    JOIN PRODUCTS P ON P.PRODUCT_ID = X.PRODUCT_ID
    JOIN PRODUCTS_UNITS U ON U.UNIT_ID = X.UNIT_ID
WHERE 
    ABS(Q_END) > 1E-4 OR Q_INPUT > 1E-4 OR Q_OUTPUT > 1E-4

GO
