IF OBJECT_ID('V_SDOCS_MFR_DRAFTS') IS NOT NULL DROP VIEW V_SDOCS_MFR_DRAFTS
GO
-- SELECT TOP 100 * FROM V_SDOCS_MFR_DRAFTS
CREATE VIEW V_SDOCS_MFR_DRAFTS
AS
SELECT 
	X.DRAFT_ID,
	X.PDM_ID,
	X.TYPE_ID,
	X.PLAN_ID,
	X.MFR_DOC_ID,
	X.PRODUCT_ID,
	X.ITEM_ID,
	ITEM_NAME = P.NAME,
	X.IS_BUY,
	X.ITEM_PRICE0,
	X.UNIT_NAME,
	MFR_NUMBER = SD.NUMBER,
	X.STATUS_ID,
	STATUS_NAME = S.NAME,
	X.D_DOC,
	X.NUMBER,
	X.MOL_ID,
	MOL_NAME = M.NAME,
	X.EXECUTOR_ID,
	X.ADD_MOL_ID,
	X.CONTEXT,
	X.NOTE,
	X.OPERS_COUNT,
	X.IS_ROOT,	
	X.IS_PRODUCT,	
	X.WORK_TYPE_1,
	X.WORK_TYPE_2,	
	X.WORK_TYPE_3,
	X.IS_DELETED,	
	X.UPDATE_DATE
FROM SDOCS_MFR_DRAFTS X WITH (NOLOCK)
	JOIN SDOCS_MFR_DRAFTS_STATUSES S WITH (NOLOCK) ON S.STATUS_ID = X.STATUS_ID
	LEFT JOIN MFR_PLANS PL WITH (NOLOCK) ON PL.PLAN_ID = X.PLAN_ID
	LEFT JOIN SDOCS SD WITH (NOLOCK) ON SD.DOC_ID = X.MFR_DOC_ID
	LEFT JOIN PRODUCTS P WITH (NOLOCK) ON P.PRODUCT_ID = X.ITEM_ID
	LEFT JOIN MOLS M WITH (NOLOCK) ON M.MOL_ID = X.MOL_ID
GO
