IF OBJECT_ID('V_SUPPLY_R_INVPAYS') IS NOT NULL DROP VIEW V_SUPPLY_R_INVPAYS
GO
-- SELECT TOP 50 * FROM V_SUPPLY_R_INVPAYS
CREATE VIEW V_SUPPLY_R_INVPAYS
AS
SELECT    
    X.ROW_ID,
    ACC_REGISTER_NAME = REG.NAME,
    X.PLAN_ID,
    PLAN_NAME = PL.NUMBER,
    MFR_DOC_ID = ISNULL(x.MFR_DOC_ID, 0),
    MFR_NUMBER = MFR.NUMBER,
    MFR.D_ISSUE_PLAN,
    AGENT_NAME = A1.NAME,
    DEAL_NUMBER = DL.NUMBER,
    X.PRODUCT_ID,
    PRODUCT_NAME = P1.NAME,
    X.ITEM_ID,
    ITEM_NAME = P2.NAME,
    MANAGER_NAME = MOLS.NAME,
    INV_ID,
    INV_D_PLAN,
    INV_D_CONDITION,
    INV_NUMBER = I.NUMBER,    
    INV_CONDITION,
    INV_CONDITION_PAY,
    INV_CONDITION_FUND,
    INV_D_DOC = I.D_DOC,
    X.INV_MILESTONE_ID,
    INV_MILESTONE = CONCAT(MS.MILESTONE_ID, '.', MS.NAME),
    VENDOR_NAME = ISNULL(A2.NAME, A3.NAME),
    VENDOR_INN = ISNULL(A2.INN, A3.INN),
    INV_MS_D_PLAN,
	INV_D_PLAN_MONTH = LEFT(CONVERT(VARCHAR, X.INV_D_PLAN, 20), 7),
	INV_D_PLAN_WEEK = DATEPART(ISO_WEEK, X.INV_D_PLAN),		
    INV_MS_D_FACT,
    INV_D_MFR,
    INV_D_MFR_TO,
    FINDOC_DATE,
    X.FINDOC_ID,
    INV_VALUE,
    SHIP_VALUE = INV_Q_SHIP / NULLIF(INV_Q, 0) * INV_VALUE,
    FINDOC_VALUE,
    INV_FUND_VALUE,
    X.NOTE
FROM SUPPLY_R_INVPAYS X
    LEFT JOIN SDOCS_MFR MFR ON MFR.DOC_ID = X.MFR_DOC_ID
        LEFT JOIN AGENTS A1 ON A1.AGENT_ID = MFR.AGENT_ID
        LEFT JOIN DEALS DL ON DL.DEAL_ID = MFR.DEAL_ID
    LEFT JOIN PRODUCTS P1 ON P1.PRODUCT_ID = X.PRODUCT_ID
    LEFT JOIN PRODUCTS P2 ON P2.PRODUCT_ID = X.ITEM_ID
    LEFT JOIN SDOCS_MILESTONES_NAMES MS ON MS.MILESTONE_ID = X.INV_MILESTONE_ID
    LEFT JOIN SUPPLY_INVOICES I ON I.DOC_ID = X.INV_ID
        LEFT JOIN AGENTS A2 ON A2.AGENT_ID = I.AGENT_ID
        LEFT JOIN MOLS ON MOLS.MOL_ID = I.MOL_ID
    LEFT JOIN FINDOCS FD ON FD.FINDOC_ID = X.FINDOC_ID
        LEFT JOIN AGENTS A3 ON A3.AGENT_ID = FD.AGENT_ID
    LEFT JOIN MFR_PLANS PL ON PL.PLAN_ID = X.PLAN_ID
    LEFT JOIN ACCOUNTS_REGISTERS REG ON REG.ACC_REGISTER_ID = X.ACC_REGISTER_ID
GO
