IF OBJECT_ID('V_TASKS') IS NOT NULL DROP VIEW V_TASKS
GO
CREATE VIEW V_TASKS
AS
SELECT
	T.TASK_ID,
    T.PROJECT_TASK_ID,
	T.TYPE_ID,
	T.D_DOC,
	T.D_CLOSED,
    T.THEME_ID,
	THEME_NAME = ISNULL(THEMES.NAME, TYPES.NAME),
	T.TITLE,
	T.AUTHOR_ID,
	M1.NAME AS AUTHOR_NAME,
	T.ANALYZER_ID,
	M2.NAME AS ANALYZER_NAME,
    T.OWNER_ID,
    T.STATUS_ID,
    T.D_DEADLINE,
	T.REFKEY,
	T.REFNAME,
	T.EXECUTOR_NAME,
    T.ADD_DATE,
	T.UPDATE_DATE
FROM TASKS T
	LEFT JOIN TASKS_TYPES TYPES ON TYPES.TYPE_ID = T.TYPE_ID
	LEFT JOIN TASKS_THEMES THEMES ON THEMES.THEME_ID = T.THEME_ID
	LEFT JOIN MOLS M1 ON M1.MOL_ID = T.AUTHOR_ID
	LEFT JOIN MOLS M2 ON M2.MOL_ID = T.ANALYZER_ID
GO
